### PR TITLE
Fix 5419: iATM ranges incorrect

### LINKED ISSUE #5419: iATMs do not work correctly in weapon bays
### Environment
MegaMek Version: MekHQ v0.49.19 Development Snapshot
Operating System: Mac
Java Version: 20.0.1

### Description

iATMs do not work correctly in ATM Bays, being limited to Medium range and allowing a choice of ammo within those brackets. Curiously, the original ATMs _do_ work correctly. This can be demonstrated in the attached screenshots, using the attached designs and save file.
image
image-2
[atmBayRangeExample.sav.gz](https://github.com/MegaMek/megamek/files/15114710/atmBayRangeExample.sav.gz)
[Union_C_C-Ph_Mk_IV.blk](https://github.com/MegaMek/megamek/files/15114756/Union_C_C-Ph_Mk_IV.blk.txt)

### PR DESCRIPTION
**Pull request by Sleet01**
Initial issue was that iATM weapon bays did not accurately reflect their selected ammo.
In the process of investigating this I discovered a number of issues:

1. iATMs are not covered by most code that handles ATMs
2. iATMs are not considered Streak weapons for Princess planning purposes
3. iATM ammo types are not considered by Princess when guessing at expected damage from prospective attacks
4. ATM and iATM weapon ranges are retrieved, re-calculated, overwritten, and recreated from magic numbers _multiple_ times every turn for each launcher due to redundant code throughout WeaponType, WeaponFireInfo, WeaponAttackAction, and the WeaponPanel GUI elements.
5. The merge of PR #5406 reverted at least some of the Princess ammo selection code; any other code merged after 02/08/2024 is also suspect.

This PR fixes 1-4 and part of 5.

Testing:
- Re-ran all projects' unit tests (note: MHQ unit tests were already failing for other reasons)
- Tested extensively with player-controlled and bot-controlled Aerospace units mounting iATMs
- Built custom Dropships to confirm iATM bays functioning as expected.

Note: appears to be blocked by #5423 

Close #5419

### CODE REVIEW

File: megamek/src/megamek/common/Compute.java [hunk 1]
```diff
@@ -3211,27 +3211,33 @@ public static float getExpectedDamage(Game g, WeaponAttackAction waa,
...
+        if (use_table) {
             if (!(attacker instanceof BattleArmor)) {
                 if (weapon.getLinked() == null) {
                     return 0.0f;
                 }
             }
+
             AmmoType at = null;
-            if ((weapon.getLinked() != null)
+            if (waa.getAmmoId() != -1) {
```
Comment (HoneySkull) [inline megamek/src/megamek/common/Compute.java:3222]: What does -1 mean here?  Not linked?  Maybe a constant for readability?

Comment (Sleet01) [reply megamek/src/megamek/common/Compute.java:3222]: Ah, right.  -1 is "Unset", and I believe there is a constant, let me grab that...

Comment (Sleet01) [reply megamek/src/megamek/common/Compute.java]: I have created the constant and replaced the magic number "-1" where appropriate.

**Comment by SJuliez** [comment]
@Sleet01 Not sure from your inital comment: Is this safer to merge?

**Comment by Sleet01** [comment]
> @Sleet01 Not sure from your inital comment: Is this safer to merge?

Yes.
This will fix the reported issue and restore Princess ammo selection in the current .20 dev branch.
It should also be fine to re-apply if we do end up pulling out the last week of merges and re-building everything.
Also, it appears that a fix for #5423 has already been merged so this should no longer be blocked.

**Review by SJuliez — APPROVED** [review]
