### PR TITLE
Fix Artillery units not losing autohit mod after spending mp

### LINKED ISSUE #6929: Artillery auto-hit hexes not lost on MP expenditure
### Brief Description *

Tactical Operations: Advanced Rules page 150 indicates that if an artillery unit expends MP after successfully hitting a targeted hex, that hex can no longer be automatically hit. Megamek does not appear to implement this rule.

### 3. Steps to Reproduce

1. Load the provided save with an auto-hit hex active.
2. Expend MP in any way (turn in place, move forward and back into the same hex, etc.).
3. During the Targeting Phase of the next round, observe that the hex can still be automatically hit.

### Attach Files

Save with auto-hit active:
[autohit-active.sav.gz](https://github.com/user-attachments/files/19900543/autohit-active.sav.gz)

A save prior to the targeted hex being struck (with a significant fire correction bonus) is also provided in case anything that occurs when the hex is hit would be useful for debugging this issue.
[pre-autohit.sav.gz](https://github.com/user-attachments/files/19900538/pre-autohit.sav.gz)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MegaMek Suite Version *

0.50.04

### Operating System *

Windows 10

### Java Version *

Java 17.0.11

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by Sleet01**
Fix for Artillery units moving but keeping their auto-hit mods on hexes they've already hit.
This patch adds a new method to the ArtilleryTracker to remove _only_ those autohit mods when a unit expends MP.

Note that other mods (such as base artillery mod, spotter adjustment mod, etc.) should not be modified by this method, as only the auto-hit mod is lost after movement (per TO:AR rules).

Testing:
- Tested with games vs Princess including on- and off-board artillery on various unit types
- Added unit tests
- Ran all 3 projects' unit tests

Close #6929

### CODE REVIEW

File: megamek/src/megamek/server/totalwarfare/MovePathHandler.java [hunk 1]
```diff
@@ -125,6 +125,12 @@ class MovePathHandler extends AbstractTWRuleHandler {
     }
 
     void processMovement() {
+        if (md.getMpUsed() > 0) {
+            // All auto-hit hexes for this unit (not including preset targets) are cleared
+            // if any MP are expended.
+            entity.aTracker.clearHitHexMods();
```
Comment (Scoppio) [inline megamek/src/megamek/server/totalwarfare/MovePathHandler.java:131]: I think a report would be reasonable for this. But not vital.

**Review by Scoppio — APPROVED** [review]

File: megamek/src/megamek/server/totalwarfare/MovePathHandler.java (hunk 1 above)
Comment (Sleet01) [reply megamek/src/megamek/server/totalwarfare/MovePathHandler.java:131]: Sorry, I had stepped away for dinner.
The only issue with reporting is that this is happening during the movement phase, as each move is executed, so reports inserted here would be interleaved with the normal movement reporting.
It feels a little wrong to insert reports about lost auto-hit artillery mods into the move report, but we could store the removed Coords _in_ the ArtilleryTracker and report them during the next Indirect Phase report...
Actually, it might be good to report any auto-hit mods on a per-unit basis as well since we don't do that either.
I'll file an RFE, but I think it's outside the sope of this fix.
