### PR TITLE
Fix #4790: uncaught NPE when Sniper Turret fired on fleeing off-board target

### LINKED ISSUE #4790: NullPointerException at firing phase start
### Environment
MekHQ 0.49.14
Windows 10
Java 17.0.8

### Description
NullPointerException when starting firing phase - seems to be artillery related?

### Files
[megamek.log](https://github.com/MegaMek/mekhq/files/12517800/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/12517801/mekhq.log)

[Czechoslovak Foreign Legion30270919.cpnx.gz](https://github.com/MegaMek/mekhq/files/12517807/Czechoslovak.Foreign.Legion30270919.cpnx.gz)

Savegame: advance turn to firing phase to get NullPointerException. I had a Thumper artillery vehicle off screen, but I fled it to avoid sniper turret counterfire
[autosave.sav.gz](https://github.com/MegaMek/mekhq/files/12517810/autosave.sav.gz)

Custom mechs: Dervish and Archer are in this battle
[Czechoslovak Foreign Legion.zip](https://github.com/MegaMek/mekhq/files/12517859/Czechoslovak.Foreign.Legion.zip)

### PR DESCRIPTION
**Pull request by Sleet01**
Issue is that target is null by the time we get around to handling this indirect attack, because it has fled already.

Fix is to ignore this failure and just log the incident, as there doesn't seem to be any way to resolve damage from a missed counter-battery attack on an off-board target that has fled.

Tested by implementing this code in 0.49.14 and running OP's save file past the point that previously got hung.

close #4790

### CODE REVIEW

File: megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectFireHandler.java [hunk 1]
```diff
@@ -103,7 +103,16 @@ public boolean handle(GamePhase phase, Vector<Report> vPhaseReport) {
         }
 
         final Vector<Integer> spottersBefore = aaa.getSpotterIds();
-        Coords targetPos = target.getPosition();
+
+        // Handle counter-battery on fleeing/fled off-board targets.
+        Coords targetPos;
+        try {
+            targetPos = target.getPosition();
```
Comment (NickAragua) [inline megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectFireHandler.java:110]: If you know what the problem is (target == null), then you may as well check for that instead of using a try/catch block.

**Review by NickAragua — CHANGES_REQUESTED** [review]
Right idea, but can be done without a try/catch block.

File: megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectFireHandler.java (hunk 1 above)
Comment (Sleet01) [reply megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectFireHandler.java:110]: Yeah, I'd tried a more involved solution before paring it back to this - but had forgotten how much worse the try/catch performance is compared to just `if (null == X)`.

**Review by NickAragua — APPROVED** [review]
