### PR TITLE
Issue: #4152 - LAM does not suffer +3 to-hit penalty on turn it chang…

### LINKED ISSUE #4152: LAM does not suffer +3 to hit penalty on turn it changes modes
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
0.49.11
Windows
Java 11

### Description
No to hit penalty applied on the turn a LAM changes mode.

IO:AE pp101 states "Converting LAMs may make attacks with a +3 to-hit modifier during the turn they are converting"

To reproduce, load save game, convert to Mech mode (hit Convert Mode TWICE so it shows "1. Convert Mode") then fire.

Observe lack of +3 modifier.

### Files
Save game attached - ready to convert one of the mechs from AirMech back to Mech
Image showing to hit calcs for mech that just converted this turn
[LAM not applying conversion to hit mod - autosave.gz](https://github.co
NoToHitPenaltyForModeConversion
m/MegaMek/megamek/files/10574086/LAM.not.applying.conversion.to.hit.mod.-.autosave.gz)

### PR DESCRIPTION
**Pull request by HammerGS**
LAM does not suffer +3 to-hit penalty on turn it chanes modes

Fixes #4152        

  Files Modified:

  1. megamek/src/megamek/common/actions/compute/ComputeAttackerToHitMods.java (lines 165-168)
    - Added LAM conversion check after the existing QuadVee check
  2. megamek/resources/megamek/client/messages.properties (line 4194)
    - Added WeaponAttackAction.LAMConverting=converting

  Changes:
  // LAM converting to a new mode (IO:AE p.101)
  if (attacker instanceof LandAirMek && attacker.isConvertingNow()) {
      toHit.addModifier(+3, Messages.getString("WeaponAttackAction.LAMConverting")); }

  The fix follows the existing pattern used for QuadVees and leverages the isConvertingNow() flag that is already
  properly set during LAM mode conversion.

### CODE REVIEW

File: megamek/unittests/megamek/common/actions/ProneTargetPhysicalAttackTest.java [hunk 1]
```diff
@@ -0,0 +1,272 @@
...
+ * </ul>
+ *
+ * <p>Full integration testing is performed via manual in-game testing as the physical attack
+ * toHit methods require extensive Game/Entity setup. These unit tests document and verify
+ * the elevation difference calculations used in the implementation.
+ *
+ * @see PunchAttackAction
+ * @see ClubAttackAction
+ * @see KickAttackAction
+ * @see <a href="https://github.com/MegaMek/megamek/issues/5713">GitHub Issue #5713</a>
```
Comment (psikomonkie) [inline megamek/unittests/megamek/common/actions/ProneTargetPhysicalAttackTest.java:81]: Should this be in this PR?

File: megamek/unittests/megamek/common/actions/compute/PrototypeDniToHitModsTest.java [hunk 2]
```diff
@@ -0,0 +1,275 @@
...
+import org.junit.jupiter.api.BeforeEach;
+import org.junit.jupiter.api.DisplayName;
+import org.junit.jupiter.api.Nested;
+import org.junit.jupiter.api.Test;
+
+/**
+ * Tests for Prototype Direct Neural Interface (Proto DNI) to-hit modifiers. Per IO pg 83, Proto DNI provides -2 gunnery
+ * modifier. Proto DNI takes precedence over VDNI/BVDNI and doesn't stack with them.
+ *
+ * @see ComputeAttackerToHitMods#compileCrewToHitMods
```
Comment (psikomonkie) [inline megamek/unittests/megamek/common/actions/compute/PrototypeDniToHitModsTest.java:58]: If this is for testing a method in `ComputeAttackerToHitMods` then this should probably be in a class called `ComputeAttackerToHitModsTest`, unless there's a good reason to split that into multiple classes.

File: megamek/unittests/megamek/common/actions/compute/ConversionToHitModsTest.java [hunk 3]
```diff
@@ -0,0 +1,199 @@
...
+import org.junit.jupiter.api.Test;
+import org.mockito.MockedStatic;
+
+/**
+ * Tests for mode conversion to-hit modifiers.
+ * <p>
+ * Per IO:AE p.101, LAMs suffer +3 to-hit when converting between modes. Per TM, QuadVees suffer +3 to-hit when
+ * converting between modes.
+ *
+ * @see ComputeAttackerToHitMods#compileAttackerToHitMods
```
Comment (psikomonkie) [inline megamek/unittests/megamek/common/actions/compute/ConversionToHitModsTest.java]: If this is for testing a method in ComputeAttackerToHitMods then this should probably be in a class called ComputeAttackerToHitModsTest, unless there's a good reason to split that into multiple classes.

File: megamek/unittests/megamek/common/actions/ProneTargetPhysicalAttackTest.java (hunk 1 above)
Comment (HammerGS) [reply megamek/unittests/megamek/common/actions/ProneTargetPhysicalAttackTest.java:81]: These tests where missed from previous PR's (just like the commit note). I figure being a test I'd commit with this PR.

File: megamek/unittests/megamek/common/actions/ProneTargetPhysicalAttackTest.java [hunk 4]
```diff
@@ -0,0 +1,272 @@
...
+ */
+public class ProneTargetPhysicalAttackTest {
```
Comment (psikomonkie) [inline megamek/unittests/megamek/common/actions/ProneTargetPhysicalAttackTest.java:83]: This test isn't testing anything. It's some private methods that look at the provided int and pass out true or false. There's no code being tested.

File: megamek/src/megamek/common/actions/compute/ComputeAttackerToHitMods.java [hunk 5]
```diff
@@ -162,6 +162,11 @@ public static ToHitData compileAttackerToHitMods(Game game, Entity attacker, Tar
             toHit.addModifier(+3, Messages.getString("WeaponAttackAction.QuadVeeConverting"));
         }
 
+        // LAM converting to a new mode (IO:AE p.101)
+        if (attacker instanceof LandAirMek && attacker.isConvertingNow()) {
+            toHit.addModifier(+3, Messages.getString("WeaponAttackAction.LAMConverting"));
+        }
```
[the remark this answers is not in the document]
Comment (HammerGS) [reply megamek/src/megamek/common/actions/compute/ComputeAttackerToHitMods.java:168]: https://github.com/MegaMek/megamek/pull/7822/commits/285a41914b712ac5043e29995143ce1fff569f32

File: megamek/unittests/megamek/common/actions/ProneTargetPhysicalAttackTest.java (hunk 4 above)
Comment (HammerGS) [reply megamek/unittests/megamek/common/actions/ProneTargetPhysicalAttackTest.java:83]: Should be resolved here - https://github.com/MegaMek/megamek/pull/7822/commits/17e573c24a709fcaa0a6b48a65c64e35c0e73b49

File: megamek/unittests/megamek/common/actions/compute/ConversionToHitModsTest.java (hunk 3 above)
Comment (HammerGS) [reply megamek/unittests/megamek/common/actions/compute/ConversionToHitModsTest.java]: Should be resolved here - https://github.com/MegaMek/megamek/pull/7822/commits/17e573c24a709fcaa0a6b48a65c64e35c0e73b49

File: megamek/unittests/megamek/common/actions/compute/PrototypeDniToHitModsTest.java (hunk 2 above)
Comment (HammerGS) [reply megamek/unittests/megamek/common/actions/compute/PrototypeDniToHitModsTest.java:58]: Should be resolved here - https://github.com/MegaMek/megamek/pull/7822/commits/17e573c24a709fcaa0a6b48a65c64e35c0e73b49

File: megamek/src/megamek/common/actions/compute/ComputeAttackerToHitMods.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (HammerGS) [reply megamek/src/megamek/common/actions/compute/ComputeAttackerToHitMods.java:168]: Should be resolved here - https://github.com/MegaMek/megamek/pull/7822/commits/17e573c24a709fcaa0a6b48a65c64e35c0e73b49

**Comment by HammerGS** [comment]
Working on the failing tests.
