### PR TITLE
Simplify Hex class to handle on board check

### LINKED ISSUE #6686: [0.50.04-SNAPSHOT] NPE during deployment: Cannot invoke "megamek.common.Hex.isOnBoard()" because "mhex" is null
### Brief Description *

NPE during deployment phase. Might be caused by the new code that shows the unit's current terrain type in the info box since during deployment the unit doesn't have a terrain type yet?

I found that if I just click through and deploy all of my units, the issue no longer occurs.

`10:44:04,070 ERROR [megamek.client.AbstractClient] {AWT-EventQueue-0}
megamek.client.AbstractClient.handlePacket(AbstractClient.java:402) - Failed to parse Packet command of TURN
java.lang.NullPointerException: Cannot invoke "megamek.common.Hex.isOnBoard()" because "mhex" is null
	at megamek.client.ui.swing.unitDisplay.SummaryPanel.displayMek(SummaryPanel.java:165)
	at megamek.client.ui.swing.unitDisplay.UnitDisplay.updateDisplay(UnitDisplay.java:473)
	at megamek.client.ui.swing.unitDisplay.UnitDisplay.displayEntity(UnitDisplay.java:458)
	at megamek.client.ui.swing.DeploymentDisplay.selectEntity(DeploymentDisplay.java:244)
	at megamek.client.ui.swing.DeploymentDisplay.beginMyTurn(DeploymentDisplay.java:273)
	at megamek.client.ui.swing.DeploymentDisplay.gameTurnChange(DeploymentDisplay.java:441)
	at megamek.common.event.GameTurnChangeEvent.fireEvent(GameTurnChangeEvent.java:46)
	at megamek.common.AbstractGame.fireGameEvent(AbstractGame.java:196)
	at megamek.common.Game.processGameEvent(Game.java:759)
	at megamek.common.Game.setTurnIndex(Game.java:700)
	at megamek.client.Client.changeTurnIndex(Client.java:1271)
	at megamek.client.Client.handleGameSpecificPacket(Client.java:979)
	at megamek.client.AbstractClient.handlePacket(AbstractClient.java:394)
	at megamek.client.AbstractClient$1.lambda$packetReceived$0(AbstractClient.java:566)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)`

Image

### 3. Steps to Reproduce

1. During deployment phase, click on the second unit in the list
2. NPE should appear

### Attach Files

[buggedunits.sav.gz](https://github.com/user-attachments/files/19232319/buggedunits.sav.gz)

[megamek.log](https://github.com/user-attachments/files/19232346/megamek.log)

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### MegaMek Suite Version *

0.50.04-SNAPSHOT     Build Date: 2025-03-13T03:29:18.817249738

### Operating System *

Windows 10

### Java Version *

Java Vendor: Eclipse Adoptium     Java Version: 17.0.6

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by mkdillard**
Refactor the isOnBoard approach to fix the load save serialization issue:
 * Remove the isOnBoard flag from Hex class.
 * Hex.isOnBoard() always returns true, Hex.isOffBoard() always returns false
 * Create OffBoardHex class to extend Hex, this object is returned whenver Board.getHex() is given coords not on the board.
 * OffBoardHex.isOnBoard() always returns false, OffBoardHex.isOffBoard() always returns true.

Also fixes #6686 by restoring the specific null check for the hex of an undeployed mek.

### CODE REVIEW

File: megamek/src/megamek/common/OffBoardHex.java [hunk 1]
```diff
@@ -0,0 +1,18 @@
+package megamek.common;
+
+public class OffBoardHex extends Hex {
+
+    OffBoardHex() {
+        super();
+    }
```
Comment (Sleet01) [inline megamek/src/megamek/common/OffBoardHex.java:7]: I _believe_ you can leave the constructor out and it will automatically call the super constructor, but I'd need to double-check that.

File: megamek/src/megamek/common/util/SerializationHelper.java [hunk 2]
```diff
@@ -26,6 +26,7 @@
 import com.thoughtworks.xstream.io.HierarchicalStreamWriter;
 
 import megamek.common.Coords;
+import megamek.common.Hex;
```
Comment (Sleet01) [inline megamek/src/megamek/common/util/SerializationHelper.java:29]: Probably don't need this anymore.

**Review by Sleet01 — APPROVED** [review]
Couple of things that might be removable, but looks good.
