### PR TITLE
 Fix Rapid-Fire AC Special Ammunition (Option B)

### LINKED ISSUE #5829: [49.19.1] Flak rounds do not roll cluster when used during a rapid fire AutoCannon attack
### Environment
49.19.1
Windows
Java 11

### Description
I can obtain screenshots if necessary but I've seen it enough times due to my turrets being added into MM that I know it occurs. At least in 49.19.1 None the less
https://bg.battletech.com/forums/index.php?topic=85660.0
In this rules question I asked if munitions that were supposed to use the cluster table needed to roll cluster again after rolling cluster for number of shots that hit. With the answer being yes, this is very much not the methodology used within MM. Most likely because it is a VERY unique situation that most of us never really thought about.

If anyone wants me to obtain a screenshot just poke me here or on the Discord. I can do it fairly quick.

### Files
N/A

### LINKED ISSUE #7705: [Issue] Armor Piercing Ammo does not roll for TACs when the autocannon fires on "Rapid" mode.
### Brief Description *

Both regular AP ammo and the playtest AP ammo do not roll for TACs when fired on "rapid". They still roll for TACs as normal when fired in single shot mode.

### 3. Steps to Reproduce

1. Start game of Megamek with one unit with AP ammo.
2. Fire AP ammo at enemy with the autocannon set to "rapid".
3. Observe that no TACs are rolled even on a hit.

### Attach Files

[MessingAround.sav.gz](https://github.com/user-attachments/files/23888870/MessingAround.sav.gz)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MegaMek Suite Version *

50.10

### Operating System *

Windows 11 10.0 (amd64)

### Java Version *

19.0.1

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by HammerGS**
Fix Rapid-Fire AC Special Ammunition
 
Fixes #5829 

Fixes #7705

Replaces https://github.com/MegaMek/megamek/pull/7710
  Summary

  Rapid-fire autocannons were losing special ammunition effects when fired in rapid-fire mode. This PR fixes the issue by spawning individual auto-hit attacks for each shot that hits, allowing existing specialized handlers (ACAPHandler, ACFlakHandler, etc.) to apply their ammunition-specific effects.

  Approach

  Option B: Spawn Auto-Hit Attacks

  When a rapid-fire AC fires with special ammunition:
  1. RapidFireACWeaponHandler calculates how many shots hit using the cluster table
  2. For each hit, it spawns an auto-hit attack using the existing specialized handler
  3. Each spawned attack applies the ammunition's special effects (AP crit modifier, flechette damage reduction, etc.)

  This approach reuses existing handler code rather than duplicating logic into new rapid-fire-specific handlers.

  Files Changed

  | File                          | Change                                                                  |
  |-------------------------------|-------------------------------------------------------------------------|
  | ACWeapon.java                 | Added auto-hit detection to skip rapid-fire routing for spawned attacks |
  | RapidFireACWeaponHandler.java | Added hasSpecialAmmo() check and spawnAutoHitAttacks() method           |
  | AmmoWeaponHandler.java        | Added check to skip ammo consumption for spawned rapid-fire attacks     |
  | TWDamageManagerModular.java   | Added Battle Armor trooper identification in armor remaining messages   |
  | report-messages.properties    | Added messages 6096/6097 for BA-specific armor remaining format         |

  Special Ammunition Support

  | Ammo Type      | Effect                                             | Status   |
  |----------------|----------------------------------------------------|----------|
  | Armor-Piercing | -2 crit roll modifier                              | ✅ Tested |
  | Caseless       | Different jam mechanics                            | ✅ Tested |
  | Flak           | Fragment cluster damage vs aerospace               | ✅ Tested |
  | Flechette      | Half damage vs hardened targets, bonus vs infantry | ✅ Tested |
  | Tracer         | -1 damage per hit, night combat to-hit bonus       | ✅ Tested |
  | Incendiary     | Excluded - retconned per FMFS pg 158               | N/A      |

  Technical Details

  Auto-hit marker: Spawned attacks use TargetRoll.AUTOMATIC_SUCCESS with a "rapid-fire hit" description marker to:
  - Prevent infinite recursion (ACWeapon skips rapid-fire routing for auto-hits)
  - Allow AmmoWeaponHandler to skip ammo consumption (parent already consumed ammo)

  Ammo consumption: The parent RapidFireACWeaponHandler consumes ammo for all shots. Spawned attacks detect the rapid-fire marker and skip
  consumption to prevent double-counting.

  Additional Fix: Battle Armor Armor Remaining Messages

  During Flak testing, discovered that Battle Armor "Armor remaining" messages didn't identify which trooper was hit. Added trooper identification:

  Before:
  5 Armor remaining.
  9 Armor remaining.

  After:
  Trooper 1: 5 Armor remaining.
  Trooper 3: 9 Armor remaining.

  Test Plan

  - AP ammo: Verify -2 crit modifier appears in combat log
  - Caseless ammo: Verify jam mechanics work correctly
  - Flak ammo: Verify fragment damage against aerospace/VTOL targets
  - Flechette ammo: Verify half damage vs hardened, bonus vs infantry
  - Tracer ammo: Verify -1 damage per hit and night combat modifier
  - Battle Armor: Verify trooper identification in armor messages
  - Ammo consumption: Verify correct ammo count after firing

### CODE REVIEW

File: megamek/src/megamek/server/totalWarfare/TWDamageManagerModular.java [hunk 1]
```diff
@@ -2195,15 +2195,18 @@ public void damageInfantry(Vector<Report> reportVec, Infantry infantry, HitData
 
                     infantry.damageThisPhase += tmpDamageHold;
                     damage = 0;
-                    if (!infantry.isHardenedArmorDamaged(hit)) {
-                        report = new Report(6085);
+                    // Use trooper-specific messages for Battle Armor
+                    if (infantry instanceof BattleArmor) {
```
Comment (Sleet01) [inline megamek/src/megamek/server/totalWarfare/TWDamageManagerModular.java]: Couple points:
1. we try\* to keep each Pull Request focused on one fix/feature (\*not always successfully)
2. BA damage should not come through `TWDamageManagerModular.damageInfantry()` at all, as there is a check to separate regular infantry and BA damage assignments.

This should probably be in a different PR, and BA-specific handling should be in `TWDamageManagerModular.damageBA()` (unless there is a separate bug here).

File: megamek/src/megamek/server/totalWarfare/TWDamageManagerModular.java [hunk 2]
```diff
@@ -3046,15 +3049,18 @@ public int applyEntityArmorDamage(Entity entity, HitData hit, int damage, boolea
                 entity.damageThisPhase += damage;
 
                 damage = 0;
-                if (!entity.isHardenedArmorDamaged(hit)) {
-                    report = new Report(6085);
+                // Use trooper-specific messages for Battle Armor
+                if (entity instanceof BattleArmor) {
```
Comment (Sleet01) [inline megamek/src/megamek/server/totalWarfare/TWDamageManagerModular.java:3051]: Have separate BA and Infantry handling _here_ is probably okay, as this method is called for all unit types.

**Comment by HammerGS** [comment]
> I think the BA damage reporting snuck in by mistake; please move to a separate PR (and see comments).
> 
> Otherwise this looks good.

The BA damage report is really bad without. Basically just lists numbers I'd really rather keep it in.

File: megamek/src/megamek/server/totalWarfare/TWDamageManagerModular.java (hunk 1 above)
Comment (HammerGS) [reply megamek/src/megamek/server/totalWarfare/TWDamageManagerModular.java]: Left the comment below. The BA damage reporting is really bad without the fix.

**Comment by Sleet01** [comment]
> > I think the BA damage reporting snuck in by mistake; please move to a separate PR (and see comments).
> > Otherwise this looks good.
> 
> The BA damage report is really bad without. Basically just lists numbers I'd really rather keep it in.

The section in `damageInfantry()` shouldn't be doing anything; if it _does_ change the damage output, then there's a separate bug with how we're handling Infantry vs BA damage.

That said, I'm fine with including reporting cleanup pertaining to the new code if it makes the UX better.
