### PR TITLE
Consolidate the Clan TAG Bomb with the IS TAG Bomb

### LINKED ISSUE #7778: [Issue] TAG Pod (Clan) available too early
### Brief Description *

Image

Clan external TAG pods should probably not be available to IS units in 3046. 

### 3. Steps to Reproduce

_No response_

### Attach Files

[Clan.sav.gz](https://github.com/user-attachments/files/24147603/Clan.sav.gz)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MegaMek Suite Version *

50.10

### Operating System *

Windows 11

### Java Version *

Java 17

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by HammerGS**
Removes the Clan TAG Bomb, and adds the Clan Availability into the IS TAG Bomb and updating its tech to be ALL. 

They both share the same internal name

Fixes #7778

### CODE REVIEW

File: megamek/src/megamek/common/units/Entity.java [hunk 1]
```diff
@@ -133,7 +133,6 @@
 import megamek.common.weapons.bombs.clan.CLAAAMissileWeapon;
 import megamek.common.weapons.bombs.clan.CLASEWMissileWeapon;
 import megamek.common.weapons.bombs.clan.CLASMissileWeapon;
-import megamek.common.weapons.bombs.clan.CLBombTAG;
 import megamek.common.weapons.bombs.clan.CLLAAMissileWeapon;
```
[the remark this answers is not in the document]
Comment (HammerGS) [reply megamek/src/megamek/common/units/Entity.java:136]: Addressed

File: megamek/src/megamek/common/weapons/bombs/clan/CLBombTAG.java
Comment (IllianiBird) [inline megamek/src/megamek/common/weapons/bombs/clan/CLBombTAG.java:1]: How will this handle MekHQ campaigns with units that have a unit with this item loaded onto a unit, or in the warehouse?

Comment (HammerGS) [reply megamek/src/megamek/common/weapons/bombs/clan/CLBombTAG.java:1]: They use the same internal name so should just work. MekHQ campaigns store equipment by internal name

**Review by IllianiBird — APPROVED** [review]
