### PR TITLE
Fix 7543: Freeze using Tactical Genius

### LINKED ISSUE #7543: [Issue] 50.07 Game becoming stuck when rerolling initiative with Tactical Genius
### Brief Description *

When attempting to reroll initiative the game will not progress to showing the reroll and you cannot move past the initiative phase to continue the game. You can interact with the program, but it will not progress to the next phase and you're forced to exit out (I used the top right "x")

### 3. Steps to Reproduce

Used a fresh download and basic 1v1 for testing purposes
Added SPAs and used Tactical Genius (TG) > reroll worked
Loaded the options used in my campaign > reroll stuck
Reset Defaults, enabled SPAs for TG, enabled options matching campaign choices 1 tab at a time (starting from "RPG Related" and working back
Successful until I matched "Advanced Rules"
Checked each option on "Advanced Rules" tab until is stuck with "TacOps Double Blind"
Checked again with only SPAs and Double Blind enabled > reroll stuck

### Attach Files

[megamek log.zip](https://github.com/user-attachments/files/23237534/megamek.log.zip)

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### MegaMek Suite Version *

.50.07

### Operating System *

windows 10

### Java Version *

17.0.11

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by Sleet01**
In one code path, while attempting to notify players of an opportunity to use Tactical Genius, we were wrapping the Reports Vector in a new Vector _array_, which causes an exception.
This is sub-optimal.

This fix:
1. Reverts the change that adds the array creation,
2. Adds initiative info to the Player objects when passing Players around - Initiative info should be available to all players (even Bots) but previously we were failing to copy it when sending Player updates.
3. Give Princess simple logic for using Tactical Genius

Testing:
- Ran repro reported by OP
- Ran all 3 projects' unit tests

Fix #7543

### CODE REVIEW

File: megamek/src/megamek/client/bot/BotClient.java [hunk 1]
```diff
@@ -486,8 +489,15 @@ public void changePhase(GamePhase phase) {
                     endOfTurnProcessing();
                     // intentional fallthrough: all reports must click "done", otherwise the game
                     // never moves on.
-                case TARGETING_REPORT:
                 case INITIATIVE_REPORT:
+                    // Let bots use Tactical Genius
```
Comment (IllianiBird) [inline megamek/src/megamek/client/bot/BotClient.java:495]: image

File: megamek/src/megamek/client/bot/BotClient.java [hunk 2]
```diff
@@ -1368,6 +1378,34 @@ public String receiveReport(List<Report> reports) {
...
+                    otherRoll = other.getInitiative();
+                    if (otherRoll.size() > 0 &&
+                          myRoll.getRoll(myRoll.size() - 1) < otherRoll.getRoll(otherRoll.size() - 1)) {
+                        return true;
+                    }
+                }
+            }
+        }
+        return false;
+    }
```
Comment (IllianiBird) [inline megamek/src/megamek/client/bot/BotClient.java:1409]: So, my first impulse here is that I can foresee a situation where we are facing `n` players. Our initiative roll beats `n-1`, but because we failed to beat one other player we re-roll the whole lot and end up actually losing to everyone (or some other worse-than-original result).

So I put my brain-noggin into it and came up with the following, that should (if everything is right, no guarantees) give Princess a bit more intelligence over whether to use Genius or not.

Feel free to use the below, or don't, I mostly did it for my own edification:

```
/**
     * Determines whether Princess should reroll initiative using the Tactical Genius special ability.
     * 
     * <p>The decision is based on:</p>
     * 
     * <ul>
     *   <li>Whether Tactical Genius is available to the player</li>
     *   <li>Whether it has already been used this round</li>
     *   <li>The probability that rerolling will improve the net initiative outcome against enemies</li>
     * </ul>
     * 
     * <p>Princess will only reroll if currently losing more initiative comparisons than winning, and if the 
     * probability of improvement exceeds the configured threshold.</p>
     *
     * @return {@code true} if Tactical Genius should be used to reroll initiative
     */
    protected boolean decideToRerollInitiative() {
        Player me = getLocalPlayer();

        if (!game.hasTacticalGenius(me) || rerolledInitiative) {
            return false;
        }

        int myRoll = getLastInitiativeRoll(me);
        List<Integer> enemyRolls = game.getPlayersList().stream()
                                         .filter(p -> p != me && p.isEnemyOf(me))
                                         .map(this::getLastInitiativeRoll)
                                         .toList();

        int winsNow = countWins(myRoll, enemyRolls);
        int lossesNow = countLosses(myRoll, enemyRolls);

        // We're only interested in rerolling if we're actually losing overall.
        if (winsNow >= lossesNow) {
            return false;
        }

        double pMajority = probabilityOfMajorityWinOnReroll(enemyRolls);

        // Threshold can be tweaked; 0.5 = only reroll if it's more likely than not to help.
        double THRESHOLD = 0.5;
        return pMajority >= THRESHOLD;
    }

    /**
     * Retrieves the most recent initiative roll for the specified player.
     *
     * @param player the player whose initiative roll to retrieve
     * @return the player's last initiative roll value, or {@code 0} if no roll exists
     */
    private int getLastInitiativeRoll(Player player) {
        InitiativeRoll roll = player.getInitiative();
        if (roll == null || roll.size() == 0) {
            return 0;
        }
        return roll.getRoll(roll.size() - 1);
    }

    /**
     * Counts how many enemy initiative rolls Princess' roll beats.
     *
     * @param myRoll the initiative roll to compare
     * @param enemyRolls the list of enemy initiative rolls to compare against
     * @return the number of enemy rolls that are lower than myRoll
     */
    private int countWins(int myRoll, List<Integer> enemyRolls) {
        int wins = 0;
        for (int roll : enemyRolls) {
            if (myRoll > roll) {
                wins++;
            }
        }
        return wins;
    }

    /**
     * Counts how many enemy initiative rolls beat Princess' roll.
     *
     * @param myRoll the initiative roll to compare
     * @param enemyRolls the list of enemy initiative rolls to compare against
     * @return the number of enemy rolls that are higher than myRoll
     */
    private int countLosses(int myRoll, List<Integer> enemyRolls) {
        int losses = 0;
        for (int roll : enemyRolls) {
            if (myRoll < roll) {
                losses++;
            }
        }
        return losses;
    }

    /**
     * Calculates the probability that rerolling 2d6 initiative will result in beating more enemy rolls than lose to.
     * 
     * <p>Uses the standard 2d6 probability distribution to determine favorable outcomes, where a favorable outcome 
     * is defined as winning more initiative comparisons than losing.</p>
     *
     * @param enemyRolls the list of enemy initiative rolls to compare against
     * @return the probability (0.0 to 1.0) that a reroll will improve the net initiative outcome
     */
    private double probabilityOfMajorityWinOnReroll(List<Integer> enemyRolls) {
        // Number of ways to roll each total on 2d6
        int[] ways = { 0, 0, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1 };

        int favorableOutcomes = 0;
        int totalOutcomes = 36;

        for (int myRoll = 2; myRoll <= 12; myRoll++) {
            int wins = countWins(myRoll, enemyRolls);
            int losses = countLosses(myRoll, enemyRolls);

            if (wins > losses) {
                favorableOutcomes += ways[myRoll];
            }
        }

        return (double) favorableOutcomes / totalOutcomes;
    }
```

Comment (Sleet01) [reply megamek/src/megamek/client/bot/BotClient.java:1409]: This looks fine, I just didn't have time to spend on it myself.
I'll give it a whirl and see how things look!

**Comment by Sleet01** [comment]
@IllianiBird your code works great, although subjectively I might like it to be a little more aggressive.  We might tie it in to one of the bot sliders in the future, although it's sort of niche.

I did move your code into Princess, it seems like a better fit for the advanced bot.
I'll live the simpler code in BotClient.java so any subclass can override it as necessary, but we'll have a fallback.
