### PR TITLE
Log4j2: Fixing Issues Found During QA

### LINKED ISSUE #3326: Princess Logging Everything Regardless of Log4j Settings
This is a blocker for our next release, and I'll handle it in the near future.

### PR DESCRIPTION
**Pull request by Windchild292**
This fixes #3326, moves Log4j2's and SerialKiller's config to the mmconf file, ensures that stacktraces properly print for exceptions, and fixes exception stacktrace printout formatting.

### CODE REVIEW

File: megamek/src/megamek/client/bot/BotClient.java [hunk 1]
```diff
@@ -477,20 +477,20 @@ private synchronized void calculateMyTurn() {
...
-                    LogManager.getLogger().error(e.toString());
+                    LogManager.getLogger().error("", e);
                 }
             }
         }
     }
 
     /**
-     * Worker function for a single attempt to calculate the bot's turn.
+     * Worker function for a single attempt to calculate the boot's turn.
```
Comment (SJuliez) [inline megamek/src/megamek/client/bot/BotClient.java:493]: Surprising change, that :)

**Review by SJuliez — APPROVED** [review]
OK. just a typo

File: megamek/src/megamek/client/bot/BotClient.java (hunk 1 above)
Comment (Windchild292) [reply megamek/src/megamek/client/bot/BotClient.java]: Whoops
