### PR TITLE
Board Loading fix

### LINKED ISSUE #1898: Boards of sizes xx:yyy don't load
Tested with a few versions from current development to MM 0.45:

Boards with a two-digit x size and a three digit y size don't load. The issue is I think with board.indexFor which doesn't work for that situation. There is currently only one such board, SimonLandmine's Valley sample board (30x150).

The whole board loading seems a bit arcane, probably for historical reasons. The coords are unfortunately written in the board file without a separator or enough 000000 to separate them safely. The indexFor function tries to find the real coordinates from the coord string. The board saves the hex in an 1D-array based on those coordinates and retrieves hexes from this but assigns that hex Coords based on count variables (which could be different from the coord read from the file if the file has been altered).

### PR DESCRIPTION
**Pull request by SJuliez**
Changes board loading to allow loading xx * yyy boards (2 digit width and 3 digit height). This is done by ignoring the coordinates that are written in the board file and assuming the hexes appear in the order they are written by the board editor. I suppose it's not a big loss that manually changing coords in a board file won't have any effect anymore.

While at it, added in the Logger and moved a few streams to the try () statement.

Resolves #1898

### CODE REVIEW

**Review by sixlettervariables — COMMENTED** [review]
Does this break the `note` keyword?

File: megamek/src/megamek/common/Board.java [hunk 1]
```diff
@@ -956,16 +951,10 @@ public void load(final String filename) {
...
-            // tell the board to load!
+        try (InputStream is = new FileInputStream(filepath)) {
             load(is);
-            // okay, done!
-            is.close();
-        } catch (java.io.IOException ex) {
-            System.err.println("error opening file to load board!");
-            System.err.println(ex);
+        } catch (IOException ex) {
+            MegaMek.getLogger().error(this, "IO Error opening file to load board! " + ex);
```
Comment (Windchild292) [inline megamek/src/megamek/common/Board.java:957]: Curious why you decided to append the ex instead of have it as `MegaMek.getLogger().error(this, "IO Error opening file to load board!", ex);`

File: megamek/src/megamek/common/Board.java [hunk 2]
```diff
@@ -1093,10 +1075,10 @@ public void load(InputStream is, StringBuffer errBuff, boolean continueLoadOnErr
         if (isValid(nd, nw, nh, errBuff) && ((nw > 1) || (nh > 1) || (di == (nw * nh)))) {
             newData(nw, nh, nd, errBuff);
         } else if (continueLoadOnError && ((nw > 1) || (nh > 1) || (di == (nw * nh)))) {
-            System.err.println("Error reading board, data invalid.");
+            MegaMek.getLogger().error(this, "Invalid board data!");
             newData(nw, nh, nd, errBuff);
         } else if (errBuff == null){
-            System.err.println("Error reading board, data invalid.");
+            MegaMek.getLogger().error(this, "Invalid board data!");
```
Comment (Windchild292) [inline megamek/src/megamek/common/Board.java:1081]: Same error message twice in the same method without a way to tell them apart, which could cause issues in the future.

**Review by Windchild292 — COMMENTED** [review]
Two comments about logging.

File: megamek/src/megamek/common/Board.java (hunk 1 above)
Comment (SJuliez) [reply megamek/src/megamek/common/Board.java:957]: I just replicated what was done before without much thought. Didn't even notice that ex was the exception, not a message... I'll change it.

**Comment by SJuliez** [comment]
@sixlettervariables No, notes must bring their own coords and there's no interaction with the hex ordering. But I guess from the code that they won't work well on large boards either. But Im not sure what to make of them, apparently they're not called up anywhere currently and they don't seem to be the same as the notes I can place on the map in-game.

**Comment by HammerGS** [comment]
@SJuliez Comment for you on Slack regarding this one. Just seeing if it's ready for todays release? Thanks.

**Review by Windchild292 — APPROVED** [review]
