### PR TITLE
Issue #7083: Restrict C3 network effect based on map

### LINKED ISSUE #7083: [Issue] C3/C3i working for LAMs on space and low atmosphere maps
### Brief Description *

Aerospace fighters are prohibited from being constructed with C3 systems excepting NOVA CEWS and NOVA does not work except when interacting with ground units per IO (relevant rules thread discussion: https://bg.battletech.com/forums/index.php?topic=23135.0). Naval C3 is the only C3 system that should work on the space and low atmosphere map (and goes on to describe normal C3 as "ground-based C3 systems" in TO).

Currently LAMs are displaying an unexpected edge case where they are able to operate C3/C3i in space and low atmosphere maps and gain the benefits as if they were on the ground map because they can mount and utilize those items in BattleMech mode. 

### 3. Steps to Reproduce

1. Create custom LAM with C3 setup or C3i.
2. Deploy networked LAM force to space or low atmosphere map.
3. Observe C3 bonuses being conveyed during combat phase.

### Attach Files

_No response_

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don't affect gameplay and occur rarely.

### MegaMek Suite Version *

0.50.05

### Operating System *

Windows 11 10.0

### Java Version *

Adoptium 17.0.11

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by SJuliez**
Fixes #7083 
This PR
- moves C3 spotter code to its own helper class
- restricts NC3 to spaceborne units
- restricts other C3 to units on a ground map
- restricts C3 to units on the same map
- adds scenario language for C3 network definition and a test setup scenario

The restrictions only affect the on-map range effect, C3 networks can still be assigned regardless of where units are.

### CODE REVIEW

File: megamek/src/megamek/common/ComputeC3Spotter.java [hunk 1]
```diff
@@ -0,0 +1,179 @@
+/*
+ * Copyright (c) 2025 - The MegaMek Team. All Rights Reserved.
```
Comment (Scoppio) [inline megamek/src/megamek/common/ComputeC3Spotter.java]: This is an incomplete licensing header, the most current one is ~33 lines long

File: megamek/src/megamek/common/ComputeC3Spotter.java [hunk 2]
```diff
@@ -0,0 +1,179 @@
...
+        isNovaDefeated = start.hasNovaCEWS() && (spotterEndECM != null) && spotterEndECM.isNovaECM();
+        isC3Defeated = !(start.hasBoostedC3() || start.hasNovaCEWS())
+              && (spotterEndECM != null)
+              && spotterEndECM.isECM();
+        // If there's no ECM between spotter and end, we're done
+        if (!(isC3BDefeated || isNovaDefeated || isC3Defeated)) {
+            return true;
+        }
+
+        for (++startPosition; startPosition < network.size(); startPosition++) {
```
Comment (Scoppio) [inline megamek/src/megamek/common/ComputeC3Spotter.java:181]: Oh my... this looks like a very daunting code

File: megamek/src/megamek/common/scenario/C3ScenarioParser.java [hunk 3]
```diff
@@ -0,0 +1,89 @@
+/*
+ * Copyright (c) 2025 - The MegaMek Team. All Rights Reserved.
```
Comment (Scoppio) [inline megamek/src/megamek/common/scenario/C3ScenarioParser.java]: Wrong licensing header again

File: megamek/src/megamek/common/scenario/ScenarioLoaderException.java [hunk 4]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2022, 2024 - The MegaMek Team. All Rights Reserved.
+ * Copyright (c) 2025 - The MegaMek Team. All Rights Reserved.
```
Comment (Scoppio) [inline megamek/src/megamek/common/scenario/ScenarioLoaderException.java]: Put 2022-2025 here

**Review by Scoppio — CHANGES_REQUESTED** [review]

File: megamek/src/megamek/common/ComputeC3Spotter.java (hunk 2 above)
Comment (SJuliez) [reply megamek/src/megamek/common/ComputeC3Spotter.java:181]: Yes, I just moved that. I dont understand it either.

**Comment by SJuliez** [comment]
@Scoppio Updated the licenses in the new files and the copilot report was true as well.
