### PR TITLE
fix: Restore firing solution displaying after a torso twist

### LINKED ISSUE #7003: [Issue] [0.50.06-nightly-2025-05-07] Modifers overlay disappears during firing phase if torso/turret twist is performed
### Brief Description *

When performing a torso twist during the firing phase, the target modifier numbers disappear unless you select the unit again (such as clicking over to another unit and back to the first unit). 

### 3. Steps to Reproduce

Before twist:
Image

And after twist:
Image

### Attach Files

[ModifiersBug.sav.gz](https://github.com/user-attachments/files/20097301/ModifiersBug.sav.gz)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MegaMek Suite Version *

0.50.06-nightly-2025-05-07

### Operating System *

Windows 10

### Java Version *

Java Vendor: Eclipse Adoptium     Java Version: 17.0.6

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by Scoppio**
# What it does?

Makes the firing solution modifiers keep showing after a torso twist is made.

# Related issues
- Closes #7003

### CODE REVIEW

File: megamek/src/megamek/client/ui/swing/phaseDisplay/FiringDisplay.java [hunk 1]
```diff
@@ -1502,6 +1502,7 @@ protected void updateForNewAction() {
         }
         updateTarget();
         updateDonePanel();
+        refreshAll();
```
Comment (Scoppio) [inline megamek/src/megamek/client/ui/swing/phaseDisplay/FiringDisplay.java:1505]: So whenever an action that requires an update for new action, like torso twist or flip arms happen it will then call refresh all, who calls `update firing arc`, who calls `show firing solutions`, solving the problem.

**Review by HammerGS — APPROVED** [review]
