### PR TITLE
Issue #7359 - fix MMJB path finding

### LINKED ISSUE #7359: [Issue] 50.06 j.booster jumping null pointer exception
### Brief Description *

Using mech with j. booster, jumping into location behind mech causes uncaught null pointer exception. 

Image

### 3. Steps to Reproduce

_No response_

### Attach Files

[1.sav.gz](https://github.com/user-attachments/files/21700653/1.sav.gz)

[megamek.log](https://github.com/user-attachments/files/21700656/megamek.log)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MegaMek Suite Version *

0.50.06

### Operating System *

Linux

### Java Version *

17

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by SJuliez**
Fixes #7359
Fixes a problem with the direction calculation. Also fixes findSimplePathTo() going through hexes outside the board at the northern and southern edges of the board. 
Edit: Also changes the jump type selection dialog for units that have both MMJB and normal JJ to use two buttons instead of a combobox.

### CODE REVIEW

File: megamek/src/megamek/client/ui/panels/phaseDisplay/MovementDisplay.java [hunk 1]
```diff
@@ -1692,49 +1692,11 @@ private void currentMove(Coords dest, int boardId) {
...
-                    cmd.findSimplePathTo(dest,
-                          MoveStepType.LATERAL_RIGHT_BACKWARDS,
-                          src.direction(dest),
-                          currentEntity().getFacing());
-                    break;
-                case 5:
-                    cmd.findSimplePathTo(dest, MoveStepType.LATERAL_LEFT, src.direction(dest), currentEntity().getFacing());
-                    break;
-            }
+            MoveStepType moveStepType = MoveStepType.stepTypeForRelativeDirection(direction, currentEntity().getFacing());
```
Comment (Sleet01) [inline megamek/src/megamek/client/ui/panels/phaseDisplay/MovementDisplay.java:1697]: Nice!

**Review by Sleet01 — APPROVED** [review]
LGTM
