### PR TITLE
correct issues with BAP targeting to hit bonus

### LINKED ISSUE #5030: [HQ49.17] Displayed ToHit# and Tool-Tip in the Round Report are bugged when effected by active probe advanced rule.
The image illustrates what happens every time an attack is made while effected by the "TacOps Beagle Active Probes" advanced rule.  It seems part of the Tool-Tip is displayed in front of the ToHit# while the Tool-Tip itself is incomplete.

probe

Also, unrelated to this issue, is there a way to change the color of the ToHit# and ToHitRolls text?  I'm having a really hard time seeing them and I don't see a way to change them in the client settings.

### LINKED ISSUE #5072: [0.49.17] Modifier for BAP shooting through woods shows up in wrong places
### Environment
MegaMek version 0.49.17, packaged with MekHQ
Windows 11
Java 11.0.14.1

### Description
During the shooting phase, in the section of the unit window where accuracy modifiers are displayed, mechs firing through woods were given the "target behind woods and attacker has BAP" modifier despite none of the mechs having BAPs or pilots with SPAs. I am not yet sure whether this was actually affecting accuracy or if it was just a display bug.

That modifier also appeared, clearly erroneously, in the firing results list. Where it should just state a to-hit number it instead includes "behind woods and attacker has BAP)'>" before that number.

To reproduce, just load into the game and find a position where you'll be shooting through woods. (This should be easy.)

### Files
Screenshot 2024-01-21 172153
firingreportBAPbug
[megamek.log](https://github.com/MegaMek/megamek/files/14003576/megamek.log)
[BAPbugsave.sav.gz](https://github.com/MegaMek/megamek/files/14003577/BAPbugsave.sav.gz)
Player name: Evil Atlas

### PR DESCRIPTION
**Pull request by kuronekochomusuke**
- correct issues with BAP targeting always providing bonus to hit when shooting through woods
- correct issue with C3 member providing bonus to any target not just targets within the C3 member's BAP range
- show a updated message when receiving the bonus from a C3 member
- remove / from message that seems to cause display issues in the report
- show active probe range on unit tooltip

image
image

image

#5103
fixes #5030
fixes #5072

### CODE REVIEW

File: megamek/src/megamek/common/LosEffects.java [hunk 1]
```diff
@@ -237,6 +237,10 @@ public int getUltraWoods() {
         return ultraWoods;
     }
 
+    public boolean thruWoods() {
+        return (lightWoods > 0) || (heavyWoods > 0) || (ultraWoods > 0);
```
Comment (NickAragua) [inline megamek/src/megamek/common/LosEffects.java:241]: lol no jungle?

**Review by NickAragua — APPROVED** [review]
