### PR TITLE
Fix 6957 ba artillery no damage to onboard targets

### LINKED ISSUE #6957: [Issue] BA Artillery doing no damage
### Brief Description *

BA Tube Artillery does not cause any damage to units or buildings when the shell lands.

### 3. Steps to Reproduce

1. Add Centaur to force
2. Deploy
3. Make artillery attack against hex
4. Observe no damage from result of a hit

### Attach Files

Image
Image
Image

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MegaMek Suite Version *

0.50.05

### Operating System *

Windows 11 10.0

### Java Version *

Adoptium 17.0.11

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by Sleet01**
Fix for BA Tube Artillery dealing 0 damage, regardless of direct hits or blast.
Replaces basic `artilleryDamageArea()` call with the one that uses a DamageFalloff object and accounts for BA numbers.

Testing:
1. Ran manual repro with two Tube Artillery-equipped BA unit types and confirmed fix.
2. Ran all three projects' unit tests.

Close #6957

### CODE REVIEW

File: megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectFireHandler.java [hunk 1]
```diff
@@ -435,7 +455,7 @@ else if ((null != bestSpotter) && !(this instanceof ArtilleryWeaponDirectFireHan
         } else {
             handleArtilleryDriftMarker(targetPos, finalPos, aaa,
                     gameManager.artilleryDamageArea(finalPos, aaa.getCoords(), atype,
-                            subjectId, ae, isFlak, height, mineClear, vPhaseReport,
+                            subjectId, ae, df, isFlak, height, vPhaseReport,
```
Comment (Scoppio) [inline megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectFireHandler.java:458]: I know you are not "fixing"it, but update the variables to use our current naming convention, aka: `ae`, `df` and `atype`. Its minor, won't cause any problems and will help in the long run.

**Review by Scoppio — CHANGES_REQUESTED** [review]

**Comment by Scoppio** [comment]
> @Scoppio Sorry, what was the merge for?

I just clicked the `update branch`, sorry, I do that without thinking constantly.

File: megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectFireHandler.java [hunk 2]
```diff
@@ -1,15 +1,34 @@
 /*
- * MegaMek - Copyright (C) 2005 Ben Mazur (bmazur@sev.org)
```
[the remark this answers is not in the document]
Comment (rjhancock) [reply megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectFireHandler.java:2]: REQUIRED to keep this line. Period. We are NOT removing their copyright, we are adding ours. The ONLY change to this line is removing the `MegaMek - ` portion.

File: megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectFireHandler.java (hunk 1 above)
Comment (Sleet01) [reply megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectFireHandler.java:458]: I'll do a POC, but if renaming them exceeds 100 lines changed I'm going to abort.

Comment (rjhancock) [reply megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectFireHandler.java:458]: Doing a variable rename, even if 100+ LOC, is still worth it long term. But this is your call as you're the one doing the work.

File: megamek/docs/history.txt [hunk 3]
```diff
@@ -13,6 +13,7 @@ MEGAMEK VERSION HISTORY:
 + Fix #6954: Fixes NPE and missing portrait/deployment in Mek Customization dialog
 + Fix #6955: fuel tanks take zero damage from AE
 + Fix #6956: Correct fluff art for HHWs
++ Fix #6957: BA Artillery doing no damage
```
Comment (Scoppio) [inline megamek/docs/history.txt:16]: Ok, we need to have a standard for this, because most of the entries we have follow the standard:

`[type:Fix|PR] #[number:PR NUMBER]: [text:title/message]`

And in this message would have the ID of the issue it is fixing.

Now that we are making PRs with history, this makes it a little harder to follow the standard as we dont have the code prior to making the Pull request, meaning we have to open the pull request, take note of the PR number, add a new commit with the history change with that PR number.

What you did here (and other people are also doing) is taking the ID of the issue, not the ID of the PR, and adding in the PR Code.

I dont know what to do other than raise this as a potential problem in the engineering channel.

I'm marking @rjhancock here just so he know where comes from my worry.

**Review by Scoppio — APPROVED** [review]

File: megamek/docs/history.txt (hunk 3 above)
Comment (psikomonkie) [reply megamek/docs/history.txt:16]: I actually prefer it this way - If it's fixing an issue, let's reference the issue. That fix will reference this PR, and any other PRs that were needed to implement it.
