### PR TITLE
fix npe when displaying summary/TRO for gun emplacements

### LINKED ISSUE #2022: Watchdog ECM Bunker - Empty TRO card
### Environment
- MegaMek 0.47.7
- Java:
openjdk version "11.0.7.2" 2020-04-26
OpenJDK Runtime Environment (Alibaba Dragonwell) (build 11.0.7.2+9)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell) (build 11.0.7.2+9, mixed mode)
(I don't think that Java was a matter; all other things were OK).
- OS: Linux (Ubuntu 20.04 Focal Fossa)

### Description
So I've selected the Watchdog ECM Bunker, and TRO card was empty, like on the picture.

### Files
Provided screenshot
bug

Now the question is - is it intended or not?

### PR DESCRIPTION
**Pull request by NickAragua**
This fixes #2022 in two ways:

1) isClanArmor no longer throws an exception if passed an invalid location, returning false instead
2) Created new TRO templates for gun emplacements which omit armor and structure information and selectively use those for the TRO display.

### CODE REVIEW

File: megamek/src/megamek/common/templates/VehicleTROView.java [hunk 1]
```diff
@@ -44,6 +45,13 @@ public VehicleTROView(Tank tank) {
 
     @Override
     protected String getTemplateFileName(boolean html) {
+        if(tank instanceof GunEmplacement) {
```
Comment (Windchild292) [inline megamek/src/megamek/common/templates/VehicleTROView.java:48]:
```suggestion
        if (tank instanceof GunEmplacement) {
```

File: megamek/src/megamek/common/templates/VehicleTROView.java [hunk 2]
```diff
@@ -44,6 +45,13 @@ public VehicleTROView(Tank tank) {
...
+            if (html) {
+                return "gunemplacement.ftlh";
+            }
+            return "gunemplacement.ftl";
```
Comment (Windchild292) [inline megamek/src/megamek/common/templates/VehicleTROView.java:52]:
```suggestion
            if (html) {
                return "gunemplacement.ftlh";
            } else {
                return "gunemplacement.ftl";
            }
```

Comment (Windchild292) [reply megamek/src/megamek/common/templates/VehicleTROView.java:52]: I find it easier to read if the return is in an else in statements like this, but this is very much a suggestion.
