### PR TITLE
Fix Lobby Multiunit Config

### LINKED ISSUE #3590: 0.49.7 Bot sometimes ignores set deployment turns.
### Environment
I'm using MekHQ 0.49.7, running on Windows, and using Java 11.0.14.1.

### Description

I'm running a pursuit battle generated by and launched through MekHQ. I adjusted the deployment settings in the lobby so I deploy at start of game and the bot's units deploy on turn 3, but when I start the game, the bot's units all ignore the deployment setting and deploy at start of game as well. I've repeatedly closed the game without saving, restarted it from MekHQ, and tried to set things properly and try again, but the issue recurs. I've tried setting it so a single enemy unit (a helicopter) deploys at start of game and everything else deploys on turn 3, just in case the bot's units were getting pushed forward until at least _something_ would be deployed, but everything deployed at start of game anyway.

I also tried saving my game in the lobby so I could restart from there rather than having to set everything again, but when I loaded the save, all the enemy units in the lobby were set to deploy at start of game. (This issue may recur with the save I sent you.)

image
image
image

### Files
[bugged_deployment.zip](https://github.com/MegaMek/megamek/files/8532774/bugged_deployment.zip)
Player name is Iron Titans. I _think_ I provided all relevant files, but if anything's missing, let me know and I'll add it!

### LINKED ISSUE #5575: [0.49.19.1] Issues modifying deployment time/location for stratcon generated forces (offboard arty, ASF)
### Environment
Megamek/MekHQ Version: 0.49.19.1 milestone
OS: Windows 10
Java Version: Adoptium 11.0.23.9

### Description
When launching a Dropship Assault mission generated by MekHQ via Stratcon with an offboard artillery and asf opfor modifiers, changes to deployment time for the ASF and offboard location for the artillery do not stick. The ASF want to deploy SouthEast at game start, and I can set them in lobby to deploy later in the lobby, but once the match is launched they always will deploy at game start instead of the dictated deployment round. I can however alter their deployment location without issue. The artillery I similarly can tell to deploy offboard anywhere in the lobby, but once the match is launched they will always deploy offboard East at 34 distance. Possibly other deployment time/locations do not stick, but I haven't tested other permutations.

### Files
Here is the mekhq campaign file with the mission pending.
[DragonclawsBuggedDropshipMission.cpnx.gz](https://github.com/user-attachments/files/15855661/DragonclawsBuggedDropshipMission.cpnx.gz)
Except for a few custom mech files (none of which are partaking in this mission), and my various saves and saved presets, my mekhq folder is otherwise stock.

### PR DESCRIPTION
**Pull request by SJuliez**
Fixes #3590 
Fixes #5575

Updates from multi-unit config were not accepted by the server as they came from the wrong client connection. This PR unifies the code for sending updates after unit configuration for single unit and multi unit config so that it also works for locally owned bot units.

### CODE REVIEW

File: megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java [hunk 1]
```diff
@@ -307,77 +302,39 @@ public void customizeMechs(Collection<Entity> entities) {
...
-        ArrayList<Entity> c3members = new ArrayList<>();
-        Iterator<Entity> playerUnits = c.getGame().getPlayerEntities(c.getLocalPlayer(), false).iterator();
-        while (playerUnits.hasNext()) {
-            Entity unit = playerUnits.next();
-            if (!entity.equals(unit) && entity.onSameC3NetworkAs(unit)) {
-                c3members.add(unit);
-            }
-        }
+
+        String ownerName = entity.getOwner().getName();
```
Comment (kuronekochomusuke) [inline megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java:325]: should this block be an isEditable function?

Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java]: it's needs to get the client as well. But still true, I unified this also.

**Review by NickAragua — APPROVED** [review]
