### PR TITLE
Fix Radical Heat Sink target number not reducing on inactive turns

### LINKED ISSUE #3087: [0.49.2] Radical Heat Sink target number not reducing on inactive turns
### Environment
0.49.2

### Description
Radical Heat Sink TNs are not decreasing on one turn of the system being turned off. TN is only reduced on consecutive turns of being turned off. This is a bug - one turn of the RHS being turned off should reduce the TN by 1.

Observed behaviour

Case A: single inactive turn
turn 0: RHS on, TN 2+
turn 1: RHS on, TN 3+
turn 2: RHS off, no roll
turn 3: RHS on, TN 3+
turn 4: RHS on, TN 5+
turn 5: RHS off, no roll
turn 6: RHS on, TN 5+

Case B: consecutive inactive turns
turn 0: RHS on, TN 2+
turn 1: RHS on, TN 3+
turn 2: RHS off, no roll
turn 3: RHS off, no roll
turn 4: RHS on, TN 2+
turn 5: RHS on, TN 3+

Expected behaviour (Field Manual 3145, page 247):

"For each turn the unit does not use its Radical Heat Sinks, the failure chance reduced by one level."

turn 0: RHS on, TN 2+
turn 1: RHS on, TN 3+
turn 2: RHS off, no roll
turn 3: RHS on, TN 2+
turn 4: RHS on, TN 3+
turn 5: RHS off, no roll
turn 6: RHS on, TN 2+

### Files
[rhstest.sav.gz](https://github.com/MegaMek/megamek/files/6989400/rhstest.sav.gz)

### PR DESCRIPTION
**Pull request by HammerGS**
Fixes #3087

  ---
  Summary

  Radical Heat Sinks (RHS) failure target number was not decreasing when the system was inactive for a turn between active turns. This PR fixes the tracking logic and adds UI improvements for better RHS management.

  ---
  Root Cause

  The code was checking hasActivatedRadicalHS() (equipment mode) at newRound() time to determine if RHS was used. However, the equipment mode persists from the previous turn until reset, so the code couldn't distinguish between "RHS is active but not yet processed" and "RHS was used in the previous turn."

  Fix

  Following the same pattern as MASC/Supercharger, added explicit tracking flags:
  - usedRHSLastTurn - Set in HeatResolver when RHS is actually processed
  - rhsWentUp - Tracks if consecutive uses counter increased (for proper double-decrement when transitioning from using to not using)

  ---
  Changes

  Bug Fix (Entity.java, HeatResolver.java):
  - Added usedRHSLastTurn and rhsWentUp tracking fields
  - Updated newRound() to properly decrement consecutive uses based on actual usage
  - Double-decrement applies when transitioning from "using" to "not using" RHS

  UI: RHS Toggle Button (FiringDisplay.java, messages.properties):
  - Added "RHS is: Off" / "RHS is: On" toggle button in firing phase
  - Button only appears for units with working (undamaged) Radical Heat Sinks
  - Sends mode change to server for proper synchronization

  UI: Heat Phase Status Messages (HeatResolver.java, report-messages.properties):
  - When RHS is used: Shows stress level and next activation TN
    - RHS stress level: 2 (next activation requires 7+, skipping a turn reduces stress)
  - When RHS is skipped but has stress: Shows settling status with predictions
    - RHS settling: stress 2 -> 0 (next activation requires 3+)

  ---
  Files Changed

  | File                       | Changes                                                                                                         |
  |----------------------------|-----------------------------------------------------------------------------------------------------------------|
  | Entity.java                | Added usedRHSLastTurn, rhsWentUp fields and methods; activateRadicalHS(), hasWorkingRadicalHS(), hasRHSWentUp() |
  | HeatResolver.java          | Set tracking flag when RHS processed; added stress status reports                                               |
  | FiringDisplay.java         | Added FIRE_RHS command, toggle button, and server sync                                                          |
  | messages.properties        | Added FiringDisplay.fireRHS, FiringDisplay.fireRHSOn                                                            |
  | report-messages.properties | Added reports 5544 (stress level) and 5546 (settling)                                                           |

  ---
  Testing

  Verified scenarios:
  - Use RHS 2 turns → Skip 1 turn → Use again: TN correctly drops from 5+ to 3+
  - Use RHS 3 turns → Skip 2 turns → Use again: TN correctly drops from 7+ to 3+
  - Settling message correctly predicts double-decrement (stress 2 → 0) and next TN
  - RHS toggle button properly syncs with server

### CODE REVIEW

File: megamek/resources/megamek/common/report-messages.properties [hunk 1]
```diff
@@ -800,6 +800,8 @@
 5541=Radical heat sinks failure check, needs <data>+, rolls: <data>, <msg:5542,5543>
 5542=<span class='warning'>failure!</span>
 5543=<span class='success'>success!</span>
+5544=RHS stress level: <data> (next activation requires <data>+, skipping a turn reduces stress)
+5546=RHS settling: stress <data> -> <data> (next activation requires <data>+)
```
[the remark this answers is not in the document]
Comment (HammerGS) [reply megamek/resources/megamek/common/report-messages.properties]: Resolved https://github.com/MegaMek/megamek/pull/7808/commits/1ef17f5090463db2f87489356a766e3064e9364d

File: megamek/src/megamek/server/totalWarfare/HeatResolver.java [hunk 2]
```diff
@@ -117,6 +120,7 @@ void resolveHeat() {
                 rhsReports.add(report);
 
                 Roll diceRoll = Compute.rollD6(2);
+                // Increment consecutive uses for this turn's use, then look up target number
```
[the remark this answers is not in the document]
Comment (HammerGS) [reply megamek/src/megamek/server/totalWarfare/HeatResolver.java]: Resolved https://github.com/MegaMek/megamek/pull/7808/commits/1ef17f5090463db2f87489356a766e3064e9364d

File: megamek/src/megamek/client/ui/panels/phaseDisplay/FiringDisplay.java [hunk 3]
```diff
@@ -2049,6 +2056,47 @@ private void updateActivateSPA() {
...
+    private void doToggleRHS() {
+        Entity entity = currentEntity();
+        if (entity == null) {
+            return;
+        }
+
+        // Find the RHS equipment
+        for (MiscMounted mounted : entity.getMisc()) {
+            if (mounted.getType().hasFlag(MiscType.F_RADICAL_HEATSINK)) {
+                // Toggle: mode 0 = Off, mode 1 = On
```
Comment (IllianiBird) [inline megamek/src/megamek/client/ui/panels/phaseDisplay/FiringDisplay.java]: Is it possible converting this from storing magic ints to use boolean, instead?

File: megamek/src/megamek/common/units/Entity.java [hunk 4]
```diff
@@ -15142,6 +15168,20 @@ public void deactivateRadicalHS() {
         }
     }
 
+    public void activateRadicalHS() {
+        for (MiscMounted m : getMisc()) {
```
Comment (IllianiBird) [inline megamek/src/megamek/common/units/Entity.java]: Abbreviated variable name, you know the drill

File: megamek/src/megamek/common/units/Entity.java [hunk 5]
```diff
@@ -15142,6 +15168,20 @@ public void deactivateRadicalHS() {
...
+            if (m.getType().hasFlag(MiscType.F_RADICAL_HEATSINK)) {
+                m.setMode("On");
```
Comment (IllianiBird) [inline megamek/src/megamek/common/units/Entity.java]: user facing hardcoded String

**Review by IllianiBird — COMMENTED** [review]
A question and some minor, optional feedback.

File: megamek/src/megamek/common/units/Entity.java (hunk 5 above)
Comment (HammerGS) [reply megamek/src/megamek/common/units/Entity.java]: Resolved https://github.com/MegaMek/megamek/pull/7808/commits/74b4fce4b2e4874ba87e30113e6e839af0ca5ca0

File: megamek/src/megamek/common/units/Entity.java (hunk 4 above)
Comment (HammerGS) [reply megamek/src/megamek/common/units/Entity.java]: Resolved https://github.com/MegaMek/megamek/pull/7808/commits/74b4fce4b2e4874ba87e30113e6e839af0ca5ca0

File: megamek/src/megamek/client/ui/panels/phaseDisplay/FiringDisplay.java (hunk 3 above)
Comment (HammerGS) [reply megamek/src/megamek/client/ui/panels/phaseDisplay/FiringDisplay.java]: Resolved https://github.com/MegaMek/megamek/pull/7808/commits/74b4fce4b2e4874ba87e30113e6e839af0ca5ca0
