### PR TITLE
Fix for #6682, #6683, also terrain blast over-applying

### LINKED ISSUE #6682: [0.50.04-SNAPSHOT] Unit avoided being damaged by AOE blast from Long Tom Cannon despite being adjacent to target hex
### Brief Description *

I'm not sure exactly why, but the Legionnaire in the screenshot below did NOT get damaged by the blast area, but the Hercules in a different adjacent hex took the expected splash damage.

Attached is the save file and gamelog showing the resolution of the firing phase where I observed the behavior

Image

### 3. Steps to Reproduce

1. Load "LTCblastBug.sav"
2. Use the Demolisher II to fire both LTC cannons at hex 0927, which should hit the Legionnaire in the rear and the Hercules in the face with 10 AOE splash damage each
3. Observe that only the Hercules took damage

### Attach Files

[LTC Blast Bug.zip](https://github.com/user-attachments/files/19213923/LTC.Blast.Bug.zip)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MegaMek Suite Version *

0.50.04-SNAPSHOT     Build Date: 2025-03-11T03:28:21.989996995

### Operating System *

Windows 10

### Java Version *

Java Vendor: Eclipse Adoptium     Java Version: 17.0.6

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### LINKED ISSUE #6683: [0.50.04-SNAPSHOT] Long Tom Cannon Fuel-Air Munition ammo applying damage as standard LTC shell
### Brief Description *

While reporting another bug, I noticed that the FAM fired (30/20/10/5 damage) applied only the standard LTC shell damage (20/10).

You can see in the attached gamelog that it DID fire the FAM shells, because it did the FAM ignition check on a nearby hex which caught fire, but only did 10 damage to a unit in the hex adjacent to the targeted hex (which was hit directly and did not scatter) instead of the expected 20

### 3. Steps to Reproduce

1. Load LTCblastBug.sav
2. Fire LTC FAM shell at hex 0927
3. Observe incorrect damage being applied
4. (repeat and try again if the unit misses the target)

### Attach Files

[LTC Blast Bug.zip](https://github.com/user-attachments/files/19213981/LTC.Blast.Bug.zip)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MegaMek Suite Version *

0.50.04-SNAPSHOT     Build Date: 2025-03-11T03:28:21.989996995

### Operating System *

Windows 10

### Java Version *

Java Vendor: Eclipse Adoptium     Java Version: 17.0.6

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by Sleet01**
Fixes four issues with FAE munitions using the updated blast shaping code:
1. FAE explosion handling was not taking the underlying hex's level into account when creating the blast
2. FAE cannon damage was not getting set correctly
3. FAE munitions' blast damage profile was not correctly represented in the target display, using incorrect damage and falloff values.
4. Blasts were doing extra damage to the terrain factor of each hex due to ignoring the blast height anyways

This fix adds FAE artillery damage profiles to the target display, correctly generates FAE munition blast damage and blast shapes, and correctly passes the target hex elevation to the blast handling code.
Additionally, the new 3D blast shapes will only damage terrain factor for hexes whose surfaces intersect with the blast shape; hexes above or below the blast will not be affected (just like units).
Buildings will still take damage for every level that is within the blast shape, however.

NOTE: we do not have blast shadowing (buildings and hexes blocking/partially absorbing blast damage) implemented yet.  This is a non-trivial feature and will not be ready in time for the next release.
So players will see blasts going "through" intervening terrain or buildings in some cases.

Close #6682 
Close #6683

### CODE REVIEW

File: megamek/src/megamek/server/totalwarfare/TWGameManager.java [hunk 1]
```diff
@@ -31789,7 +31790,7 @@ public Vector<Integer> artilleryDamageHex(Coords coords,
             if (!flak) {
                 // Report that damage applied to terrain, if there's TF to damage
                 Hex h = game.getBoard().getHex(coords);
-                if ((h != null) && h.hasTerrainFactor()) {
+                if ((h != null) && h.hasTerrainFactor() && h.hasTerrainFactor() && (altitude == h.getLevel())) {
```
Comment (HoneySkull) [inline megamek/src/megamek/server/totalwarfare/TWGameManager.java:31793]: `h.hasTerrainFactor()` is in this conditional twice.

Comment (Sleet01) [reply megamek/src/megamek/server/totalwarfare/TWGameManager.java:31793]: Okay, I know I pulled that out, one sec...

Comment (Sleet01) [reply megamek/src/megamek/server/totalwarfare/TWGameManager.java:31793]: Must have undone the previous fix at some point.  Should be fixed now.

**Review by HoneySkull — APPROVED** [review]
