### PR TITLE
Issue #7382 - Fixes Submarines can move when at the seafloor

### LINKED ISSUE #7382: [Issue] Submarines can move when at the seafloor
### Brief Description *

TW p.56 states that submarines at a depth equal to the water depth cannot move, they are resting at the bottom. MM does not seem to implement this.

### 3. Steps to Reproduce

Start a game with the archipelago map, add a Neptune, deploy and go down to -2 in a depth 2 water hex. The sub can still move normally.

### Attach Files

_No response_

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don't affect gameplay and occur rarely.

### MegaMek Suite Version *

50.06

### Operating System *

Win10

### Java Version *

doesnt matter

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by HammerGS**
Summary for fixes #7382

  Part 1: Submarine Movement Type Assignment
  - ✅ Added submarine movement type checks to WALK and RUN sections
  - ✅ Submarines now display depth indicators ({-1}, {-2}) in UI
  - ✅ Foundation established for depth-based restrictions
  - ✅ Tested and validated (Tests 1-3)

  Part 2: Seafloor Movement Restriction
  - ✅ Added seafloor immobilization check (TW p.56)
  - ✅ Blocks horizontal movement at seafloor
  - ✅ Blocks facing changes at seafloor
  - ✅ Allows vertical ascent from seafloor
  - ✅ Works across all water depths (depth-1, depth-2, depth-3+)
  - ✅ Tested and validated (Tests 4-8)

  Bug Fixed During Testing:
  - Initial implementation checked destination instead of origin
  - Fixed to use prev.getPosition() and prev.getElevation()
  - Now correctly prevents movement from seafloor

  Files Changed

  1. MoveStep.java (lines 2041-2042, 2085-2086, 2112-2119)
    - Part 1: Submarine movement type assignment
    - Part 2: Seafloor movement restriction check
  2. 7382-submarine-seafloor-movement.md
    - Complete issue documentation with implementation details, test results, and notes

### CODE REVIEW

**Comment by HammerGS** [comment]
AI Notes

[7382-submarine-seafloor-movement.md](https://github.com/user-attachments/files/23535086/7382-submarine-seafloor-movement.md)

File: megamek/src/megamek/common/moves/MoveStep.java [hunk 1]
```diff
@@ -2080,6 +2082,8 @@ private void compileIllegal(final Game game, final Entity entity, final MoveStep
                 if ((entity.getMovementMode() == EntityMovementMode.VTOL ||
                       entity.getMovementMode() == EntityMovementMode.WIGE) && getClearance() > 0) {
                     movementType = EntityMovementType.MOVE_VTOL_RUN;
+                } else if ((entity.getMovementMode() == EntityMovementMode.SUBMARINE) && getElevation() < 0) {
```
Comment (IllianiBird) [inline megamek/src/megamek/common/moves/MoveStep.java:2085]: Should this be elevation or depth?

Comment (HammerGS) [reply megamek/src/megamek/common/moves/MoveStep.java:2085]: My understanding (not Claude's understanding) is that MegaMek uses negative elevation values to represent underwater depth

Comment (Sleet01) [reply megamek/src/megamek/common/moves/MoveStep.java:2085]: Yeah, it looks like for _entities_ we use a negative elevation for "depth".
But we also have a positive Depth (used by mines, hex _floors_, and basements), and we even compare the absolute value of the one to the value of the other sometimes -_-;

Comment (IllianiBird) [reply megamek/src/megamek/common/moves/MoveStep.java:2085]: Awesome, just wanted to verify
