### PR TITLE
handle additional cases with null position

### LINKED ISSUE #4548: [49.14 - SNAPSHOT] Post Physical Attack Report IllegalStateException
### Environment
MegaMek 0.49-14 - SNAPSHOT (17-06-2023), lightly modded, modded files and mechfiles in attached zip
Origin Project: MekHQ
Platform: Windows 10 10.0 (amd64)
Java Vendor: Eclipse Adoptium
Java Version: 11.0.19

### Description
Either when or after resolving the physical attack report on Round 5 the game gives an IllegalStateException error and will not proceed further in the game, though the game itself does not appear to crash, client settings and other non-game related functions appear to work.

Have run battle twice and both times the Scorpion battlemech will report "Crew Dead" despite A.) The Pilot being alive and B.) "Crew dead" not being a condition that a 'mech can be in.

Issue appears to be related to the Scorpion Battlemech, in games in which the Scorpion dies quickly the bug does not occur.

### Files
[battletech bug report.zip](https://github.com/MegaMek/megamek/files/11816452/battletech.bug.report.zip)

### PR DESCRIPTION
**Pull request by kuronekochomusuke**
- handle additional cases with null position
- handle other errors within getEntityTipReport 

fixes #4548

### CODE REVIEW

File: megamek/src/megamek/server/GameManager.java [hunk 1]
```diff
@@ -1796,7 +1796,14 @@ private void entityStatusReport() {
...
             r.addDesc(e);
-            r.add(UnitToolTip.getEntityTipReport(e).toString());
+            String etr = "";
+            try {
+                etr = UnitToolTip.getEntityTipReport(e).toString();
+            } catch (Exception ex) {
+                LogManager.getLogger().error("", ex);
+                etr = ex.getMessage();
+            }
+            r.add(etr);
```
Comment (NickAragua) [inline megamek/src/megamek/server/GameManager.java:1806]: Generally speaking, we don't stick exception messages into the round reports; logging it is sufficient.

**Review by NickAragua — CHANGES_REQUESTED** [review]

**Review by NickAragua — APPROVED** [review]
