### PR TITLE
Fixes #7885. AMS does not engage twice

### LINKED ISSUE #7885: [Issue] Playtest 3 AMS change not working
### Brief Description *

In playtest 3 gear:

Image

Image

MM does not use AMS to engage two missile flights with the Playtest option 3 changes selected. 

(The old unofficial option to allow AMS unlimited fire per turn does currently still work)

Image

### 3. Steps to Reproduce

1. Start a lobby and add a bot
2. Add LRM and/or SRM units to one side and a unit with AMS to the other
3. Observe firing phase resolution

### Attach Files

[amsplaytest1.sav.gz](https://github.com/user-attachments/files/24652149/amsplaytest1.sav.gz)
Name: test

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MegaMek Suite Version *

50.11

### Operating System *

Windows 11

### Java Version *

17.0.15

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by TenkawaBC**
This is a prospective fix and needs testing.

This was the only other use of MULTI_AMS, and the logic has to be different, but I've got the new logic in now. Needs more testing, but I wanted to open the PR so that it is tracked for now. will run more tests this weekend and confirm the fix is good.

### CODE REVIEW

File: megamek/src/megamek/common/compute/Compute.java [hunk 1]
```diff
@@ -3398,6 +3398,27 @@ public static WeaponAttackAction getHighestExpectedDamage(Game g,
...
+     */
+    public static WeaponAttackAction getSecondHighestExpectedDamage(Game g,
+          List<WeaponAttackAction> vAttacks, boolean assumeHit) {
+        WeaponAttackAction waaHighest = null;
+        WeaponAttackAction waaSecondHighest = null;
+        
+        // Copy the list to a new list
+        List<WeaponAttackAction> attacksClone = new ArrayList<>(vAttacks);
+        // Find the highest damage
+        waaHighest = getHighestExpectedDamage(g, attacksClone, true);
```
Comment (Sleet01) [inline megamek/src/megamek/common/compute/Compute.java]: replace `true` in these two calls to getHighestExpectedDamage with `assumeHit` parameter being passed in.

Comment (TenkawaBC) [reply megamek/src/megamek/common/compute/Compute.java]: Changed in c2f5d55

**Comment by TenkawaBC** [comment]
Reviewing code further, this appears to only apply to auto-assigned AMS.

Manually assigned AMS does not seem to respect multi-AMS or playtest. I'm reviewing further to see if that needs to change

File: megamek/src/megamek/client/ui/clientGUI/ClientGUI.java [hunk 2]
```diff
@@ -2948,7 +2949,7 @@ public void gameClientFeedbackRequest(GameCFREvent gameCFREvent) {
                         return;
                     }
                     ArrayList<String> amsOptions = new ArrayList<>();
-                    amsOptions.add(Messages.getString("NONE"));
+                    //amsOptions.add(Messages.getString("NONE"));
```
Comment (Sleet01) [inline megamek/src/megamek/client/ui/clientGUI/ClientGUI.java]: Do we actually no longer need this option?  What if the player decides (for whatever reason) not to use their AMS shots at all?

Comment (TenkawaBC) [reply megamek/src/megamek/client/ui/clientGUI/ClientGUI.java]: It makes it more difficult if we keep it, and clicking cancel on the dialog box is effectively the same thing.

If we keep it, then we need to iterate the selection list and reduce every index by 1 (the space that None takes up).

I can add it back in, but I need to introduce logic to reduce the values in the returned int[] array.

File: megamek/src/megamek/client/ui/clientGUI/AmsAssignGUI.java [hunk 3]
```diff
@@ -0,0 +1,77 @@
...
+
+package megamek.client.ui.clientGUI;
+import javax.swing.*;
+
+/**
+ * @author James Magnan
+ * Implements a custom list selection model to assign AMS with varying numbers of selections
+ */
+
+public class AmsAssignGUI extends DefaultListSelectionModel {
```
[the remark this answers is not in the document]
Comment (TenkawaBC) [reply megamek/src/megamek/client/ui/clientGUI/AmsAssignGUI.java:42]: Added in c643f66

File: megamek/src/megamek/client/ui/clientGUI/ClientGUI.java (hunk 2 above)
Comment (TenkawaBC) [reply megamek/src/megamek/client/ui/clientGUI/ClientGUI.java]: In c643f66 I added it back in, and compensated for it before sending the indexes back. Then also check for -1 on the receiving end to strip it out if someone selected NONE and other entries at the same time.

**Comment by TenkawaBC** [comment]
After adjustments, this is ready for testing. Will need to test the following:

1) auto-AMS assignment against player
2) auto-AMS assignment against bot
3) manual AMS assignment against player
4) manual AMS assignment against bot

All 4 need to be tested with a) No playtest options, b) Playtest 3 enabled
3 and 4 need to be tested with Multi-AMS enabled

**Review by Sleet01 — APPROVED** [review]
LGTM.

**Comment by TenkawaBC** [comment]
Test 3 (manual AMS selection) with playtest3 enabled was a success (Longbow 2xLRM20, 2xLRM5 against Komodo 2xAMS)

**Comment by TenkawaBC** [comment]
All tests completed and passed. Princess can engage with AMS automatically properly, with playtest and without. and manually and automatically assigning AMS.
