### PR TITLE
Map Editor Fixes - Wave 1

### LINKED ISSUE #1641: Map Editor 47.3 - Building selection issue
With the mouse pointer over the 'Buildings' icon, and using CTRL+scrollwheel to select the Building Type, there appears to be odd behaviour at the top and bottom end of the range ...

If you CTRL+ScrollDown beyond 'Light Building', you end up with the following in the detail window (I don't know what it's actually called) ...

_Building CF 40
Building Elevation 1
Woods (unknown)_

... and a starfield in the preview hex.

And if you CTRL+ScrollUp beyond 'Hardened Building', you get the following ...

_Building CF 40
Building Elevation 1
Wall_

... and, again, a starfield in the preview hex.

### LINKED ISSUE #1643: Map Editor 47.3 - Exits Button Tooltip
The Exit Selection button appears to retain the tooltip giving the button name, rather than the button function.

MapEditor-ExitsButton

### PR DESCRIPTION
**Pull request by Windchild292**
This fixes #1641, fixes #1643, fixes a bug found when investigating #1642 relating to building names, fixes a few bugs with exits relating to enforcing the standard bounds and having the check mark selected, and implements some efficiency changes made while investigating #1635.

### CODE REVIEW

File: megamek/src/megamek/client/ui/swing/BoardEditor.java [hunk 1]
```diff
@@ -1752,21 +1741,39 @@ public void actionPerformed(ActionEvent ae) {
...
-            cheTerrExitSpecified.setSelected(true);
-            ed.setExits(texTerrExits.getNumber());
+            int exitsVal = texTerrExits.getNumber();
+            ed.setExits(exitsVal);
             ed.setVisible(true);
-            texTerrExits.setNumber(ed.getExits());
+            exitsVal = ed.getExits();
+            texTerrExits.setNumber(exitsVal);
+            if (exitsVal != 0) {
+                cheTerrExitSpecified.setSelected(true);
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/BoardEditor.java]: How about cheTerrExitSpecified.setSelected(exitsVal != 0)

Comment (NickAragua) [reply megamek/src/megamek/client/ui/swing/BoardEditor.java]: and on line 1772

Comment (Windchild292) [reply megamek/src/megamek/client/ui/swing/BoardEditor.java]: Fixed
