### PR TITLE
Fix zero-armor aero units incorrectly showing as damaged (Fixes #7925)

### LINKED ISSUE #7925: [Issue] Unit images for fixed wing SVs incorrectly showing as damaged
### Brief Description *

When they are created with 0 armor, fixed wing support vehicles (like the Boomerang Spotter Plane) are having their images in all 3 programs show as damaged in some (but not all) places.  They are also listed as "HEAVY DMG" in the unit display.

### 3. Steps to Reproduce

_No response_

### Attach Files

Image
(note that the image on the board is damaged but not the image on the right

Image
(note that the image in the icon selector is not damaged, but the image in the select unit window is)

Image
(all 3 damaged and unit showing as "Heavy Damage")

Image
(image and unit both showing damage)

[logs.zip](https://github.com/user-attachments/files/24842141/logs.zip)

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don't affect gameplay and occur rarely.

### MegaMek Suite Version *

0.50.11

### Operating System *

Windows 10

### Java Version *

Java Vendor: Eclipse Adoptium     Java Version: 17.0.17

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by HammerGS**
1. Fix in Aero.java: Modified the three damage level methods to check for ARMOR_NA before comparing armor percentages:
  - isDmgHeavy() - line 2562
  - isDmgModerate() - line 2596
  - isDmgLight() - line 2629

  This matches the existing pattern in Tank.java which already handles this correctly.

  2. New test class DamageLevelTest.java: Created comprehensive tests covering:
  - AeroSpaceFighter with zero armor → should be DMG_NONE
  - FixedWingSupport with zero armor → should be DMG_NONE
  - Tank with zero armor → should be DMG_NONE
  - ConvFighter with zero armor → should be DMG_NONE
  - Verification that actual damage still correctly reports damage levels

  Files changed:
  1. megamek/src/megamek/common/units/Aero.java - Bug fix
  2. megamek/unittests/megamek/common/units/DamageLevelTest.java - New test class
  
  Fixes #7925

### CODE REVIEW

**Comment by psikomonkie** [comment]
>     2. New test class DamageLevelTest.java: Created comprehensive tests covering:
> 
> 
>     * AeroSpaceFighter with zero armor → should be DMG_NONE
> 
>     * FixedWingSupport with zero armor → should be DMG_NONE
> 
>     * Tank with zero armor → should be DMG_NONE
> 
>     * ConvFighter with zero armor → should be DMG_NONE
> 
>     * Verification that actual damage still correctly reports damage levels
> 
> 
> Files changed:
> 
>     1. megamek/src/megamek/common/units/Aero.java - Bug fix
> 
>     2. megamek/unittests/megamek/common/units/DamageLevelTest.java - New test class


I only see one file, DamageLevelTest.java doesn't look to be included.

File: megamek/unittests/megamek/common/units/DamageLevelTest.java [hunk 1]
```diff
@@ -0,0 +1,225 @@
+/*
+ * Copyright (C) 2025-2026 The MegaMek Team. All Rights Reserved.
```
Comment (psikomonkie) [inline megamek/unittests/megamek/common/units/DamageLevelTest.java]: I think this should just be 2026.

**Review by psikomonkie — APPROVED** [review]
Nice! One comment on the copyright header for the unit test but code-wise this is good.

File: megamek/unittests/megamek/common/units/DamageLevelTest.java (hunk 1 above)
Comment (rjhancock) [reply megamek/unittests/megamek/common/units/DamageLevelTest.java]: First year is the year the file was created/first touched by MegaMek. Second is current year modifications are being done.

Comment (rjhancock) [reply megamek/unittests/megamek/common/units/DamageLevelTest.java]: Only exception to this is if the code was extracted from another class and put into its own file. Then the year is from the time the original file was added.
