### PR TITLE
Issue Megameklab#1818: Correct "armor_tech" to "armor_tech_level" when applicable

### LINKED ISSUE #6858: [Issue] Glitch when loading Dropships from files
### Brief Description *

MegaMekLab version 0.50.04

When loading a dropship from a .blk file, MegaMekLab adds 1,5 tons of armor regardless of how the file was saved.

### 3. Steps to Reproduce

1) Create a dropship and save to file
2) Reload that same file
3) you should see the armor setting being incorrect

### Attach Files

_No response_

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MegaMek Suite Version *

0.50.04

### Operating System *

Windows 10

### Java Version *

Java Version 8  Update 441     (Build 1.8.0_441-b07)

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by psikomonkie**
Fixes MegaMek/megameklab#1818
Fixes #6858 

Recently, `armor_tech` was updated to `armor_tech_level` in some places. Notably, it was updated in the method used for saving. This was breaking units that were re-saved in the current version. This completes the change and updates the correct occurrences of `armor_tech` to `armor_tech_level`. Battle Armor still uses `armor_tech`, it's handled separately for some reason. IDK, that's not what I'm here for. 

@Scoppio made this real nifty test that's disabled by default, `BulkUnitFileTest`. I was able to use this to verify how many units had issues loading, saving, and loading again both before my changes and after. 346 units were failing this test before these changes. 157 are failing after these changes. There are no new units failing, the 157 failing now were also failing before these changes.

We should update the existing files so they have `armor_tech_level` instead of `armor_tech`, but this is able to handle a file that has `armor_tech` so this won't break master before the units are updated.

### CODE REVIEW

File: megamek/src/megamek/common/loaders/BLKAeroSpaceFighterFile.java [hunk 1]
```diff
@@ -161,9 +161,6 @@ public Entity getEntity() throws EntityLoadingException {
         // This is not working right for arrays for some reason
         a.autoSetThresh();
 
-        // add Transporters prior to equipment to simplify F_CARGO bay assignment
-        addTransports(a);
-
```
Comment (psikomonkie) [inline megamek/src/megamek/common/loaders/BLKAeroSpaceFighterFile.java:166]: This is intentional - it was another issue reported by @NexiraElimus on Discord at the same time as MegaMek/megameklab#1818. Aerospace fighters were having transports added twice. There is other code that handles this better, so this was removed.

**Review by Scoppio — APPROVED** [review]
Good job
