### PR TITLE
Bot command fix

### LINKED ISSUE #2883: [princess] Bot does not respond to in-game commands
The PrincessNotes doc says you can issue commands to bots during the game, such as {name}: Flee. While the bot responds appropriately ("Princess: Run Away!"), it doesn't flee at all. It seems the other commands don't work either, but it's harder to test. Maybe the behaviour got changed but not that part?

Also the PrincessNotes.txt lists the wrong command for "Show Behaviour".

### PR DESCRIPTION
**Pull request by NickAragua**
Fixes #2883; Also, allows the bot to have its destination edge be set to the nearest edge.

### CODE REVIEW

File: megamek/src/megamek/client/bot/ChatProcessor.java [hunk 1]
```diff
@@ -299,9 +300,29 @@ void additionalPrincessCommands(GamePlayerChatEvent chatEvent, Princess princess
 
         // If instructed to, flee.
         if (command.toLowerCase().startsWith(ChatCommands.FLEE.getAbbreviation())) {
-            msg = "Received flee order!";
+            if (arguments == null || arguments.length == 0) {
```
Comment (Windchild292) [inline megamek/src/megamek/client/bot/ChatProcessor.java:303]: brackets

File: megamek/src/megamek/client/bot/ChatProcessor.java [hunk 2]
```diff
@@ -299,9 +300,29 @@ void additionalPrincessCommands(GamePlayerChatEvent chatEvent, Princess princess
...
+                princess.sendChat(msg);
+                return;
+            }
+            
+            CardinalEdge edge = null;
+            
+            try {
+                int edgeIndex = Integer.parseInt(arguments[0]);
+                edge = CardinalEdge.getCardinalEdge(edgeIndex);
+            } catch (Exception e) { }
```
Comment (Windchild292) [inline megamek/src/megamek/client/bot/ChatProcessor.java:314]:
```suggestion
            } catch (Exception ignored) { }
```

Comment (Windchild292) [reply megamek/src/megamek/client/bot/ChatProcessor.java:314]: Prevents IDE warnings on my end

File: megamek/src/megamek/common/pathfinder/BoardClusterTracker.java [hunk 3]
```diff
@@ -164,8 +164,10 @@ public boolean coordinatesShareCluster(Coords first, Coords second, int firstEle
      */
     public Set<Coords> getDestinationCoords(Entity entity, CardinalEdge edge, boolean terrainReduction) {
         CardinalEdge actualEdge = edge;
-        if(edge == CardinalEdge.NEAREST_OR_NONE) {
+        if(edge == CardinalEdge.NEAREST) {
```
Comment (Windchild292) [inline megamek/src/megamek/common/pathfinder/BoardClusterTracker.java:167]:
```suggestion
        if (edge == CardinalEdge.NEAREST) {
```

File: megamek/src/megamek/client/bot/princess/Princess.java [hunk 4]
```diff
@@ -1844,7 +1844,7 @@ protected void processChat(final GamePlayerChatEvent ge) {
     CardinalEdge getHomeEdge(Entity entity) {
         // if I am crippled and using forced withdrawal rules, my home edge is the "retreat" edge        
         if(entity.isCrippled(true) && getBehaviorSettings().isForcedWithdrawal()) {
-            if(getBehaviorSettings().getRetreatEdge() == CardinalEdge.NEAREST_OR_NONE) {
+            if(getBehaviorSettings().getRetreatEdge() == CardinalEdge.NEAREST) {
```
Comment (Windchild292) [inline megamek/src/megamek/client/bot/princess/Princess.java:1847]:
```suggestion
            if (getBehaviorSettings().getRetreatEdge() == CardinalEdge.NEAREST) {
```

File: megamek/src/megamek/client/bot/princess/CardinalEdge.java [hunk 5]
```diff
@@ -49,35 +61,57 @@ public static CardinalEdge getCardinalEdge(int index) {
...
+        // attempt enum parse
+        try {
+            return valueOf(source);
+        } catch (Exception e) {}
+        
+        // attempt "legacy" parse
+        try {
+            int edgeIndex = Integer.parseInt(source);
+            return getCardinalEdge(edgeIndex);
+        } catch (Exception e) {}
```
Comment (Windchild292) [inline megamek/src/megamek/client/bot/princess/CardinalEdge.java:77]:
```suggestion
        } catch (Exception ignored) {}
```

File: megamek/src/megamek/client/bot/princess/CardinalEdge.java [hunk 6]
```diff
@@ -49,35 +61,57 @@ public static CardinalEdge getCardinalEdge(int index) {
...
     }
     
+    /**
+     * Given a string, attempt to figure out if it corresponds to a cardinal edge
+     */
+    public static CardinalEdge parseFromString(String source) {
+        // attempt enum parse
+        try {
+            return valueOf(source);
+        } catch (Exception e) {}
```
Comment (Windchild292) [inline megamek/src/megamek/client/bot/princess/CardinalEdge.java:71]:
```suggestion
        } catch (Exception ignored) {}
```

**Review by Windchild292 — APPROVED** [review]
