### PR TITLE
Board editor fixes (#2233,#1762)

### LINKED ISSUE #1762: 0.47.4 Map Editor - CTRL+scroll change to Bridge class
When doing 'CTRL+Scroll' over the bridge icon to change the Bridge Class value, if you've used 'ALT+click' to select an existing bridge, you lose the 'Exits' value for the existing bridge.

### LINKED ISSUE #2233: Map Editor - new terrain picks up 'exits' setting from the 'Terrain Settings' window
MM 0.47.10 and earlier
Windows 10
Java 8

When a new terrain type is selected by clicking on the WYSIWYG buttons at the top of the right-hand menu, it inherits any 'exits' value that is currently defined in the 'Terrain Settings' fields (e.g. from previously configuring a Bridge), even if exits are irrelevant to the terrain type (e.g. the Light Woods in the screenshot below).

This seems to happen with most terrain types (e.g. Roads, Woods, Mud, Swamp, Pavement, Water), except for Buildings, Fuel Tanks, and, ironically given this example, Bridges.

The simplest solution might be to, when a new terrain type is selected via a WYSIWYG button, the 'exits' checkbox is unchecked (except when ALT-clicking Buildings to enforce single-hex construction).

image

### PR DESCRIPTION
**Pull request by SJuliez**
Resolves #2233 
Resolves #1762 
... and various small issues.

### CODE REVIEW

File: megamek/src/megamek/client/ui/swing/BoardEditor.java [hunk 1]
```diff
@@ -1622,47 +1554,69 @@ private void boardSaveImage(boolean ignoreUnits) {
...
+        if (curBoardFile == null || saveAs) {
+            if (!chooseSaveBoardFile()) {
+                return false;
+            }
+        }
+        butSourceFile.setEnabled(true);
+
+        // write the board
+        try {
+            OutputStream os = new FileOutputStream(curBoardFile);
```
Comment (sixlettervariables) [inline megamek/src/megamek/client/ui/swing/BoardEditor.java:1578]: This should be moved into the try statement itself (`try (...)`) so if board.save throws, `os` will be cleaned up.

**Review by sixlettervariables — COMMENTED** [review]
Small improvement requested otherwise looks good!

File: megamek/src/megamek/client/ui/swing/BoardEditor.java (hunk 1 above)
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/BoardEditor.java]: Done.

**Review by Windchild292 — APPROVED** [review]
