### PR TITLE
fix NPE with support tank infantry weapons

### LINKED ISSUE #1797: Princessbot freezes w/ Infantry vs Apocalypse World Rover (ClassCastException)
I was just messing around with a Mad Max-esque scenario with technicals, jeeps, and motorized infantry and apparently Princessbot didn't like it.

### Environment
MekHQ's MegaMek
MegaMek v0.46.1 ...
	Compiled on Mon Mar 09 15:11:45 PDT 2020
	Today is Fri Mar 27 18:16:15 PDT 2020
	Java vendor Oracle Corporation
	Java version 1.8.0_241
	Platform Windows 10 10.0 (x86)
	Total memory available to MegaMek: 1,013,632 kB

### Description
Princessbot is consistently freezing around Round 2-6 when using a Apocalypse World Rover (player) against an Infantry Mechanized Hover Platoon (bot). Unable to skip.

**Steps to reproduce:**
1. Load attached save game
2. Advance turn
3. Game should hang on Princessbot's turn. (If it doesn't, try advancing a few more turns. In all my tests it consistently freezes, just not on the same turn.)

I've run several battles with infantry on different maps and gotten the same results.

### Files
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/4396554/mekhqlog.txt)
[Marauders_b1_hanging_r6.sav.gz](https://github.com/MegaMek/megamek/files/4396556/Marauders_b1_hanging_r6.sav.gz)

Player Name: Marauders

### PR DESCRIPTION
**Pull request by NickAragua**
Fixes #1797, which would happen when evaluating potential attacks against infantry by support vehicles mounting infantry weapons.

### CODE REVIEW

File: megamek/src/megamek/client/bot/princess/InfantryFireControl.java [hunk 1]
```diff
@@ -115,8 +115,10 @@ public double getMaxDamageAtRange(final MovePath shooterPath, final MovePath tar
 
             // case 1
             if (weaponType.hasFlag(WeaponType.F_INFANTRY)) {
+                int infantryCount = shooter.isConventionalInfantry() ?
+                        ((Infantry) shooter).getInternal(Infantry.LOC_INFANTRY) : 1;
```
Comment (Windchild292) [inline megamek/src/megamek/client/bot/princess/InfantryFireControl.java]: Cast to Infantry isn't needed here.

Comment (NickAragua) [reply megamek/src/megamek/client/bot/princess/InfantryFireControl.java:119]: It's used by the bot to calculate incoming and outgoing damage when evaluating a path being considered by an infantry unit. So it was trying to evaluate a move path for a foot platoon and checking how much damage an "apocalypse world rover" would do to the foot platoon. That particular tank has a weapon with an infantry flag, but was not an infantry unit. 

I'm pretty sure this will lead to incorrect behavior for battle armor, so I'm going to take another look at it.

Comment (NickAragua) [reply megamek/src/megamek/client/bot/princess/InfantryFireControl.java]: There, that should do it.

File: megamek/src/megamek/client/bot/princess/InfantryFireControl.java [hunk 2]
```diff
@@ -91,7 +92,7 @@ public double getMaxDamageAtRange(final MovePath shooterPath, final MovePath tar
                 && target.hasETypeFlag(Entity.ETYPE_INFANTRY) && ((Infantry) target).isMechanized();
 
         // cycle through my weapons
-        for (final Mounted weapon : shooter.getWeaponList()) {
+        for (final Mounted weapon : shooter.getWeaponList()) {
```
Comment (Windchild292) [inline megamek/src/megamek/client/bot/princess/InfantryFireControl.java:95]:
```suggestion
        for (final Mounted weapon : shooter.getWeaponList()) {
```

File: megamek/src/megamek/client/bot/princess/InfantryFireControl.java [hunk 3]
```diff
@@ -115,8 +116,16 @@ public double getMaxDamageAtRange(final MovePath shooterPath, final MovePath tar
 
             // case 1
             if (weaponType.hasFlag(WeaponType.F_INFANTRY)) {
+                int infantryCount = 1;
+                
+                if(shooter.isConventionalInfantry()) {
```
Comment (Windchild292) [inline megamek/src/megamek/client/bot/princess/InfantryFireControl.java:121]:
```suggestion
                if (shooter.isConventionalInfantry()) {
```

File: megamek/src/megamek/client/bot/princess/InfantryFireControl.java [hunk 4]
```diff
@@ -115,8 +116,16 @@ public double getMaxDamageAtRange(final MovePath shooterPath, final MovePath tar
...
+                    infantryCount = shooter.getInternal(Infantry.LOC_INFANTRY);
+                } else if(shooter instanceof BattleArmor){
```
Comment (Windchild292) [inline megamek/src/megamek/client/bot/princess/InfantryFireControl.java:123]:
```suggestion
                } else if (shooter instanceof BattleArmor) {
```
