### PR TITLE
fix path enumerator NPEs for destroyed entities

### LINKED ISSUE #1807: 0.46.1 Princess Freeze Calculating Pathing
0.46.1 MHQ Mergamek
Win10
 Java 1.8 I think?

### Description
Playing base defence as defender. AI is controlling Base Civilians, and CapCon Defence forces, and also FWL Attackers, Attackers #2 and Reinforcements (RAT tables don't seem to play ball with providing turrets to CapCon Base Turrets team).

Below bug occurred twice (two play attempts), usually during CapCon movement. Appears to be occurring with a hover SRM APC starting over water. Not sure what's happening, but CPU use is at 0% (occasionally 0.2%).
[megameklog.txt](https://github.com/MegaMek/megamek/files/4409240/megameklog.txt)
[borked.sav.gz](https://github.com/MegaMek/megamek/files/4409243/borked.sav.gz)

-----------------------------------------------------------------------------------
13:47:24,705 ERROR [megamek.common.pathfinder.LongestPathFinder] {Princess-precognition (Base Civilian Units)} 
Entity invalid. ID 15
java.lang.IllegalArgumentException: Entity invalid. ID 15
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:483)
	at megamek.common.MovePath.addStep(MovePath.java:483)
	at megamek.common.MovePath.addStep(MovePath.java:257)
	at megamek.common.MovePath.addStep(MovePath.java:169)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:354)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:319)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:331)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:268)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)
	at java.lang.Thread.run(Unknown Source)

13:50:52,350 ERROR [megamek.common.pathfinder.LongestPathFinder] {Princess-precognition (Capellan Confederation)} 
Entity invalid. ID 15
java.lang.IllegalArgumentException: Entity invalid. ID 15
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:483)
	at megamek.common.MovePath.addStep(MovePath.java:483)
	at megamek.common.MovePath.addStep(MovePath.java:257)
	at megamek.common.MovePath.addStep(MovePath.java:169)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:354)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:319)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:331)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:268)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)
	at java.lang.Thread.run(Unknown Source)

13:52:15,633 ERROR [megamek.common.pathfinder.LongestPathFinder] {Princess-precognition (Base Civilian Units)} 
Entity invalid. ID 15
java.lang.IllegalArgumentException: Entity invalid. ID 15
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:483)
	at megamek.common.MovePath.addStep(MovePath.java:483)
	at megamek.common.MovePath.addStep(MovePath.java:257)
	at megamek.common.MovePath.addStep(MovePath.java:169)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:354)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:319)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:331)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:268)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)
	at java.lang.Thread.run(Unknown Source)

13:56:27,062 ERROR [megamek.common.pathfinder.LongestPathFinder] {Princess-precognition (Base Civilian Units)} 
Entity invalid. ID 15
java.lang.IllegalArgumentException: Entity invalid. ID 15
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:483)
	at megamek.common.MovePath.addStep(MovePath.java:483)
	at megamek.common.MovePath.addStep(MovePath.java:257)
	at megamek.common.MovePath.addStep(MovePath.java:169)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:354)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:319)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:331)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:268)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)
	at java.lang.Thread.run(Unknown Source)

13:56:50,734 ERROR [megamek.common.pathfinder.LongestPathFinder] {Princess-precognition (Capellan Confederation)} 
Entity invalid. ID 15
java.lang.IllegalArgumentException: Entity invalid. ID 15
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:483)
	at megamek.common.MovePath.addStep(MovePath.java:483)
	at megamek.common.MovePath.addStep(MovePath.java:257)
	at megamek.common.MovePath.addStep(MovePath.java:169)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:354)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:319)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:331)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:268)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)
	at java.lang.Thread.run(Unknown Source)

13:58:25,947 ERROR [megamek.common.pathfinder.LongestPathFinder] {Princess-precognition (Free Worlds League Force #2)} 
Entity invalid. ID 15
java.lang.IllegalArgumentException: Entity invalid. ID 15
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:483)
	at megamek.common.MovePath.addStep(MovePath.java:483)
	at megamek.common.MovePath.addStep(MovePath.java:257)
	at megamek.common.MovePath.addStep(MovePath.java:169)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:351)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:319)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:331)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:268)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)
	at java.lang.Thread.run(Unknown Source)

### PR DESCRIPTION
**Pull request by NickAragua**
Occasionally, a unit will get destroyed while the path enumerator is still calculating movement possibilities for it. Since that happens in a separate thread, the underlying game object gets updated and a call to "getEntity(id)" returns null, but the entity object having its moves calculated is still present, leading to NPEs.

This *should* fix that problem (it's difficult to reproduce since it goes away if you kick the bot and have it reconnect) by double checking that the entity is actually in the game before starting path calculations. It also cleans up orphaned entries for that entity in the various lookup tables.

Fixes #1807

### CODE REVIEW

File: megamek/src/megamek/client/bot/princess/PathEnumerator.java [hunk 1]
```diff
@@ -179,6 +179,16 @@ public void recalculateMovesFor(final Entity mover) {
             // Clear out any already calculated paths.
             getUnitPaths().remove(mover.getId());
             getLongRangePaths().remove(mover.getId());
+            
+            // if the entity does not exist in the game for any reason, let's cut out safely
+            // otherwise, we'll run into problems calculating paths
+            if(getGame().getEntity(mover.getId()) == null) {
```
Comment (Windchild292) [inline megamek/src/megamek/client/bot/princess/PathEnumerator.java:185]:
```suggestion
            if (getGame().getEntity(mover.getId()) == null) {
```
