### PR TITLE
Fix MG Arrays not linking for ProtoMeks #7325

### LINKED ISSUE #7325: MG Arrays do not work for Protomechs
### Brief Description *

As stated in the title. MG Arrays do not link the MGs in protomechs.

### 3. Steps to Reproduce

1. Make Protomech
2. Add MGs then Array
3. Test... no MGs linked.

### Attach Files

Image

Image

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MegaMeklab Suite Version *

0.50.06

### Operating System *

Windows 10

### Java Version *

    Java Vendor: Eclipse Adoptium     Java Version: 17.0.15

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by HammerGS**
Fixes #7325

  Root cause: Two issues prevented MG Arrays from working on ProtoMeks:
  1. BLKProtoMekFile.getEntity() never called linkMGAs() after loading equipment
  2. linkMGAs() relied on critical slots to find MGs, but ProtoMeks don't populate critical slots when equipment is added via Entity.addEquipment()

  Fix:
  1. Added call to MekFileParser.linkMGAs(t) in BLKProtoMekFile.getEntity() after loading equipment, matching the pattern used in other loaders
  2. Added fallback in linkMGAs() to search the weapon list directly when no MGs are found via critical slots. This handles entities like ProtoMeks that store equipment differently.

  The fix also applies to MegaMekLab automatically since equipment placement
  calls postLoadInit() which calls linkMGAs().

  ---
  Files modified:
  - megamek/src/megamek/common/loaders/BLKProtoMekFile.java - Added MekFileParser.linkMGAs(t) call
  - megamek/src/megamek/common/loaders/MekFileParser.java - Added fallback in linkMGAs() for entities without critical slots
  
  
image

### CODE REVIEW

File: megamek/src/megamek/common/loaders/BLKProtoMekFile.java [hunk 1]
```diff
@@ -144,6 +144,10 @@ public Entity getEntity() throws EntityLoadingException {
             loadEquipment(t, abbreviations[loop], loop);
         }
         t.setArmorTonnage(t.getArmorWeight());
+
+        // Link MG Arrays to their MGs
+        MekFileParser.linkMGAs(t);
```
[the remark this answers is not in the document]
Comment (HammerGS) [reply megamek/src/megamek/common/loaders/BLKProtoMekFile.java]: Addressed

File: megamek/src/megamek/common/loaders/MekFileParser.java [hunk 2]
```diff
@@ -887,6 +887,25 @@ public static void linkMGAs(Entity entity) {
...
                 }
+
+                // Fallback for entities that don't use critical slots (e.g., ProtoMeks)
+                // If no MGs were linked via critical slots, search the weapon list directly
+                if (mga.getBayWeapons().isEmpty()) {
+                    for (WeaponMounted weapon : entity.getWeaponList()) {
+                        if (weapon.getLocation() == mga.getLocation() &&
+                              weapon.getType().hasFlag(WeaponType.F_MG) &&
+                              mga.getType().getRackSize() == weapon.getType().getRackSize()) {
+                            int eqNum = entity.getEquipmentNum(weapon);
```
Comment (IllianiBird) [inline megamek/src/megamek/common/loaders/MekFileParser.java:898]: We shouldn't be using abbreviated variable names any more. It unnecessarily reduces code clarity. When updating code that has pre-existing single letter or abbreviated variable names we should be updating them.

File: megamek/unittests/megamek/common/MekFileParserTest.java [hunk 3]
```diff
@@ -85,4 +88,129 @@ void loadMGAsFromContiguousBlocks() throws LocationFullException {
...
+     * Tests for MG Array linking on ProtoMeks, which don't use critical slots. These tests verify the fallback path in
+     * linkMGAs() that searches the weapon list directly. Uses LOC_BODY which has no weapon limit for ProtoMeks.
+     */
+    @Nested
+    class ProtoMekMGALinkingTests {
+
+        @Test
+        void protoMekMGALinksMGsInSameLocation() throws LocationFullException {
+            ProtoMek proto = new ProtoMek();
+            WeaponMounted mga = (WeaponMounted) proto.addEquipment(
```
Comment (IllianiBird) [inline megamek/unittests/megamek/common/MekFileParserTest.java]: It's unclear what `mga` means in this, eventually I worked it out to be `machineGunArray`, but this is an illustration of why abbreviated variable names are bad. I shouldn't have to fathom what the programmers' intent is, the variable name should always say what the variable is.

Comment (HammerGS) [reply megamek/unittests/megamek/common/MekFileParserTest.java]: I think the mga reference is existing in the code.

Comment (IllianiBird) [reply megamek/unittests/megamek/common/MekFileParserTest.java]: So, here's the thing: we should always be looking for ways to improve code quality in the codebase. We have a _lot_ of abbreviated variable (and sometimes method) names in the codebase. They do nothing but make the code harder to follow for no gain. What we should be doing is not replicating them, but replacing them. For example, here, this is a new variable name so shouldn't be abbreviated. However the AI is duplicating existing code practices - code practices we're actively trying to phase out.

If you recall, this exact thing was one of my concerns with the introduction of AI-authored code. Which, in this case (among others), is not a good thing and actually undermines our efforts to modernize the codebase.

Comment (HammerGS) [reply megamek/unittests/megamek/common/MekFileParserTest.java]: Done

**Review by IllianiBird — APPROVED** [review]
