### PR TITLE
Fix LAM Aerospace Strafing Bug

### LINKED ISSUE #4410: 49.12 Firing Phase VTOL Strafe Issue
### Environment
MegaMek battle within an MHQ AtB campaign
Windows
Version 11 Adoptium

### Description
Issue - Triggering VTOL Strafe attack popped up error. Error led to a weird glitched out view on all vehicle's weapon tabs as well as failing to complete the Strafing attack with more than 1 laser.
Step by Step of events
I had already complete the move phase for the turn. I had one of my VTOLs fly over in a strafing attack. During the firing phase I handed out all my firing orders to my units. When I got to the Warrior VTOL, I was able to fire its first weapon [Which thats a first, more on that in a bit] but when I clicked the fire button for the second time an error popped up. Unfortunately being the first time I have actually came across an issue and thought to upload it, I clicked through a few things and so I forgot the proper code on the pop up nor do I have a save for it [as I allowed the turn to move on]. 
To expand upon the bracket I mentioned earlier. Before when I have used VTOL strafes, I have not been able to actually click the fire button. I could still right click their path and click the fire option there and it would work. I believe that is because my VTOL's movement ended at the end of the strafe path, and since a unit can't target the space its in it was having issues. This time my VTOL's movement ended 1 space past the strafe route. Not sure if this may be having an impact on the issue or not.
I have also noticed there are two options that add in VTOL strafing, and at the time I did have them both on [not even realizing I did].

### Files
[megamek.log](https://github.com/MegaMek/megamek/files/11415971/megamek.log)
Capture

[This is my first issue post. Please feel free to poke me if I messed something up]

### LINKED ISSUE #5232: ASFs can use plasma rifles for strafing runs
### Environment
MekHQ/MegaMek 0.49.18
Java Vendor: Eclipse Adoptium
Java Version: 21
Win11 23H2

### Description
Aerospace Fighters with plasma rifles can use them for strafing runs. Presumably since they are classified as 'energy' weapons. But being ammo-dependent I was told to open a bug report.

To reproduce, create an ASF with plasma rifles and perform a strafing run as normal.

image

### Files
[plasmastrafe.sav.gz](https://github.com/MegaMek/megamek/files/14532174/plasmastrafe.sav.gz)

Team name is "The Wrecking Belles"

### LINKED ISSUE #6708: [Issue] Land Air Mech in Aerospace mode cannot use all energy weapons to strafe and null error thrown
### Brief Description *

20:28:27,854 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:151) - Starting MegaMek v0.50.03
    Build Date: 2025-02-02T13:40:31.382772700
    Today: 2025-03-15
    Origin Project: MegaMekLab
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.12
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_AU
    Total memory available to MegaMek: 4 GB
    MM Code Revision: 4ed278cd097a5222b12c6e888f8b202e5ccc4ff4
    MML Code Revision: d743ae29375a67401eaa4eb254ec09c037fe572b
    MHQ Code Revision: 41f1f82ce502ea4ca82bcc50d28bb3ecf6a82ac4

Have noticed this issue in earlier versions of MegaMek.

When LAM is in aerospace mode and strafing if more than 1 energy weapon is selected a NULL error is thrown.

Image

### 3. Steps to Reproduce

1. open new megamek game
2. add a LAM with more than one energy weapon
3. configure LAM to fighter mode
4. start game (altitude 3)
5. fly over combatants 
6. on shooting phase select more than one energy weapon (null error thrown on selection of second energy weapon)

### Attach Files

_No response_

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### MegaMek Suite Version *

0.50.03

### Operating System *

Windows 11 24H2 build: 26100.3476

### Java Version *

17.0.12

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by HammerGS**
Fixes #6708
  Fixes #4410
  Fixes #5232

  ---
  Summary

  LAMs in fighter/aerospace mode could not perform strafing attacks. Two issues were identified and fixed. Additionally, based on code review feedback, two related strafing bugs were also addressed.

  Issues Fixed:
  - #6708 - LAM strafing hex selection and NPE
  - #4410 - VTOL strafing NPE on second weapon (same root cause as #6708 Issue 2)
  - #5232 - Plasma rifles incorrectly allowed for strafing

  ---
  Root Cause

  Issue 1: Hex Selection (LAMs)

  The strafe button enablement correctly uses entity.isAero() which returns true for LAMs in fighter mode. However, getStrafingCoords() used instanceof Aero which returns false for LAMs since LandAirMek extends BipedMek, not Aero.

  Issue 2: NPE on Second Weapon (LAMs and VTOLs)

  During strafing, target is intentionally null because strafing attacks hexes via strafingCoords, not a single target. The secondary target arc-checking code at lines 1199-1225 didn't account for strafing mode and attempted to use the null target, causing an NPE when firing the second weapon.

  This affects both LAM strafing and VTOL strafing since both use the same fire() method with isStrafing = true and target = null.

  Issue 3: LAM Arc Rules

  The forced primary target arc check applies Mek-style front/side/rear arc rules. LAMs in fighter mode use aero arc rules (nose/wings/aft), so this check should be skipped for them.

  Issue 4: Plasma Weapons Strafing

  The strafing weapon validation in ComputeToHitIsImpossible allowed weapons with F_PLASMA flag, but plasma weapons use ammo. Per BattleTech rules, only energy weapons that don't use ammo can strafe (to avoid ammo explosion risk from ground fire). This was inconsistent with the button enablement check in FiringDisplay.equippedForStrafing() which correctly excluded ammo-using weapons.

  ---
  Changes

  FiringDisplay.java

  1. getStrafingCoords() (line 2375): Changed instanceof Aero to isAero() to properly detect LAMs in fighter mode. Added null safety check.
  2. fire() (lines 1199-1204): Added !isStrafing check to skip secondary target arc validation during strafing. Also fixed operator precedence issue with parentheses. Additionally, excluded LAMs in aero mode from the Mek arc check using instanceof Mek mek && !mek.isAero().

  ComputeToHitIsImpossible.java

  3. isDirectFireEnergy check (lines 930-935): Removed F_PLASMA and F_PLASMA_MFUK from allowed strafing weapon flags. Plasma weapons use ammo and should not be allowed for strafing.

### CODE REVIEW

File: megamek/src/megamek/client/ui/panels/phaseDisplay/FiringDisplay.java [hunk 1]
```diff
@@ -1196,9 +1196,11 @@ public void fire() {
         // check if we now shoot at a target in the front arc and previously
         // shot a target in side/rear arc that then was primary target
         // if so, ask and tell the user that to-hits will change
-        if (!game.getOptions().booleanOption(OptionsConstants.ADVANCED_COMBAT_NO_FORCED_PRIMARY_TARGETS)
-              && (currentEntity() instanceof Mek) || (currentEntity() instanceof Tank)
-              || (currentEntity() instanceof ProtoMek)) {
+        // Skip this check during strafing since strafing attacks multiple hexes, not a single target
+        if (!isStrafing
+              && !game.getOptions().booleanOption(OptionsConstants.ADVANCED_COMBAT_NO_FORCED_PRIMARY_TARGETS)
+              && ((currentEntity() instanceof Mek) || (currentEntity() instanceof Tank)
```
Comment (psikomonkie) [inline megamek/src/megamek/client/ui/panels/phaseDisplay/FiringDisplay.java]: This is from LAMs, right? Should we update the `(currentEntity() instanceof Mek)` check to account for that, something like `(currentEntity() instanceof Mek mek && !mek.isAero())`? Or do we still want to apply this sometimes when the Mek is in Aero mode?

File: megamek/src/megamek/client/ui/panels/phaseDisplay/FiringDisplay.java [hunk 2]
```diff
@@ -2370,7 +2372,7 @@ public Targetable getTarget() {
     private List<Coords> getStrafingCoords(Coords center) {
         Entity strafingAero = currentEntity();
 
-        if (!(strafingAero instanceof Aero)) {
+        if ((strafingAero == null) || !strafingAero.isAero()) {
```
Comment (psikomonkie) [inline megamek/src/megamek/client/ui/panels/phaseDisplay/FiringDisplay.java:2376]: VTOLs can strafe too, right? I see there are some times where a VTOL entity will call this method, do you know if those also currently broken & something we could fix here?

Comment (HammerGS) [reply megamek/src/megamek/client/ui/panels/phaseDisplay/FiringDisplay.java:2376]: I'll have a look

Comment (HammerGS) [reply megamek/src/megamek/client/ui/panels/phaseDisplay/FiringDisplay.java:2376]: VTOLs use a completely different strafing system. My research shows:

  | Aspect      | Aero Strafing   | VTOL Strafing                 |
  |-------------|-----------------|-------------------------------|
  | Phase       | Firing phase    | Movement phase                |
  | Handler     | FiringDisplay   | MovementDisplay               |
  | Check       | entity.isAero() | instanceof VTOL               |
  | Game Option | N/A             | ADVANCED_COMBAT_VTOL_STRAFING |
  | Location    | Line 2037-2048  | Line 2934                     |

  The getStrafingCoords() method is only called for aero-style strafing. VTOLs have their own strafe button in MovementDisplay that uses instanceof VTOL correctly.

  Answer to psikomonkie: VTOLs are not affected by this fix - they use a separate strafing system in the movement phase.

File: megamek/src/megamek/client/ui/panels/phaseDisplay/FiringDisplay.java (hunk 1 above)
Comment (HammerGS) [reply megamek/src/megamek/client/ui/panels/phaseDisplay/FiringDisplay.java]: Feedback 1: instanceof Mek check (Line 1202)

  What this code does: Implements the "forced primary targets" rule. When you first shoot at a target in your side/rear arc, it becomes your primary target. If you then try to shoot at a target in your front arc, the game warns you that to-hit modifiers will change.

  psikomonkie's point is valid. LAMs in fighter mode:
  - Still match instanceof Mek (since LandAirMek extends BipedMek)
  - But they use aero arc rules (nose/wings/aft), not Mek arc rules (front/side/rear)

  Implementing the following recommendation: Update the check to exclude LAMs in aero mode:
  && ((currentEntity() instanceof Mek mek && !mek.isAero()) || (currentEntity() instanceof Tank)
  || (currentEntity() instanceof ProtoMek))

File: megamek/src/megamek/client/ui/panels/phaseDisplay/FiringDisplay.java (hunk 2 above)
Comment (psikomonkie) [reply megamek/src/megamek/client/ui/panels/phaseDisplay/FiringDisplay.java:2376]: What's up with `FiringDisplay` lines `1746` & `1747`, or `MovePathHandler` line `2253`, or `VTOLAttackSprite` line `75`? In all three cases we cast the attacker to a VTOL, then call `getStrafingCoords`. Will that act as expected with the changes made in this PR to `getStrafingCoords`?

File: megamek/src/megamek/common/actions/compute/ComputeToHitIsImpossible.java [hunk 3]
```diff
@@ -927,13 +927,11 @@ static String toHitIsImpossible(Game game, Entity weaponEntity, int attackerId,
                     }
                 }
 
-                // Only direct-fire energy weapons can strafe
-                //FIXME we have different checks for this in FiringDisplay, here and in MML for some table
+                // Only direct-fire energy weapons that don't use ammo can strafe
+                // Plasma weapons are excluded because they use ammo (risk of explosion from ground fire)
```
Comment (psikomonkie) [inline megamek/src/megamek/common/actions/compute/ComputeToHitIsImpossible.java]: ?? I know they're excluded, but what's this about explosion ?

File: megamek/src/megamek/client/ui/panels/phaseDisplay/FiringDisplay.java (hunk 2 above)
Comment (HammerGS) [reply megamek/src/megamek/client/ui/panels/phaseDisplay/FiringDisplay.java:2376]: Those three locations are unaffected by this PR because they call a different method:

  - FiringDisplay:1749 → `vtol.getStrafingCoords()` (VTOL instance method)
  - MovePathHandler:2253 → `((VTOL) entity).getStrafingCoords()` (VTOL instance method)
  - VTOLAttackSprite:75 → `((VTOL) entity).getStrafingCoords()` (VTOL instance method)

  All three call `VTOL.getStrafingCoords()` - an instance method defined on the VTOL class that returns the coordinates stored on that entity.

  This PR modifies `FiringDisplay.getStrafingCoords(Coords center)` - a private method in FiringDisplay that calculates strafing coordinates for Aero units. Different method, same name.

  VTOLs store their strafing coords directly on the entity during movement phase (MovePathHandler:2253 adds to that list), then FiringDisplay and VTOLAttackSprite read from that stored list. They never use the FiringDisplay calculation method.

File: megamek/src/megamek/common/actions/compute/ComputeToHitIsImpossible.java (hunk 3 above)
Comment (HammerGS) [reply megamek/src/megamek/common/actions/compute/ComputeToHitIsImpossible.java]: Its part of the third related strafing bug, Plasma weapons can't be used in strafing we currently allow it. Its right in this report linked above - https://github.com/MegaMek/megamek/issues/5232

Comment (psikomonkie) [reply megamek/src/megamek/common/actions/compute/ComputeToHitIsImpossible.java]: That... Is the worst written rule ever. Can you include a link to the page, because even the original issue report has Sleet and Raoz being confused over referring to plasma ammo as explosive (because it isn't, but the rule explicitly includes it).

Comment (HammerGS) [reply megamek/src/megamek/common/actions/compute/ComputeToHitIsImpossible.java]: Resolved the comment to fully align with the rules. https://github.com/MegaMek/megamek/pull/7823/commits/eaba6902a0c41526f2ee8ffb13eb0e995308509e
