### PR TITLE
Fix #7839: Check if a carryable unit is carryable before attempting to load it and correct mek arms `toString()` 

### LINKED ISSUE #7839: Nightly 0.50.11 - MekArms display error / TacOps Picking Up Units References and Loading onto invalid units
### Brief Description *

Nightly MegaMek-0.50.11-PR-7837-215f5f0

Unselectable entity whne trying to load battle armor onto a mek. Option exists when TacOps Picking Up Units is selected OR not selected (should it not be available if the option is not selected?)

Image

Steps to reproduce

1) add unit of Battle Armor
2) There will be 2 options - the valid target, and the invalid target

Image

When option is not selected, BA can still be loaded onto invalid selections:

Steps to reproduce:
1) open lobby
2) Picking Up units is NOT enabled
3) Add mech (see below, Jenner)
4) add battle armor (see below, squad 5 elementals)

The elemtals should be too heavy for the jenner's weight class, and the Jenner has no arms. The option is also not enabled to allow it to take place if it did have arms:

(TOAR 95)

Image

Image

### 3. Steps to Reproduce

Invalid Reference:

Steps to reproduce

1) add unit of Battle Armor
2) There will be 2 options - the valid target, and the invalid target

Illegal units:
Steps to reproduce:
1) open lobby
2) Picking Up units is NOT enabled
3) Add mech (see below, Jenner)
4) add battle armor (see below, squad 5 elementals)

Image

### Attach Files

Image

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### MegaMek Suite Version *

MegaMek v0.50.11-PR-7837-215f5f0

### Operating System *

Win 11

### Java Version *

17.0.13

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by psikomonkie**
Fixes #7839 

Don't show "Mek Arms" as a valid transporter to load units onto in the lobby if the unit can't be loaded (either because Picking Up units is disabled, or because the unit is otherwise not eligible to go into the Mek's arms).

### CODE REVIEW

File: megamek/src/megamek/common/equipment/MekArms.java [hunk 1]
```diff
@@ -117,4 +119,41 @@ public double getUnused() {
     public String getTransporterType() {
         return "Arms";
     }
+
+    @Override
+    public String toString() {
+        return "Mek Arms - tons:" + getUnused();
```
Comment (HammerGS) [inline megamek/src/megamek/common/equipment/MekArms.java:125]: Hardcoded string?

Comment (psikomonkie) [reply megamek/src/megamek/common/equipment/MekArms.java:125]: Yes. This is used in BLK files, for example. It probably shouldn't be used in the front end like it is now, but, I'm trying to make the least amount of changes.

[the remark this answers is not in the document]
Comment (psikomonkie) [reply megamek/src/megamek/common/equipment/MekArms.java:125]: That is not true. ClampMountMek does not use the space there.

**Review by Sleet01 — APPROVED** [review]
LGTM
