### PR TITLE
Issue 6665: Fix Shifting Winds Limits

### LINKED ISSUE #6665: [Issue] Shifting Wind Strength doesn'd stay between set boundaries
### Brief Description *

"Shifting Wind Strength" under Planetary Conditions offers the ability to set a max and min amount of wind. Unfortunately, the game doesn't hold to those boundaries. Since wind strengths higher than strong gale begin to affect non-Mek units very negatively, this can lead to portions of your force being destroyed without warning.

### 3. Steps to Reproduce

started Megamek match

set planet conditions to enable shifting wind strength with a low of Light Gale and a high of Moderate Gale

During the match, the wind dropped to calm. Other experiences have seen storms and tornadoes appearing (which REALLY ruins infantry fights)

### Attach Files

Image

[gamelog.zip](https://github.com/user-attachments/files/19117781/gamelog.zip)

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### MegaMek Suite Version *

.50.03

### Operating System *

Windows 10

### Java Version *

17.0.11

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by psikomonkie**
Fixes #6665

The wind-strength-shifting logic was not using the `windMin` and `windMax`. It will now limit wind strength changes based on that.

### CODE REVIEW

File: megamek/src/megamek/common/planetaryconditions/PlanetaryConditions.java [hunk 1]
```diff
@@ -373,14 +372,18 @@ public void determineWind() {
             // Wind strength changes on a roll of 1 or 6
             switch (Compute.d6()) {
                 case 1: // weaker
-                    wind = wind.lowerWind();
-                    doSleetCheck();
-                    doSandStormCheck();
+                    if (wind.isStrongerThan(windMin)) {
+                        wind = wind.lowerWind();
+                        doSleetCheck();
```
Comment (HammerGS) [inline megamek/src/megamek/common/planetaryconditions/PlanetaryConditions.java:377]: Ok...this made me chuckle. I had images of the code reaching out to Sleet.

**Review by HammerGS — APPROVED** [review]

**Comment by psikomonkie** [comment]
This has Unit Tests coming for the whole `PlanetaryConditions::determineWind()` method which is why this is in draft.

**Review by Sleet01 — APPROVED** [review]
LGTM as well.
