### PR TITLE
Fix: Add scroll on unit display dialog (tabbed view)

### LINKED ISSUE #6951: [Issue] Unit Window not scrollable on Mac OS
### Brief Description *

No scroll available on "Unit Display" window on Mac OS. On a screen that is not that many pixels tall, the view is missing valuable information and there is no way to scroll to see it. Even a screen that is quite large in pixel height there is usually missing information.

I provided two screenshots to show. One with a slightly less amount of information and that was the default size I had the window to begin with. I did have room to expand it by dragging the window size in order to see if there was more information there.

Image

Image

### 3. Steps to Reproduce

_No response_

### Attach Files

_No response_

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MegaMek Suite Version *

0.50.05

### Operating System *

Mac OS X 15.3 (x86_64)

### Java Version *

23.0.1

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by Scoppio**
# What this does?

Adds scroll to UnitDisplay panels on tabbed view

This is not final, but it helps address the problem a little bit with minimal code intervention.

## Related issues

- Closes #6951

### CODE REVIEW

**Comment by kuronekochomusuke** [comment]
can you make the scroll bars optional?  they take up extra space, when space is really limited with these

**Comment by Scoppio** [comment]
> can you make the scroll bars optional? they take up extra space, when space is really limited with these

Yeah, it's possible, but I won't make it optional unless you can offer me evidence that they are taking up space when they are not necessary.
They were added as being optional and only showing up if the window is smaller than the contents it holds, so if they show up is because they need to be there otherwise the user wont be able to access the data in the dialog.

File: megamek/src/megamek/client/ui/dialogs/UnitDisplayContainer.java [hunk 1]
```diff
@@ -0,0 +1,10 @@
+package megamek.client.ui.dialogs;
+
+import megamek.client.ui.swing.unitDisplay.UnitDisplay;
+
+import javax.swing.JDialog;
+
```
Comment (rjhancock) [inline megamek/src/megamek/client/ui/dialogs/UnitDisplayContainer.java:6]: Copyright Header....

**Review by rjhancock — DISMISSED** [review]

File: megamek/src/megamek/client/ui/dialogs/UnitDisplayDialog.java [hunk 2]
```diff
@@ -61,6 +61,7 @@ public static void showEntity(final JFrame frame, Entity entity, final boolean n
         }
         localUnitDisplay.displayEntity(entity);
         localDialogInstance.setVisible(true);
+        localDialogInstance.dispose();
```
[the remark this answers is not in the document]
Comment (Scoppio) [reply megamek/src/megamek/client/ui/dialogs/UnitDisplayDialog.java]: Changed the way the dialogs are created, so this initializes one with the proper `onClose` behavior to actually dispose.

File: megamek/src/megamek/client/ui/dialogs/DisposableDisplayContainer.java [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+    /**
+     * Creates a new disposable container with a fresh dialog and display
+     *
+     * @param frame the parent frame for the dialog
+     */
+    DisposableDisplayContainer(JFrame frame) {
+        dialog = new UnitDisplayDialog(frame, null);
+        unitDisplay = new UnitDisplay(null, null);
+        dialog.add(unitDisplay, BorderLayout.CENTER);
+        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
```
Comment (Sleet01) [inline megamek/src/megamek/client/ui/dialogs/DisposableDisplayContainer.java:60]: Are there any performance concerns here?

**Review by Sleet01 — APPROVED** [review]
Looks good!

File: megamek/src/megamek/client/ui/dialogs/DisposableDisplayContainer.java (hunk 3 above)
Comment (Scoppio) [reply megamek/src/megamek/client/ui/dialogs/DisposableDisplayContainer.java:60]: None that I am aware of, this is what used to happen before, when it was all inside the constructor, I just moved to two separated classes to make it less bad.

**Review by Sleet01 — APPROVED** [review]
I'm not a huge fan of the swath of `mPan[Scroll]`-type variable names, but looks good otherwise.

**Review by Sleet01 — APPROVED** [review]
Now that's _clean_!  Very nice!
