### PR TITLE
Fix hex shift when changing tileset theme

### LINKED ISSUE #1645: Terrain displayed on map is shifted to adjacent hexes
### Environment
MM 0.47.3 started from MekHQ
Win10
Java (build 1.8.0_241-b07)

### Description
I am seeing some oddities when moving near water.  My meks show negative elevations, and I observed a pair of vehicles move onto and off of depth 2 water hexes.

The log recorded movement into water when the map showed a clear hex.  I had to jump the mek to get it to move.  It only moved one hex, even though the jump option showed four hexes.  It is consistent with only having one jump jet out of water.

> Wolverine WVR-6R #3 (Steel Recon) must make a piloting skill check while moving from hex 2812 to hex 2912 (entering Depth 2 Water).
> Needs 6 [2 (Base piloting skill) + 1 (cramped cockpit) + 3 (Tornado F1-F3) + 0 (entering Depth 2 Water)], rolls 9 : succeeds.

Elevation -1

Elevation -2

Vedettes moving onto and off of water hexes:
Water Move1

Water Move2

### Files

[Steel Recon30340120.zip](https://github.com/MegaMek/megamek/files/4145296/Steel.Recon30340120.zip)
[customs.zip](https://github.com/MegaMek/megamek/files/4145297/customs.zip)

Save game prior to the Vedette movement:
[autosave_2020-02-02_13-12-24.sav - Copy.gz](https://github.com/MegaMek/megamek/files/4145292/autosave_2020-02-02_13-12-24.sav.-.Copy.gz)

Save game after the Vedette movement:
[autosave_2020-02-02_13-15-18.sav - Copy.gz](https://github.com/MegaMek/megamek/files/4145294/autosave_2020-02-02_13-15-18.sav.-.Copy.gz)

Wolverine movement next to water:
[autosave_2020-02-02_13-26-51.sav - Copy.gz](https://github.com/MegaMek/megamek/files/4145295/autosave_2020-02-02_13-26-51.sav.-.Copy.gz)

The map was randomly generated.
[Water move.zip](https://github.com/MegaMek/megamek/files/4145298/Water.move.zip)

### LINKED ISSUE #1946: 0.47.7 Snapshot 2020-05-11 - Tile displacement on theme change
0.47.7 Snapshot from 2020-05-11

I was testing the new Building Fluff functionality on a pre-existing 30x15 map (The Valley - Town map (as it had a variety of buildings)).

Using the 'Change Tileset Theme' option in the map editor worked without any problem.
Using the 'Change Tileset Theme' option in battle, however, caused the previously-seen tile displacement issue.

Is there a difference between the application of the the option in the map editor and in 'battle mode' which might cause this?

### PR DESCRIPTION
**Pull request by neoancient**
When responding to a hex change event, the boardview repaints surrounding hexes as well, including making sure the theme is current. If not, it updates the hex but uses the coordinates of the original hex from the event rather than the coordinates of the surrounding hex.

Fixes #1946
Fixes #1645 (presumed)

### CODE REVIEW

File: megamek/src/megamek/client/ui/swing/boardview/BoardView1.java [hunk 1]
```diff
@@ -6661,16 +6663,20 @@ public void changeTheme() {
...
+        if (selectedTheme.equals("(Original Theme)")) {
+            for (Coords c: allCoords) {
                 IHex hex = board.getHex(c);
                 hex.resetTheme();
                 board.setHex(c, hex);
             }
 
         } else {
-            for (Coords c: allBoardHexes()) {
+            for (Coords c: allCoords) {
```
Comment (Windchild292) [inline megamek/src/megamek/client/ui/swing/boardview/BoardView1.java:6679]: Why make the change here instead of just fixing the allBoardHexes() erroneous null return and replacing it with Collections.emptyList() (the return value of ArrayList can be swapped to List without issue)

Comment (NickAragua) [reply megamek/src/megamek/client/ui/swing/boardview/BoardView1.java:6679]: Unknown whether allBoardHexes() is used elsewhere and what effects that may have (e.g. other places may depend on it being null).

Comment (neoancient) [reply megamek/src/megamek/client/ui/swing/boardview/BoardView1.java:6679]: Yes, that would be better.

Comment (neoancient) [reply megamek/src/megamek/client/ui/swing/boardview/BoardView1.java:6679]: It's used in one other place which also fails to check for a null return value.

Comment (NickAragua) [reply megamek/src/megamek/client/ui/swing/boardview/BoardView1.java:6679]: More bugs fixed = better.

File: megamek/src/megamek/client/ui/swing/boardview/BoardView1.java [hunk 2]
```diff
@@ -1459,25 +1445,27 @@ private void renderDonut(Graphics2D g, Coords coords, int radius) {
             drawHexBorder(g, p, Color.PINK, 0, 6);
         }
     }
+
     /**
-     *  Returns a list of Coords of all hexes on the board.
-     *  Returns ONLY hexes where board.getHex != null.
+     *  @return a list of {@ink Coords} of all hexes on the board.
```
Comment (Windchild292) [inline megamek/src/megamek/client/ui/swing/boardview/BoardView1.java:1450]:
```suggestion
     *  @return a list of {@link Coords} of all hexes on the board.
```

Comment (neoancient) [reply megamek/src/megamek/client/ui/swing/boardview/BoardView1.java:1450]: My fingers are tripping over themselves today.

**Comment by SJuliez** [comment]
Oh, I kinda had a fix for that (and quite some more nonsense) too... I'll see what happens when I open a PR.

**Comment by neoancient** [comment]
Sorry about that. I didn't see that you had assigned yourself to the issue until this was done.
