### PR TITLE
Fix 7449: Replace entity ID with actual entity to avoid NPEs

### LINKED ISSUE #7449: [Issue] Java exception upon melee attacks when searchlight is also an option
### Brief Description *

When a mek that has an option to use searchlight uses melee attack in the physical attack phase, an error occurs. The error can be clicked through and the physical attack then can be used without an error if pressed again.

Image

### 3. Steps to Reproduce

1. Have a MM instance with a scenario taking place under dark light conditions,
2. Have meks with a searchlight being an option attack in melee either kick or punch

### Attach Files

_No response_

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### MegaMek Suite Version *

MekHQ-0.50.07-nightly-2025-10-01

### Operating System *

Windows 11

### Java Version *

Adoptium 17

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by Sleet01**
It looks like we were mistakenly passing the activated entity ID rather than the entity itself, but the function to return a BoardView using an `int` is expecting a Board ID, not an entity ID.
This would only fire for:
1. _Not_ unit ID 0,
2. _Not_ already using the searchlight,
3. _With_ `AutoDeclareSearchlight` enabled,
4. With light level set such that a searchlight would be beneficial,
so it was sort of a pain to repro - tip of the hat to the reporter for getting a good repro save.

Close #7449 

Testing:
- Confirmed fix with OP's savegame.
- Ran all 3 projects' unit tests.

### CODE REVIEW

File: megamek/src/megamek/client/ui/panels/phaseDisplay/PhysicalDisplay.java [hunk 1]
```diff
@@ -816,7 +816,7 @@ private void doSearchlight() {
 
         // and add it into the game, temporarily
         game.addAction(saa);
-        clientgui.getBoardView(currentEntity).addAttack(saa);
+        clientgui.getBoardView(ce()).addAttack(saa);
```
Comment (IllianiBird) [inline megamek/src/megamek/client/ui/panels/phaseDisplay/PhysicalDisplay.java]: If it's not too much trouble can we rename this method. `ce` is a super ambiguous method name and even with good documentation is going to cause confusion. If nothing else it makes the code harder to parse 'at a glance'.

Comment (Sleet01) [reply megamek/src/megamek/client/ui/panels/phaseDisplay/PhysicalDisplay.java]: I have no confidence in my ability to cleanly replace `ce()` with `currentEntity()` without breaking stuff, but I'll give it a shot.

**Comment by Sleet01** [comment]
@IllianiBird I've expanded `ce()` to `currentEntity()` using the IDE's refactoring tools, and it seems to be working fine:
- all tests passing
- no errors or exceptions in debug logs
- game runs fine

Unless you have any objections, I'll go ahead and merge.

**Comment by IllianiBird** [comment]
I was about to say 'go for it' but then you already went for it :D
