### PR TITLE
correct NPE in bvReports when player is not on a team

### LINKED ISSUE #4759: [0.49.14] NPE when loading Victory screen when there is a spectator
### Environment
Megamek 0.49.14, which came with MekHQ
Windows, java 19

### Description
- At the end of a game, heading into the final results screen
- During the final round, there must be at least one extra player connected to the server that is not on any of the teams
- an NPE is triggered on the line `bvcTeam.bv += bvcPlayer.bv;`.  
- - I think it is because the `// Observers without initial entities get ignored` skip logic doesn't get triggered in the Victory screen due to the implementation of Player.isObserver()

error in the megamek log: 
```22:55:22,517 ERROR [megamek.MegaMek] {Packet Pump}
megamek.MegaMek.lambda$main$0(MegaMek.java:62) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot read field "bv" because "bvcTeam" is null
	at megamek.server.GameManager.bvReports(GameManager.java:1677)
	at megamek.server.GameManager.prepareVictoryReport(GameManager.java:1196)
	at megamek.server.GameManager.prepareForPhase(GameManager.java:2050)
```
 

### Files
[autosave_2023-08-31_18-57-54.sav.gz](https://github.com/MegaMek/megamek/files/12555197/autosave_2023-08-31_18-57-54.sav.gz)
[megamek.log](https://github.com/MegaMek/megamek/files/12555201/megamek.log)

Connect as Hubers Feuerreiter or New Hessen Armored Cavalry.

You will need to skip through the firing phase, but /victory has already been declared.   Player list contains a player named "Mannheim" who is a spectator and is not on either team.   

(Update: the error also happens if you instead connect as the non-teamed player, Mannheim.  The error also happens if all 3 players are connected.)

### PR DESCRIPTION
**Pull request by kuronekochomusuke**
- correct NPE in bvReports when player is not on a team

fixes #4759

### CODE REVIEW

File: megamek/src/megamek/server/GameManager.java [hunk 1]
```diff
@@ -1682,26 +1682,30 @@ private void bvReports(boolean checkBlind) {
...
-            bvcTeam.unitsCrewKilledCount += bvcPlayer.unitsCrewKilledCount;
-            bvcTeam.unitsFledCount += bvcPlayer.unitsFledCount;
-            bvcTeam.ejectedCrewActiveCount += bvcPlayer.ejectedCrewActiveCount;
-            bvcTeam.ejectedCrewPickedUpByTeamCount += bvcPlayer.ejectedCrewPickedUpByTeamCount;
-            bvcTeam.ejectedCrewPickedUpByEnemyTeamCount += bvcPlayer.ejectedCrewPickedUpByEnemyTeamCount;
-            bvcTeam.ejectedCrewKilledCount += bvcPlayer.ejectedCrewKilledCount;
-            bvcTeam.ejectedCrewFledCount += bvcPlayer.ejectedCrewFledCount;
+            int playerTeam = player.getTeam();
+
+            if (playerTeam != Player.TEAM_UNASSIGNED && playerTeam != Player.TEAM_NONE) {
```
Comment (Windchild292) [inline megamek/src/megamek/server/GameManager.java:1687]:
```suggestion
            if ((playerTeam != Player.TEAM_UNASSIGNED) && (playerTeam != Player.TEAM_NONE)) {
```

**Review by Windchild292 — APPROVED** [review]
