### PR TITLE
Board Overlays: numerous problems

### LINKED ISSUE #4537: Uncaught Exception on preview game map - 0.49.14-SNAPSHOT
### Environment
Build Date: 2023-06-16T01:30:11.892597800
Origin Project: MegaMek
Java Version: 17.0.7
Platform: Windows 11 10.0 (amd64)

### Description
Uncaught Exception when viewing map preview in MM. Verified Issue not present in 49.13

Maybe something to do with pr #4514

To recreate:
>Run fresh MM install
>Start a new game
>Select map
>Preview game map

### Files
[megamek.log](https://github.com/MegaMek/megamek/files/11774731/megamek.log)

### PR DESCRIPTION
**Pull request by SJuliez**
Corrects numerous problems, hopefully without introducing too many new ones
- prevents updating the done button and turn summary in phase displays that aren't active
- streamlines turning overlay visibility on/off 
- prevents adding overlays in boardviews that dont need them (it seems safer to create them but it isn't, I immediately got NPEs from listener calls for overlays that were never used, no less than three separate TurnDetailsOverlays)
- ~~removes event listening from overlays (let the boardview have control)~~
- fixes #4537

### CODE REVIEW

File: megamek/src/megamek/client/ui/swing/boardview/AbstractBoardViewOverlay.java [hunk 1]
```diff
@@ -91,11 +74,9 @@ public AbstractBoardViewOverlay(Game game, ClientGUI cg, Font font, String heade
         currentPhase = game.getPhase();
         game.addGameListener(gameListener);
         clientGui = cg;
-        KeyBindParser.addPreferenceChangeListener(this);
-        GUIP.addPreferenceChangeListener(this);
 
         Color colorTitle = GUIP.getPlanetaryConditionsColorTitle();
-        header = String.format("#%02X%02X%02X %s",
+        header = String.format("#%02X%02X%02X%s",
                 colorTitle.getRed(), colorTitle.getGreen(), colorTitle.getBlue(), headerText);
```
Comment (pakfront) [inline megamek/src/megamek/client/ui/swing/boardview/AbstractBoardViewOverlay.java:80]: This can use the utility function AbstractBoardOverlay.colorToHex()

File: megamek/src/megamek/client/ui/swing/boardview/TurnDetailsOverlay.java [hunk 2]
```diff
@@ -67,10 +57,6 @@ protected void gameTurnOrPhaseChange() {
         super.gameTurnOrPhaseChange();
     }
 
-    @Override
-    protected void setVisibilityGUIPreference(boolean value) {
```
Comment (pakfront) [inline megamek/src/megamek/client/ui/swing/boardview/TurnDetailsOverlay.java:71]: Where did the setVisibilityGUIPreference logic get moved to?

**Review by pakfront — COMMENTED** [review]
Thanks for cleaning this up. I had tested it by running games myself, did not encounter the NPEs, but  obviously they are there.  (edit, ah the Preview Map from the Map selection UI. I was not even aware that existed.)

File: megamek/src/megamek/client/ui/swing/boardview/TurnDetailsOverlay.java (hunk 2 above)
Comment (pakfront) [reply megamek/src/megamek/client/ui/swing/boardview/TurnDetailsOverlay.java:71]: and does this still respond to GUIP changes with the IPreferenceChangeListener removed?

Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/boardview/TurnDetailsOverlay.java:71]: not finished yet! I first moved the reaction into BoardView but I've since changed my viewpoint. I'll move it back into the Overlay. The logic for this is that the menu item for any of the overlays only changes the GUIP setting and everything else happens as a preferenceChangeEvent reaction. We don't have many static event generators but this one we must make use of :)

File: megamek/src/megamek/client/ui/swing/boardview/AbstractBoardViewOverlay.java (hunk 1 above)
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/boardview/AbstractBoardViewOverlay.java]: Aye

**Comment by SJuliez** [comment]
I think this is now ready...

**Comment by SJuliez** [comment]
The NPE on the board preview was only a tooltip problem and had nothing to do with the turn overlay.

The overlays now have their listeners again :) but in return they aren't created with every boardview. The lobby preview doesn't create them but the board editor does although it only uses the keybinds overlay. I simplified the constructor a bit. Every boardview must have a game with a board though not necessarily a clientgui but all these can be accessed from the boardview itself (in an obviously-bad way by directly accessing the public field. Something to correct on another day).

I think the main thing is what I wrote above: Toggling an overlay in CommonMenuBar only directly toggles the GUIP setting, the rest follows from the event (even the checkmark on the menu item is set from the event in CommonMenuBar in case it originates somewhere else). The setVisibilityGUIPreference didn't seem necessary anymore.

I also made the updateDoneButton method in AbstractActionDisplay (was this the name?) only act when it is not ignoring events. I hope this doesnt create problems but it seemed to work. I noticed the turn events being overwritten by phase displays for not-current-phases.

**Review by pakfront — APPROVED** [review]
Looks good.
