### PR TITLE
make planetary weather conditions more fault tolerant

### LINKED ISSUE #3475: [0.49.7] Uncaught java.lang.IllegalArgumentException in scenario
### Environment
MegaMek standalone
Windows 10
Java Vendor: ojdkbuild
Java Version: 11.0.14

### Description
Opened program, loaded scenario "Example.mms"
Laid mines (density 5), laid vibrabombs (density 5, sensitivity 20)
Hit "Done"
Error box popped up, "Uncaught java.lang.IllegalArgumentException detected. Please open..."

### Files
Player name: PlayerA
[megamek.log](https://github.com/MegaMek/megamek/files/8170914/megamek.log)
[error_save.sav.gz](https://github.com/MegaMek/megamek/files/8170916/error_save.sav.gz)

### PR DESCRIPTION
**Pull request by NickAragua**
When setting planetary conditions, do not allow them to be set to an invalid value - instead, ignore the operation, log the error, and move on. Fixes #3475

### CODE REVIEW

File: megamek/src/megamek/common/PlanetaryConditions.java [hunk 1]
```diff
@@ -799,7 +801,11 @@ public int getLight() {
     }
 
     public void setWeather(int type) {
-        weatherConditions = type;
+        if ((type <= 0) || (type >= WE_SIZE)) {
```
Comment (neoancient) [inline megamek/src/megamek/common/PlanetaryConditions.java:804]: Is there a reason for disallowing WE_NONE?

**Review by neoancient — APPROVED** [review]
