### PR TITLE
Fix #7855: Fix Victory Report for `AdvancedBuildingEntity`

### LINKED ISSUE #7855: [Issue] NPE At Match End With Advanced Buildings
### Brief Description *

A NPE is generated at the end of a match if the match includes one of the new advanced buildings. 

```
10:54:46,240 ERROR [megamek.MegaMek] {Packet Pump}
megamek.MegaMek.lambda$main$1(MegaMek.java:111) - Uncaught java.lang.NullPointerException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
java.lang.NullPointerException: Cannot invoke "java.util.Collection.toArray()" because "c" is null
	at java.base/java.util.Vector.addAll(Vector.java:896)
	at megamek.server.totalWarfare.TWGameManager.addReport(TWGameManager.java:28772)
	at megamek.server.totalWarfare.TWGameManager.prepareVictoryReport(TWGameManager.java:1324)
	at megamek.server.totalWarfare.TWPhasePreparationManager.managePhase(TWPhasePreparationManager.java:250)
	at megamek.server.totalWarfare.TWGameManager.prepareForCurrentPhase(TWGameManager.java:1909)
	at megamek.server.AbstractGameManager.changePhase(AbstractGameManager.java:126)
	at megamek.server.totalWarfare.TWPhaseEndManager.managePhase(TWPhaseEndManager.java:291)
	at megamek.server.totalWarfare.TWGameManager.endCurrentPhase(TWGameManager.java:2069)
	at megamek.server.totalWarfare.TWGameManager.checkReady(TWGameManager.java:1433)
	at megamek.server.AbstractGameManager.handlePacket(AbstractGameManager.java:80)
	at megamek.server.totalWarfare.TWGameManager.handlePacket(TWGameManager.java:717)
	at megamek.server.Server.handle(Server.java:1358)
	at megamek.server.Server$PacketPump.run(Server.java:153)
	at java.base/java.lang.Thread.run(Thread.java:840)
``` 

### 3. Steps to Reproduce

1. Add advanced buildings to a match.
2. Play the match to completion or use "/victory" 
3. Observe NPE

### Attach Files

[megamek.log](https://github.com/user-attachments/files/24409763/megamek.log)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MegaMek Suite Version *

MekHQ-0.50.12-nightly-2026-01-02

### Operating System *

Windows 11

### Java Version *

Adoptium 17.0.11

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by psikomonkie**
Fixes #7855

### CODE REVIEW

File: megamek/src/megamek/common/units/AbstractBuildingEntity.java [hunk 1]
```diff
@@ -706,7 +706,41 @@ public void addEquipment(Mounted<?> mounted, int loc, boolean rearMounted)
      */
     @Override
     public Vector<Report> victoryReport() {
-        return null;
+        Vector<Report> vDesc = new Vector<>();
+
+        Report r = new Report(7025);
```
Comment (IllianiBird) [inline megamek/src/megamek/common/units/AbstractBuildingEntity.java]: As this is new code, can we lose the single letter variable name?

**Review by IllianiBird — APPROVED** [review]
Approved, but I would prefer to lose the single-letter variable name

**Comment by HammerGS** [comment]
@psikomonkie Someone feedback to address then we can merge.

File: megamek/src/megamek/common/units/AbstractBuildingEntity.java (hunk 1 above)
Comment (psikomonkie) [reply megamek/src/megamek/common/units/AbstractBuildingEntity.java]: Done, `r` is now `report`

File: megamek/src/megamek/common/units/AbstractBuildingEntity.java [hunk 2]
```diff
@@ -706,7 +706,41 @@ public void addEquipment(Mounted<?> mounted, int loc, boolean rearMounted)
...
+                r.addDesc(killer);
+            } else {
+                r = new Report(7073, Report.PUBLIC);
+            }
+            vDesc.addElement(r);
+        } else if (getCrew().isEjected()) {
+            r = new Report(7071, Report.PUBLIC);
+            vDesc.addElement(r);
+        }
+        r.newlines = 2;
```
[the remark this answers is not in the document]
Comment (psikomonkie) [reply megamek/src/megamek/common/units/AbstractBuildingEntity.java]: Done, but differently.
