### PR TITLE
Fix 7409: starting location only updating once via apply button

### LINKED ISSUE #7409: [Issue] 50.06 Deployment Area Apply button only works 1 time
### Brief Description *

Image

The Apply button here doesn't apply the selected NW/SE corner values if it has already been clicked before.

Correct behavior: the Apply button should work no matter how many times it has been clicked before

(You can work around this by reopening the player settings if you want to update these values again.)

### 3. Steps to Reproduce

- start new game
- right click player, bring up Player Settings
- set Deployment Any NW/SE Corner to some values
- click Apply.  The numbers will be properly applied to the player.
- update any of the corner values again
- click Apply.  The player's deployment will not be updated.  (clicking ok also doesn't update the area, but i don't think it's supposed to)

### Attach Files

_No response_

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don't affect gameplay and occur rarely.

### MegaMek Suite Version *

0.50.06

### Operating System *

Windows 10 10.0 (amd64)

### Java Version *

Eclipse Adoptium 17.0.12

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by Sleet01**
Avoids an issue with the dialog's Player info and the local client's version of the same info desynching while within the 
player settings dialog.
The initial change to the player's deployment area would be sent out, but further changes would not be applied... because the local client's game would not update until the dialog closed.
Fix is to send out the dialog's version of the Player instance, and let the AbstractClient and / or Server worry about keeping the local client's game in sync.

Testing:
- Ran all 3 projects' unit tests
- Confirmed fix now applies player starting zone updates every time Apply is pressed.

Close #7409

### CODE REVIEW

File: megamek/src/megamek/client/AbstractClient.java [hunk 1]
```diff
@@ -227,7 +227,16 @@ public void sendNextPlayer() {
...
      */
     public void sendPlayerInfo() {
-        send(new Packet(PacketCommand.PLAYER_UPDATE, getGame().getPlayer(localPlayerNumber)));
+        sendPlayerInfo(getGame().getPlayer(localPlayerNumber));
+    }
+
+    /**
+     * Sends the info associated with a player, usually the local game's local player but sometimes the modified version
+     * of that player.
+     * @param player
```
Comment (IllianiBird) [inline megamek/src/megamek/client/AbstractClient.java:236]: If we're not going to include a description of the param, do we need to include it?

In this instance it's super obvious what `Player player` is, especially from the rest of the JavaDoc

File: megamek/src/megamek/client/ui/panels/phaseDisplay/lobby/PlayerSettingsDialog.java [hunk 2]
```diff
@@ -637,7 +637,7 @@ private void apply() {
                 // Use sendUpdate because we want the Game to allow us to change on Bot's
                 // behalf.
                 clientgui.chatlounge.sendProxyUpdates(updateEntities, client.getLocalPlayer());
-                // clientGUI.chatlounge.sendUpdate(updateEntities);
```
Comment (IllianiBird) [inline megamek/src/megamek/client/ui/panels/phaseDisplay/lobby/PlayerSettingsDialog.java:640]: Do you know why this was commented out, originally? My concern is that it was disabled for a good reason and that re-enabling it is going to cause unexpected problems.

The lack of comment explaining why something was commented out is always gray-hair inducing :D

File: megamek/src/megamek/client/AbstractClient.java (hunk 1 above)
Comment (Sleet01) [reply megamek/src/megamek/client/AbstractClient.java:236]: I _believe_ the build tests will throw an error if there is a comment block without a matching @param for each argument to the function so I've been relying on Idea's auto-complete to fill those in, but to be honest I just forgot to explicitly describe it here.

File: megamek/src/megamek/client/ui/panels/phaseDisplay/lobby/PlayerSettingsDialog.java (hunk 2 above)
Comment (Sleet01) [reply megamek/src/megamek/client/ui/panels/phaseDisplay/lobby/PlayerSettingsDialog.java:640]: That is totally valid.
Looking through the history, it looks like I commented it out to test replacing it with sendProxyUpdates(), which is the call that allows one player to make updates to another player's configuration (e.g. Player 1 changing a bot's entities).
Then it got renamed during Tex's name normalization pass.
So I uncommented and renamed it, thinking that it was left commented out as an interim fix.
Then I tested with it in place.

Leaving it in place may cause additional chat log spam as player munition configuration changes will get logged twice, but it doesn't do anything for bot changes (the local player can't make bot config changes without going through `sendProxyUpdate()`).
But it's fine to delete it.
