### PR TITLE
fix NPE when selecting vehicle grenade launcher pointing off board

### LINKED ISSUE #3753: NPE when using VGL on map edge
This particular bug goes back a ways as far I can can tell, at least back to .47 if not farther. This bug happens when you move a unit with a VGL such as the Estevez to the edge of the map board.
tank_good
tank_npe

[megamek.log](https://github.com/MegaMek/megamek/files/9025058/megamek.log)
[VGL_bug.sav.gz](https://github.com/MegaMek/megamek/files/9025052/VGL_bug.sav.gz)

### PR DESCRIPTION
**Pull request by NickAragua**
A couple of fixes 

- an NPE during "to hit" calculations if the targeted hex is somehow off board
- if we have a vehicular grenade launcher where its primary hex is off board, you can still shoot it as long as at least one of the three hexes it'll hit is on the board; also moves "business logic" out of a "UI" class.

fixes #3753

### CODE REVIEW

File: megamek/src/megamek/common/weapons/mortars/VehicularGrenadeLauncherWeapon.java [hunk 1]
```diff
@@ -75,4 +80,39 @@ protected AttackHandler getCorrectHandler(ToHitData toHit, WeaponAttackAction wa
...
+    
+    public static Targetable getTargetHex(Mounted weapon, int weaponID) {
+        Entity owner = weapon.getEntity();
+        int facing;
+        
+        if (owner.isSecondaryArcWeapon(weaponID)) {
+            facing = owner.getSecondaryFacing();
+        } else {
+            facing = owner.getFacing();
+        }
```
Comment (Windchild292) [inline megamek/src/megamek/common/weapons/mortars/VehicularGrenadeLauncherWeapon.java:92]: Ternary candidate

**Review by Windchild292 — APPROVED** [review]
