### PR TITLE
Fix: Centering on unit was broken (#7237)

### LINKED ISSUE #7237: [Issue] Centering on units is broken
### Brief Description *

Neither tab or space center on a unit consistently.

### 3. Steps to Reproduce

1. Load a game with several units
2. During the movement phase, press "next unit"
3. Not all units are centered on

### Attach Files

_No response_

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MegaMek Suite Version *

0.50.07 Nightly

### Operating System *

Mac OS / Linux

### Java Version *

Tamurin 17

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by GamesByFelix**
Fixes #7237

### CODE REVIEW

**Comment by Sleet01** [comment]
Can you add a comment highlighting the code change that actually fixes the issue?

File: megamek/src/megamek/client/ui/clientGUI/boardview/BoardView.java [hunk 1]
```diff
@@ -3476,7 +3533,7 @@ public void centerOnHex(@Nullable Coords coords) {
             // no soft centering:
             // center on coords directly
             Point centreHexLocation = getCentreHexLocation(coords);
-            centerOnPointRel(centreHexLocation.x / boardSize.getWidth(), centreHexLocation.x / boardSize.getHeight());
+            centerOnPointRel(centreHexLocation.x / boardSize.getWidth(), centreHexLocation.y / boardSize.getHeight());
```
Comment (GamesByFelix) [inline megamek/src/megamek/client/ui/clientGUI/boardview/BoardView.java:3536]: @Sleet01  Somehow a .x got inserted for the y coordinate 🫣

Comment (Sleet01) [reply megamek/src/megamek/client/ui/clientGUI/boardview/BoardView.java:3536]: Holy cow, nice work tracking _that_ down!

Comment (GamesByFelix) [reply megamek/src/megamek/client/ui/clientGUI/boardview/BoardView.java:3536]: Yeah, it took me over an hour of testing and being absolutely puzzled about what the heck was going on. I still don't know how/why that .x got in there. It has nothing to do with my new zoom feature, but well ... I must have accidentally inserted it at some point, because it was there after my commit. Whoops 😳

I'm also limiting the "code reformatting on save" in IDEA to "lines changed" now, because that makes it a lot easier to check these things.

**Review by Scoppio — APPROVED** [review]
