### PR TITLE
Fixed Missing Prone Modifier in Weapon Attack Calculation

### LINKED ISSUE #6778: 50.04 - Prone Mechs do not receive +1 defensive for being Prone from distance
### Brief Description *

50.04 - Mechs which are prone, when targeted by attackers who are not adjacent, hte attacker should recieve +1 modifier to weapon attacks. Issue:. Other units not adjacent, should recieve a +1 penalty to shoot it. they do not. 
Battlemech Manual Page 30: Attacking Prone Mechs: If the attacker is not adjacemt, apply a +1 modifier.

### 3. Steps to Reproduce

Go Prone with a Mech
Get shot with weapon attack from a unit who is not adjacent
Target number for being attacked does not accrue +1 to attacker of prone mech

Image

### Attach Files

[megamek.log](https://github.com/user-attachments/files/19498091/megamek.log)
[ProneNoPlus1.sav.gz](https://github.com/user-attachments/files/19498040/ProneNoPlus1.sav.gz)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MegaMek Suite Version *

 Starting MegaMek v0.50.04     Build Date: 2025-03-22T14:11:50.477040

### Operating System *

  Platform: Windows 11 10.0 (amd64)

### Java Version *

 Java Vendor: Eclipse Adoptium     Java Version: 17.0.13

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiCBT**
- Corrected the logic to append the prone modifier (`proneMod`) to the hit calculation when applicable.

Fix #6778

### Dev Notes
This conditional looks like it was accidentally removed during the recent fixes made to swarm missiles. All I did was restore it.

Sleet, I've requested you as a reviewer as it looks like you were the one to remove the conditional, so I want your confirmation that it wasn't an intentional change. :)

### CODE REVIEW

File: megamek/src/megamek/common/actions/WeaponAttackAction.java [hunk 1]
```diff
@@ -4280,6 +4577,9 @@ private static ToHitData compileTargetToHitMods(Game game, Entity ae, Targetable
                 proneMod = new ToHitData(1, Messages.getString("WeaponAttackAction.ProneRange"));
             }
         }
+        if (proneMod != null) {
```
Comment (IllianiCBT) [inline megamek/src/megamek/common/actions/WeaponAttackAction.java:4580]: Here's the actual changes. The rest is the autoformatter.

Comment (Sleet01) [reply megamek/src/megamek/common/actions/WeaponAttackAction.java:4580]: Almost certainly unintended.

**Review by Sleet01 — APPROVED** [review]
LGTM, just need to confirm that Swarm missiles don't get the prone mod from the original target (I believe it gets removed explicitly).

**Comment by Sleet01** [comment]
Yeah, the Prone modifiers get removed every time a Swarm attack retargets, so that post is good
