### PR TITLE
Issue 6751: Princess will now deploy mines on her turn instead of at the start of the phase.

### LINKED ISSUE #6751: [0.50.04-SNAPSHOT] Not allowed to deploy mines with frontline deployment unit (should qualify for six mine tiles).
### Brief Description *

Simple - unit is set to frontline, commander has 3 tactics, and deployed on a defense mission. The relevant unit should be getting the ability to deploy minefields; when deploying the unit, the interface claimed six tiles of mines would be available, which is correct according to the documentation.

Starting the game skips the usual mine-placing phase entirely, and continues on to deployment. 

### 3. Steps to Reproduce

This appears to replicate normally: set up conditions for a frontline unit to engage in a mission, with the commander having sufficient Tactics to qualify for Tactic Points (= 2x Tactics skill). Do not deploy any additional units (like infantry ), and all points will convert into mine tiles. 

Proceed to fight the battle. 

The attached savegame has a battle ready where all these conditions apply. 

### Attach Files

[1st Border Knights30230530.cpnx.gz](https://github.com/user-attachments/files/19406513/1st.Border.Knights30230530.cpnx.gz)

[mekhq.log](https://github.com/user-attachments/files/19406514/mekhq.log)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MekHQ Suite Version *

MekHQ v0.50.04-SNAPSHOT - rev. fe9e89ce4743887f9bb9f083b44563d410ff85be

### Operating System *

Windows 11 10.0 (amd64)

### Java Version *

    Java Vendor: Eclipse Adoptium     Java Version: 21.0.3

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by psikomonkie**
Fixes #6751 

I found there was another attempted implementation of Princess deploying minefields. It looks like it was abandoned and didn't do anything, I've marked it as `@Deprecated`. Note that the method deprecated in `BotClient` is not marked as for removal, IntelliJ throws an error (not warning) if I have a method overriding a deprecated for-removal method, like what would happen if `BotClient::calculateMinefieldDeployment` was marked as for-removal.

### CODE REVIEW

**Comment by psikomonkie** [comment]
This is ready for review.

**Review by IllianiCBT — APPROVED** [review]
Looks good :)

File: megamek/src/megamek/client/bot/BotClient.java [hunk 1]
```diff
@@ -276,6 +275,10 @@ protected int pickTagTarget(GameCFREvent evt) {
      */
     protected abstract MovePath continueMovementFor(Entity entity);
 
+    /**
+     * Deprecated, consider {@link BotClient#deployMinefields()}
+     */
+    @Deprecated (since = "0.50.05")
     protected abstract Vector<Minefield> calculateMinefieldDeployment();
```
Comment (rjhancock) [inline megamek/src/megamek/client/bot/BotClient.java:282]: two things:

1. Use the `@deprecated` JavaDoc tag. It'll stand out in the documentation to find it easier.

2. If the IDE says no uses, add the `forRemoval = true` flag to the `@Deprecated` annotation. Don't know if there are or not, just making note of it for future things.

Comment (psikomonkie) [reply megamek/src/megamek/client/bot/BotClient.java]: > two things:
> 
>1. Use the `@deprecated` JavaDoc tag. It'll stand out in the documentation to find it easier.
> 
>2. If the IDE says no uses, add the `forRemoval = true` flag to the `@Deprecated` annotation. Don't know if there are or not, just making note of it for future things.

Changed the javadoc like requested. There is one usage, the implementation itself, which I marked as `for removal`.

Comment (IllianiCBT) [reply megamek/src/megamek/client/bot/BotClient.java]: I recommend if the method is still in use, or if you're uncertain, still define the removal `forRemoval = false` as that removes any doubt as to whether that was a conscious decision or just forgotten. If that makes sense?

**Review by rjhancock — APPROVED** [review]
