### PR TITLE
Fix aero ammo explosion rep

### LINKED ISSUE #2144: 47.9 - Curious ASF heat-related ammo explosion behavior
Seems that ASF ammo doesn't actually blow up.

Get yourself an aerospace fighter that has ammo and a target to shoot at. Turn all heat sinks off. Fire guns until heat reaches ammo explosion levels. Luckily, ammo doesn't actually explode. Phew!

image

### PR DESCRIPTION
**Pull request by NickAragua**
Fixes #2144 

Pulled logic relevant to processing aero heat out of Server.java and into the ServerHelper class. Changed access level on a couple of server methods to package private.

Actual fix is on line 352 of ServerHelper.java. The issue was that the roll wasn't being added to the report, so it was incorrectly reporting an ammo explosion.

### CODE REVIEW

File: megamek/src/megamek/server/ServerHelper.java [hunk 1]
```diff
@@ -48,4 +61,338 @@ public static boolean infantryInOpen(Entity te, IHex te_hex, IGame game,
...
+    /**
+     * Worker function that handles heat as applied to aerospace fighter
+     */
+    public static void resolveAeroHeat(IGame game, Entity entity, Vector<Report> vPhaseReport, Vector<Report> rhsReports, 
+            int radicalHSBonus, int hotDogMod, Server s) {
+        Report r;
+        
+        // If this aero is part of a squadron, we will deal with its
+        // heat with the fighter squadron
+        if ((game.getEntity(entity.getTransportId()) instanceof FighterSquadron)) {
```
Comment (Windchild292) [inline megamek/src/megamek/server/ServerHelper.java:74]:
```suggestion
        if (game.getEntity(entity.getTransportId()) instanceof FighterSquadron) {
```

File: megamek/src/megamek/server/ServerHelper.java [hunk 2]
```diff
@@ -48,4 +61,338 @@ public static boolean infantryInOpen(Entity te, IHex te_hex, IGame game,
...
+        if (mtHeat) {
+            autoShutDownHeat = 50;
+        }
+
+        // heat effects: start up
+        if ((entity.heat < autoShutDownHeat) && entity.isShutDown()) {
+            // only start up if not shut down by taser or a TSEMP
+            if ((entity.getTaserShutdownRounds() == 0)
+                    && (entity.getTsempEffect() != TSEMPWeapon.TSEMP_EFFECT_SHUTDOWN)) {
+                if ((entity.heat < 14) && !(entity.isManualShutdown())) {
```
Comment (Windchild292) [inline megamek/src/megamek/server/ServerHelper.java:211]:
```suggestion
                if ((entity.heat < 14) && !entity.isManualShutdown()) {
```

File: megamek/src/megamek/server/ServerHelper.java [hunk 3]
```diff
@@ -48,4 +61,338 @@ public static boolean infantryInOpen(Entity te, IHex te_hex, IGame game,
...
+                    // automatically starts up again
+                    entity.setShutDown(false);
+                    r = new Report(5045);
+                    r.subject = entity.getId();
+                    r.addDesc(entity);
+                    vPhaseReport.add(r);
+                } else if (!(entity.isManualShutdown())) {
```
Comment (Windchild292) [inline megamek/src/megamek/server/ServerHelper.java:218]:
```suggestion
                } else if (!entity.isManualShutdown()) {
```

**Comment by Windchild292** [comment]
I think you mean line 353?

**Review by Windchild292 — APPROVED** [review]
