### PR TITLE
Fix #6336 - Battle Armor Pop-Up Mines now deal damage per mine

### LINKED ISSUE #6336: [0.52.02] Battle Armor Pop-Up Mine not doing full damage
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Pop-Up Mines are only doing 4 points of damage when they hit, but should be doing four points of damage _per mine_. See attached screen shot for example.

Relevant Text from Total Warfare, pg. 229:

>  If the attack hits, roll on the Cluster Hits Table (corresponding to the appropriate number of troopers active in the unit who fired) to determine how many mines have become attached to the target. The mines automatically hit the center torso if the target is a ’Mech, the front if the target is a vehicle, or nose if the target is a grounded fighter: four points of damage are assigned per mine that struck the location.

### Steps to Reproduce

1. Deploy BA with Pop-Up Mine weapon (Sloth or Shen Long are the canon units that mount one)
2. In the System tab, set the Pop-Up Mine to fire multiple mines
3. Successfully conduct a Pop-Up Mine Attack (suggest shutdown friendly mech for testing purposes)
4. Observe damage resolution and note that damage is four points of damage, no matter how many mines hit.

### Operating System *

Windows 11

### Java Version *

17.0.11

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMek Version

0.52.02

### Attach Files

Screenshot 2024-12-31 131529

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

### PR DESCRIPTION
**Pull request by HammerGS**
---
  Summary

  - Pop-up mines now correctly deal 4 damage per mine that hits
  - Each mine rolls for critical hit independently
  - Multi-shot modes (2-shot through 6-shot) now function correctly

  Problem

  Pop-up mines only dealt 4 damage total regardless of how many mines struck the target. Per TW p.229: "four points of damage are assigned per mine that struck the location."

  Root Cause

  In PopUpMineLauncherHandler.handleEntityDamage(), the hits parameter (number of mines that hit) was completely ignored. The method processed exactly one mine regardless of how many actually hit.

  Fix

  Wrapped the crit roll and damage logic in a while (hits > 0) loop to process each mine individually. Each mine now:
  1. Rolls for critical hit on CT (Meks) or Front (Tanks)
  2. If no crit effect → deals 4 damage
  3. If crit effect → applies the crit instead of damage

  Test Plan

  - In-game testing: 5 mines hit → multiple 4-damage entries, multiple crit rolls (2 Engine crits, 3 Gyro crits), armor destroyed and IS damaged
  
  
image

### CODE REVIEW

File: megamek/src/megamek/common/weapons/handlers/PopUpMineLauncherHandler.java [hunk 1]
```diff
@@ -115,50 +115,55 @@ protected int calcHits(Vector<Report> vPhaseReport) {
...
+        // Per TW p.229: "four points of damage are assigned per mine that struck the location"
+        // Process each mine that hit
+        while (hits > 0) {
+            HitData hit = entityTarget.rollHitLocation(toHit.getHitTable(),
+                  toHit.getSideTable(), weaponAttackAction.getAimedLocation(),
+                  weaponAttackAction.getAimingMode(), toHit.getCover());
+            hit.setAttackerId(getAttackerId());
+            if (target instanceof Mek) {
+                hit = new HitData(Mek.LOC_CENTER_TORSO);
+            } else { // te instanceof Tank
```
Comment (IllianiBird) [inline megamek/src/megamek/common/weapons/handlers/PopUpMineLauncherHandler.java]: `te` should be `target`

File: megamek/src/megamek/common/weapons/handlers/PopUpMineLauncherHandler.java [hunk 2]
```diff
@@ -115,50 +115,55 @@ protected int calcHits(Vector<Report> vPhaseReport) {
...
-                LOGGER.error("No previous report when trying to add newline");
+                        hit.getLocation(), hit.isRear(),
+                        entityTarget.getArmorType(hit.getLocation()) == EquipmentType.T_ARMOR_HARDENED ? -2
+                              : 0,
+                        4);
+
+            // Replace "no effect" results with 4 points of damage.
+            if ((specialDamageReport.lastElement()).messageId == 6005) {
+                int damage = 4;
+                // ASSUMPTION: buildings CAN'T absorb *this* damage.
```
Comment (IllianiBird) [inline megamek/src/megamek/common/weapons/handlers/PopUpMineLauncherHandler.java]: Is this assumption correct?

**Review by IllianiBird — CHANGES_REQUESTED** [review]
One question and a minor typo

File: megamek/src/megamek/common/weapons/handlers/PopUpMineLauncherHandler.java (hunk 2 above)
Comment (HammerGS) [reply megamek/src/megamek/common/weapons/handlers/PopUpMineLauncherHandler.java]: It is they can only attack Mechs, Vehicles, and Landed Aerospace

File: megamek/src/megamek/common/weapons/handlers/PopUpMineLauncherHandler.java (hunk 1 above)
Comment (HammerGS) [reply megamek/src/megamek/common/weapons/handlers/PopUpMineLauncherHandler.java]: Fixed

File: megamek/src/megamek/common/weapons/handlers/PopUpMineLauncherHandler.java [hunk 3]
```diff
@@ -115,50 +115,55 @@ protected int calcHits(Vector<Report> vPhaseReport) {
...
+                try {
+                    (specialDamageReport.elementAt(specialDamageReport.size() - 2)).newlines++;
+                } catch (Exception ignored) {
+                    LOGGER.error("No previous report when trying to add newline");
+                }
             }
+            // Report the result for this mine
+            vPhaseReport.addAll(specialDamageReport);
+            hits--;
         }
```
[the remark this answers is not in the document]
Comment (HammerGS) [reply megamek/src/megamek/common/weapons/handlers/PopUpMineLauncherHandler.java:162]: Fixed https://github.com/MegaMek/megamek/pull/7789/commits/a1b139007eca43a36c81be5ba1f45f2cd0e05954

File: megamek/src/megamek/common/weapons/handlers/PopUpMineLauncherHandler.java [hunk 4]
```diff
@@ -115,50 +115,55 @@ protected int calcHits(Vector<Report> vPhaseReport) {
...
+        while (hits > 0) {
+            HitData hit = entityTarget.rollHitLocation(toHit.getHitTable(),
+                  toHit.getSideTable(), weaponAttackAction.getAimedLocation(),
+                  weaponAttackAction.getAimingMode(), toHit.getCover());
+            hit.setAttackerId(getAttackerId());
+            if (target instanceof Mek) {
+                hit = new HitData(Mek.LOC_CENTER_TORSO);
+            } else { // te instanceof Tank
+                hit = new HitData(Tank.LOC_FRONT);
+            }
```
[the remark this answers is not in the document]
Comment (HammerGS) [reply megamek/src/megamek/common/weapons/handlers/PopUpMineLauncherHandler.java:128]: https://github.com/MegaMek/megamek/pull/7789/commits/a1b139007eca43a36c81be5ba1f45f2cd0e05954

[the remark this answers is not in the document]
Comment (HammerGS) [reply megamek/src/megamek/common/weapons/handlers/PopUpMineLauncherHandler.java]: Resolved https://github.com/MegaMek/megamek/pull/7789/commits/a1b139007eca43a36c81be5ba1f45f2cd0e05954
