### PR TITLE
Issue 6264: Destroyed Infantry no longer have negative weight

### LINKED ISSUE #6264: Mechanized Tracked Platoon (Flamer) pays you for monthly spare parts and fuel instead of charging you
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMekLab documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

image
image

May be other instances of something like this but this is the only one I came across due to the new employer-provided mothballing behavior. The unit is unmanned/not in TOE so it was the only one to generated a cbill/fuel/ammo report this month!

[logs.zip](https://github.com/user-attachments/files/18084401/logs.zip)

Campaign file and MekHQ log included, no customs in this campaign

### Steps to Reproduce

1. Have unit specified
2. Check monthly costs report or have it unmothballed with no other active units on monthly cost generation

### Operating System *

Windows 10

### Java Version *

17

### MegaMek Suite Version *

None

### Custom MegaMekLab Version

Implemented Resupply Module #4518

### Attach Files

_No response_

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

### PR DESCRIPTION
**Pull request by psikomonkie**
Fixes #6264 

infantry.getInternal returns negative values for increasingly destroyed states for the infantry. But for determining weight it should just be 0 tons.

### CODE REVIEW

**Review by HammerGS — APPROVED** [review]

File: megamek/src/megamek/common/verifier/TestInfantry.java [hunk 1]
```diff
@@ -384,6 +384,9 @@ public static double getWeightExact(Infantry infantry, CalculationReport report)
 
         InfantryMount mount = infantry.getMount();
         int activeTroopers = infantry.getInternal(Infantry.LOC_INFANTRY);
```
Comment (SJuliez) [inline megamek/src/megamek/common/verifier/TestInfantry.java:386]: It feels like making this
`int activeTroopers = Math.max(0, infantry.getInternal(Infantry.LOC_INFANTRY));`
would do it more concisely

Comment (psikomonkie) [reply megamek/src/megamek/common/verifier/TestInfantry.java]: > It feels like making this `int activeTroopers = Math.max(0, infantry.getInternal(Infantry.LOC_INFANTRY));` would do it more concisely

I agree @SJuliez , that is a much more concise way to do it. Changed, thanks!

**Comment by psikomonkie** [comment]
Made the change suggested by SJuliez.
