### PR TITLE
MekHQ 1727: Colour Camouflage

### LINKED ISSUE #2499: Problems with camo and Megamek
Megamek 47.14

Camouflage on my Megamek games has been behaving...badly.

The attached unit always spawns with my team colours, even though the campaign options should prevent that.

And on this particular game, the allied civilian and the enemy forces have the same colour in the lobby, even if the Draconis Combine forces have "green" camo when I enter the camo setting menu.

The "No Camo" folder, which I suppose should hold the basic colours for camo, has only one option.

Camo Bug

Edit:
A few extra details:
- In MekHQ, the ally color is red and the enemy's green, but all the opfor on the mission have been in red camo
- The exceptions are scenarios with allied forces like civilians and allied lances, where the enemy spawns in green, allies in red
- This is the first time allied civilians and enemy forces spawned in the same colour
- I can choose any camo in the lobby for individual units, except any basic color (red green, yellow, etc). Those don't show anywhere
- I can choose those basic colours for players when changing the players colours on the left in the lobby

Files
[megameklog.zip](https://github.com/MegaMek/megamek/files/5674911/megameklog.zip)
[mekhqlog.zip](https://github.com/MegaMek/megamek/files/5674912/mekhqlog.zip)
[CamoBug.cpnx.gz](https://github.com/MegaMek/megamek/files/5674913/CamoBug.cpnx.gz)

### PR DESCRIPTION
**Pull request by Windchild292**
This PR contains the following changes:
- [x] Create PlayerColour Enum to simplify internal player colours
- [x] Separates Player Colours from Camouflage Colours (long-standing camo bug... the two should not correlate. However, this will require a separate enhancement allowing one to customize the colour, which will be done in the next few days)
- [x] Separates Colour Camouflage from No Camouflage
- [x] Standardize Camouflage Selector Dialogs (https://github.com/MegaMek/mekhq/issues/1727)
- [x] Fixes #2499, with the rest of the issue being MekHQ-origin issues subsumed by https://github.com/MegaMek/mekhq/issues/2318
- [x] Remove unused Icon Panel classes
- [x] Cleanup antiquated GUIPreferences usages (String name colours, string booleans)

This fixes #2499.

To Review: I'm currently testing this branch, but am opening it up so that it can be reviewed and tested by more than just myself. The changes here are significant enough to open a PR up before moving on with the camouflage changes. They are in a working state, albeit one that does not fix current bugs. Because of this I have identified the cause of https://github.com/MegaMek/mekhq/issues/2318, which will be fixed in the camouflage swapover

### CODE REVIEW

**Comment by gsparks3** [comment]
To check things out, I launched a Base Attack (Attacker) scenario I had saved with a large number of "players" (8 total groups! - my units, FedSuns allied force, base civilian units, base turrets, FWL opfor 1, FWL opfor 2, FWL local forces, and FWL reinforcements). Initial thoughts and comments: 

- The search function in the camo selector doesn't include the basic colour-camos. If you search "green", you'll get all the camo patterns with "green"  in the name, but not the actual green colour camo. It's easy enough to manually click on the "colour camo"  section and select one if desired, however. Some have relatively obscure names anyway. 
- The colour camos are still not automatically applied to the bot units, but you mentioned that wasn't fixed yet, so that's expected. Player-unit camo patterns as defined in Campaign Options are automatically applied, however. 
- The "player colors" (as indicated by unit label colors in the lobby) seem to be assigned differently now. Was this intended? Details: my units are Blue, FedSuns are Red, Base Civilian Units and Base Turrets are Blue, and all FWL forces are Green. 
- The "valid unit color" (for unit labels of units that have not moved yet, or are valid selection targets) is now displayed as a rather dark blue, rather than the previous cyan (in Client Settings-Advanced it's still specified as Cyan?). Selected units are still highlighted in Magenta. 
- MP expenditure text and the Show Possible Moves outlines are now displayed entirely in the same dark blue as above, rather than cyan and yellow for Walking and Running, respectively. Sprinting still has a magenta outline and text.

Some of these may be either intentional changes, or known temporary changes while you get other things worked out. 

Image of the unexpected blue colors: 
image

More comments to come later.

**Comment by gsparks3** [comment]
... the heck? This was working well enough yesterday, but now when I load the same fight everything explodes, graphics-wise. Initially only my units show up in the lobby, and then if I try to interact with anything it goes to a blank white screen. Elements re-render as I interact with them, e.g. by blindly waving the mouse around so it hovers over buttons, or clicking on things randomly. 

Initial appearance of lobby:
image

Initial appearance of lobby after blanking (literally just a blank white screen): 
image

Appearance after waving the mouse around a lot: 
image

If I hover over something for long enough for a tooltip to appear, it forces a re-render of the graphics under the tooltip (_only_ under the tooltip), but the tooltip doesn't always un-render when moving away ... see below 
image


megameklog and mekhqlog show a LOT of errors, although the megameklog doesn't seem particularly informative. Just constantly repeats `13:10:01,366 ERROR [megamek.client.ui.swing.util.PlayerColour] {AWT-EventQueue-0} parseFromString(), line 118 : Unable to parse PlayerColour from text null, returning BLUE`. 

mekhqlog has a large number of NPEs; may all be just repeats of the same error as well. Logs attached below.

[megameklog.txt](https://github.com/MegaMek/megamek/files/5743494/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/5743495/mekhqlog.txt)

Also, if I hit "I'm Done", it gets stuck at Transmitting Game Data. NPE for this:
`Exception in thread "Packet Pump" java.lang.NullPointerException 
	at megamek.server.Server.getColorForPlayer(Server.java:3811)
	at megamek.server.Server.prepareForPhase(Server.java:2423)
	at megamek.server.Server.changePhase(Server.java:2199)
	at megamek.server.Server.endCurrentPhase(Server.java:2782)
	at megamek.server.Server.changePhase(Server.java:2208)
	at megamek.server.Server.endCurrentPhase(Server.java:2757)
	at megamek.server.Server.changePhase(Server.java:2208)
	at megamek.server.Server.endCurrentPhase(Server.java:2741)
	at megamek.server.Server.checkReady(Server.java:1991)
	at megamek.server.Server.handle(Server.java:31255)
	at megamek.server.Server$PacketPump.run(Server.java:254)`

I swear I've had these kinds of shenanigans, where it works fine the first time I use a new version, then doesn't work later, before. 
Things like the tooltip armor display icons. That one was related to which Theme you had active when you last closed MekHQ, but switching back to Metal and reloading does not seem to fix this issue here. 

Campaign save for testing purposes:
[Greyscales.cpnx.gz](https://github.com/MegaMek/megamek/files/5743500/Greyscales.cpnx.gz)

**Comment by Windchild292** [comment]
Bugs
- [ ] Camo Selector Search
- [ ] Bot Colour Camo Assignment (issues on certain machines)
- [ ] Player Colour Duplicates
- [ ] Client Settings Colours don't load properly
- [ ] Null colour camouflage on load
- [ ] Null botforce colour on load

**Comment by Windchild292** [comment]
@SJuliez
I haven't managed to figure out why the camouflage search isn't working for colour camouflage. Do you have any ideas why that category doesn't work while the others do?

**Comment by Windchild292** [comment]
@SJuliez
I haven't managed to figure out why the camouflage search isn't working for colour camouflage. Do you have any ideas why that category doesn't work while the others do?

@gsparks3 
All issues outside of the search have been fixed

**Comment by Windchild292** [comment]
This PR is ready for final review.

There are two issues raised by this that I will complete in 0.49.X that are out of the scope of this PR. These are:
1. PlayerColour Selector Dialog. Currently player colours can only be changed by modifying them in the save file, while they should be able to be selected within MegaMek.
2. Name display override. This will allow camouflage to display as name overrides. This is to be implemented so that colour camouflage can be displayed as their proper name instead of their PlayerColour::name value.

Finally, I've determined that the search implementation will require significant underlying changes given the current use of the directory to add and filter categories. Therefore, I do not at this time think it is worth implementing the search for colour camouflage, especially given the limited list of colour camouflages available.

**Comment by sixlettervariables** [comment]
Does this have the fix for the odd colors on the movement overlays that @gsparks3 saw?

**Comment by gsparks3** [comment]
That was fixed along with other issues when I tested it (after Wind's post of "All issues outside of the search have been fixed").

File: megamek/src/megamek/server/Server.java [hunk 1]
```diff
@@ -1022,23 +1022,21 @@ private IPlayer addNewPlayer(int connId, String name) {
...
-        while (players.hasMoreElements() && (colorInd < PlayerColors.COLOR_NAMES.length)) {
+        final PlayerColour[] colours = PlayerColour.values();
+        while (players.hasMoreElements()) {
             final IPlayer p = players.nextElement();
             if (p.getId() == newPlayer.getId()) {
                 continue;
             }
-            if (p.getColorIndex() == colorInd) {
-                colorInd++;
+            if ((p.getColour() == colour) && (colours.length < (colour.ordinal() + 1))) {
```
Comment (sixlettervariables) [inline megamek/src/megamek/server/Server.java:1033]: Should this be equals?

File: megamek/src/megamek/server/Server.java [hunk 2]
```diff
@@ -1051,26 +1049,31 @@ private IPlayer addNewPlayer(int connId, String name) {
...
-            final IPlayer otherPlayer = i.nextElement();
-            if (otherPlayer.getId() != playerId) {
-                colorUsed[otherPlayer.getColorIndex()] = true;
+        if (player != null) {
+            // TODO : check for duplicate or reserved names
+
+            // Colour Assignment
+            final PlayerColour[] playerColours = PlayerColour.values();
+            boolean allUsed = true;
+            boolean[] colourUtilization = new boolean[playerColours.length];
```
Comment (sixlettervariables) [inline megamek/src/megamek/server/Server.java:1058]: Consider `Set<PlayerColour>`

**Review by sixlettervariables — COMMENTED** [review]
Few comments/questions.

File: megamek/src/megamek/server/Server.java (hunk 1 above)
Comment (Windchild292) [reply megamek/src/megamek/server/Server.java:1033]: No, but it should be greater than instead of less than

That's there to prevent an index out of bounds error.

File: megamek/src/megamek/client/ui/swing/dialog/imageChooser/CamoChooser.java [hunk 3]
```diff
@@ -19,49 +19,53 @@
...
-        this(null);
-    }
-
-    public CamoChooser(AbstractIcon icon) {
-        super(new CamoChooserTree(), icon);
+    public CamoChooser(@Nullable AbstractIcon ownerCamouflage, AbstractIcon individualCamouflage) {
+        super(null, individualCamouflage);
+        setOwnerCamouflage(ownerCamouflage);
+        setIndividualCamouflage(individualCamouflage);
+        refreshDirectory(new CamoChooserTree(hasIndividualCamouflage()));
```
[the remark this answers is not in the document]
Comment (Windchild292) [reply megamek/src/megamek/client/ui/swing/dialog/imageChooser/CamoChooser.java:44]: To fix the search and some other performance oddities I've found for it I'll need to do a significant rework of parts of the dialog, so I'll add it to that list for you

**Review by sixlettervariables — APPROVED** [review]
