### PR TITLE
Fix units getting stuck when jumping into water and getting hull down result

### LINKED ISSUE #705: [43.4] Unable to get up from 'hull down' in depth 1 water
[hulldownbug.sav.gz](https://github.com/MegaMek/megamek/files/1391204/hulldownbug.sav.gz)

No errors in the log. 

Select the "Hull down" Wasp and attempt to get up. He *should* be able to, having 6 walking MP, but he's not.

### PR DESCRIPTION
**Pull request by NickAragua**
Finally fixes #705 

When a unit goes hull down, it's set as 'hull down', but none of the other fall behaviors occur - including elevation adjustment for sinking to the bottom. This PR addresses the issue.

### CODE REVIEW

File: megamek/src/megamek/server/ServerHelper.java [hunk 1]
```diff
@@ -395,4 +395,22 @@ else if ((entity.heat >= 14) && !entity.isShutDown()) {
             vPhaseReport.addAll(s.destroyEntity(entity, "pilot death", true));
         }
     }
+    
+    /**
+     * Helper function that causes an entity to sink to the bottom of the water
+     * hex it's currently in.
+     */
+    public static void sinkToBottom(Entity entity) {
+        IHex fallHex = entity.getGame().getBoard().getHex(entity.getPosition());
```
Comment (sixlettervariables) [inline megamek/src/megamek/server/ServerHelper.java:404]: Based on our historical bug reports you should probably return early if entity or fallHex is null.

File: megamek/src/megamek/server/ServerHelper.java [hunk 2]
```diff
@@ -395,4 +395,22 @@ else if ((entity.heat >= 14) && !entity.isShutDown()) {
...
+        int waterDepth = 0;
+        
+        // we're going hull down, we still sink to the bottom if appropriate
+        if (fallHex.containsTerrain(Terrains.WATER)) {
+            // *Only* use this if there actually is water in the hex, otherwise
+            // we get ITerrain.LEVEL_NONE, i.e. Integer.minValue...
+            waterDepth = fallHex.terrainLevel(Terrains.WATER);
+        }
+        
+        entity.setElevation(-waterDepth);
```
Comment (sixlettervariables) [inline megamek/src/megamek/server/ServerHelper.java:414]: Is this always appropriate? Should they always be set to elevation 0 if not in water, or should this just be skipped?

Comment (NickAragua) [reply megamek/src/megamek/server/ServerHelper.java:414]: I think I better limit it to just in water, and also it occurs to me I forgot to check for the entity being on top of a bridge.

**Review by sixlettervariables — APPROVED** [review]
