### PR TITLE
fix: actually I fixed everything that there was to fix on the minimap

### LINKED ISSUE #6452: [Issue] - Minimap context menus no longer function after opening other menus.
### Brief Description *

The context menus on the mini map (right clicking on the mini map) no longer works once the command view menu is invoked.   Navigating to zoom in or out using the context menu does not cause the mini map to zoom in our out.  Also, the other context menus to show height and toggle symbols do not function.  (The mini map context menus may work correctly initially if no other menu items are invoked beforehand.)

### 3. Steps to Reproduce

Start a new game (any setup)
Open the mini map.
Right click to open the context menus - click on the context menu options to zoom in or out.

### Attach Files

Image

### Severity *

Low - there are alternate ways other than the mini map context menu to zoom in and configure the map.  This is a long standing bug.

### MegaMek Suite Version *

0.50.03-Snapshot (1/27)  Build Date: 2025-01-27T19:29:38.197653200 

### Operating System *

 Platform: Windows 11 10.0 (amd64)

### Java Version *

Java Vendor: Eclipse Adoptium     Java Version: 17.0.11

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### LINKED ISSUE #6455: [0.50.03 - CI1750 Nightly (MHQ Packaged)] Minimap Level Numbers Slightly Offset
### Brief Description *

Image

See screenshot above.

When enabling the new minimap level numbers feature, the numbers are offset to the bottom right of the mini-hexes. This can make it hard to read as they overlap with the next hex along.

Ideally the numbers would be central to their parent hex.

### 3. Steps to Reproduce

1. Load any map with different terrain levels
2. Set minimap to show level numbers
3. Numbers are offset

### Attach Files

No save/relevant logs.

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don't affect gameplay and occur rarely.

### MegaMek Suite Version *

0.50.03 - CI1750 Nightly (MekHQ Packaged)

### Operating System *

Win 11

### Java Version *

17

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### LINKED ISSUE #6534: [0.50.04-SNAPSHOT] Minimap Symbols menu items don't work if part of the right click dialog is past the edge of the minimap
### Brief Description *

When right clicking on the minimap, if the final section (such as under Symbols) is off the edge of the minimap, clicking the menu item has no effect.

The cutoff seems to be where the checkbox is displayed on the menu item - if the checkbox is above the minimap, it works. if the checkbox is past the edge of the minimap, it doesn't work.

Minimap size/zoom level has no effect, the cutoff point seems to stay with the checkbox. Examples below.

Possibly related to other minimap bug https://github.com/MegaMek/megamek/issues/6452

Works:

Image

Doesn't work:

Image

Works:

Image

Doesn't work:

Image

### 3. Steps to Reproduce

Right click on minimap in the locations shown in the above screenshots

### Attach Files

[MinimapBorked.sav.gz](https://github.com/user-attachments/files/18756908/MinimapBorked.sav.gz)

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don't affect gameplay and occur rarely.

### MegaMek Suite Version *

0.50.04-SNAPSHOT     Build Date: 2025-02-10T03:22:46.100422574

### Operating System *

Windows 10

### Java Version *

Java Vendor: Eclipse Adoptium     Java Version: 17.0.6

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by Scoppio**
# What it does?

Implements the same algorithm to draw the text on the coordinates that is used by the "drawUnit" when it wants to draw things like the sensor ping.

It also fixes a bunch of bugs related to the minimap not responding anymore. I moved a few functions around and things started to work, I won't complain.

- closes #6455
- closes #6452
- closes #6534

### CODE REVIEW

File: megamek/src/megamek/client/ui/swing/minimap/Minimap.java [hunk 1]
```diff
@@ -405,11 +405,13 @@ public void gameNewAction(GameNewActionEvent e) {
...
-            dialog.addMouseWheelListener(mouseWheelListener);
-            dialog.addComponentListener(componentListener);
-            dialog.addComponentListener(componentListener);
+            if (dialog.getMouseListeners().length == 0) {
+                dialog.addMouseListener(mouseListener);
+                dialog.addMouseMotionListener(mouseMotionListener);
+                dialog.addMouseWheelListener(mouseWheelListener);
+                dialog.addComponentListener(componentListener);
+                dialog.addComponentListener(componentListener);
+            }
```
Comment (Scoppio) [inline megamek/src/megamek/client/ui/swing/minimap/Minimap.java:414]: avoid initializing the same dialog twice.

File: megamek/src/megamek/client/ui/swing/minimap/Minimap.java [hunk 2]
```diff
@@ -997,11 +999,15 @@ private void paintHeight(Graphics g, Hex h, int x, int y) {
...
+            String sHeight = height + "";
+            int baseX = coordsXToPixel(x);
+            int baseY = coordsYtoPixel(y, x);
+            Font font = new Font(MMConstants.FONT_SANS_SERIF, Font.PLAIN, FONT_SIZE[zoom]);
+            int fontWidth = getFontMetrics(font).stringWidth(sHeight) / 2;
+            int fontHeight = getFontMetrics(font).getHeight() / 3;
+            g.setFont(font);
             g.setColor(Color.white);
-            g.drawString(sHeight, baseX + 5, baseY + 5);
+            g.drawString(sHeight, baseX - fontWidth, baseY + fontHeight); // + (fontHeight / 2));
```
Comment (psikomonkie) [inline megamek/src/megamek/client/ui/swing/minimap/Minimap.java:1010]: Commented out code?

**Review by psikomonkie — APPROVED** [review]
Nice!

File: megamek/src/megamek/client/ui/swing/minimap/Minimap.java (hunk 2 above)
Comment (Scoppio) [reply megamek/src/megamek/client/ui/swing/minimap/Minimap.java]: what are you talking about? there is no comment.... (amended and force pushed, thanks)

**Review by SJuliez — APPROVED** [review]
