### PR TITLE
Fix for 7465: Allow null movePath objects in entity updates

### LINKED ISSUE #7465: [v0.50.07-nightly-2025-10-04] Hang on preparing for movement phase
### Brief Description *

Was playing an engagement, game suddenly hung on preparing for movement phase after the game had progressed. 
Several units of mine had already withdrawn from the board, in case that matters. 
Quicksaving and reloading had the issue persists, requiring to to go back to an earlier autosave. 

I suspect the following errors were related to the hang:

```
01:40:14,478 ERROR [megamek.client.AbstractClient] {AWT-EventQueue-0}
megamek.client.AbstractClient.handlePacket(AbstractClient.java:406) - Unknown PacketCommand of ENTITY_UPDATE

01:40:18,339 ERROR [megamek.client.Client] {AWT-EventQueue-0}
megamek.client.Client.handleGameSpecificPacket(Client.java:1191) - Invalid packet data:
megamek.common.net.packets.InvalidPacketDataException: Value at index 2 not Vector: Null object (Unknown)
	at megamek.common.net.packets.Packet.getUnitLocationVector(Packet.java:1101)
	at megamek.client.Client.receiveEntityUpdate(Client.java:598)
	at megamek.client.bot.princess.Princess.receiveEntityUpdate(Princess.java:3800)
	at megamek.client.Client.handleGameSpecificPacket(Client.java:929)
	at megamek.client.AbstractClient.handlePacket(AbstractClient.java:403)
	at megamek.client.bot.princess.Princess.handlePacket(Princess.java:3094)
	at megamek.client.AbstractClient$1.lambda$packetReceived$0(AbstractClient.java:592)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### 3. Steps to Reproduce

_No response_

### Attach Files

[unified_log.zip](https://github.com/user-attachments/files/22714089/unified_log.zip)

[quicksave.sav.gz](https://github.com/user-attachments/files/22714093/quicksave.sav.gz)

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### MegaMek Suite Version *

v0.50.07-nightly-2025-10-04

### Operating System *

Windows 11 Home Version 10.0.26100 Build 26100

### Java Version *

21.0.3

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by Sleet01**
Patch to prevent null movePath values from raising exceptions during entity updates.
It's unclear why we would send a null movePath instead of an empty path (although I suspect Double Blind is at fault).
I was also not able to repro the original error seen by the OP, though their save game does show the effects.
At any rate, until this issue is better understood we need to allow null values to be returned in this case.

Testing:
- Ran all 3 projects' unit tests.
- Attempted repros but was unable to capture the exact issue.

Close #7465

### CODE REVIEW

File: megamek/src/megamek/common/net/packets/Packet.java [hunk 1]
```diff
@@ -1089,6 +1089,10 @@ public Vector<UnitLocation> getUnitLocationVector(int index) throws InvalidPacke
 
         Vector<UnitLocation> result = new Vector<>();
 
+        // In some instances we may get a null entry; this is valid and handled in Game
+        if (object == null) {
+            return null;
+        }
```
Comment (IllianiBird) [inline megamek/src/megamek/common/net/packets/Packet.java:1095]: Is there value in printing a trace to log, so we can get an idea where these `null` values are coming from? Or do you not think that would give us any more information than we already have?

Can I also confirm that we're handling null returns from this method wherever it's being called?

Finally, can we add `@Nullable` to the method signature if we're going to have it return `null` under normal circumstances.

**Review by IllianiBird — APPROVED** [review]
This PR is fine as is, but I've left a review comment highlighting some stuff that might be worth looking into and one minor requested change.

Marking as 'approved', but if we can slip in a `@Nullable` before merging that'd be 10/10.

File: megamek/src/megamek/common/net/packets/Packet.java (hunk 1 above)
Comment (Sleet01) [reply megamek/src/megamek/common/net/packets/Packet.java:1095]: 1. The problem is that we don't really know who sends various packets out, and it is possible that we'll handle packets asynchronously (which, now that I think about it, is also an issue).
If we were going to add logging for Entity Updates with null move paths, we would want to add it on the packet create side.
I believe I understand the mechanism at play better now and I think it's working as intended (if kind of hacky).
This is actually a "bug" we created by tightening restrictions on Packet data.

2. I traced the various callers and they all pass the null to code that knows what to do with it.  It would have been nice if that were indicated somehow in the intermediate functions but I'm satisfied it's safe to pass the null around.

3. Sure thing.
