### PR TITLE
Fix: Fixed Quad-Vees Taking PSRs and Falling While in Vehicle Mode

### LINKED ISSUE #6825: Quadvee in tracked mode, can take PSR, and fail
### Brief Description *

Quadvee in tracked mode, can take PSR, and fail. 

Quadvee converted to "Vehicle Mode"
While in Vehicle mode, Quadvee took > 20 damage, and ran a check for PSR. 
This is not hte same as 6441 where a prone Quadvee can take a PSR and fail. 

### 3. Steps to Reproduce

Be Quadvee in tracked mode. 
Take 20 damage
PSR Check runs
Able to fail PSR, fall, and take damage. 

### Attach Files

Image

[megamek.log](https://github.com/user-attachments/files/19596725/megamek.log)

Image

Image

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### MegaMek Suite Version *

MegaMek v0.50.04

### Operating System *

Windows 11 10.0 (amd64)

### Java Version *

17.0.13

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
Fix #6825

### Dev Notes
Our earlier attempt to fix the quad-vee PSR issue introduced a new one.

Basically, we had added a check that unintentionally allowed PSRs so long as the quad-vee wasn't prone. This shortcut the other checks that ensured this was only checked if the quad-vee was eligible for falling checks.

### CODE REVIEW

File: megamek/src/megamek/common/QuadVee.java [hunk 1]
```diff
@@ -1,20 +1,34 @@
...
+ * of The Topps Company, Inc. All Rights Reserved.
+ *
+ * Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
+ * InMediaRes Productions, LLC.
+ *
+ * MechWarrior Copyright Microsoft Corporation. <Package Name> was created under
+ * Microsoft's "Game Content Usage Rules"
+ * <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
+ * affiliated with Microsoft.
  */
```
Comment (rjhancock) [inline megamek/src/megamek/common/QuadVee.java:32]: Don't forget to update the `<Package Name`> entries as well.

**Review by rjhancock — CHANGES_REQUESTED** [review]
Copyright fixes.

File: megamek/src/megamek/common/QuadVee.java [hunk 2]
```diff
@@ -1,20 +1,34 @@
 /*
- * Copyright (c) 2022 - The MegaMek Team. All Rights Reserved.
+ * Copyright (c) 2022-2025 - The MegaMek Team. All Rights Reserved.
  *
- * This file is part of MegaMek.
+ * This file is part of <Package Name>.
```
Comment (Scoppio) [inline megamek/src/megamek/common/QuadVee.java:4]:
```suggestion
 * This file is part of MegaMek.
```

File: megamek/src/megamek/common/QuadVee.java [hunk 3]
```diff
@@ -1,20 +1,34 @@
...
  *
- * MegaMek is free software: you can redistribute it and/or modify
- * it under the terms of the GNU General Public License as published by
- * the Free Software Foundation, either version 3 of the License, or
- * (at your option) any later version.
+ * <Package Name> is free software: you can redistribute it and/or modify
```
Comment (Scoppio) [inline megamek/src/megamek/common/QuadVee.java:6]:
```suggestion
 * MegaMek is free software: you can redistribute it and/or modify
```

File: megamek/src/megamek/common/QuadVee.java [hunk 4]
```diff
@@ -1,20 +1,34 @@
...
+ * it under the terms of the GNU General Public License (GPL),
+ * version 3 or (at your option) any later version,
+ * as published by the Free Software Foundation.
  *
- * MegaMek is distributed in the hope that it will be useful,
- * but WITHOUT ANY WARRANTY; without even the implied warranty of
- * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
- * GNU General Public License for more details.
+ * <Package Name> is distributed in the hope that it will be useful,
```
Comment (Scoppio) [inline megamek/src/megamek/common/QuadVee.java:11]:
```suggestion
 * MegaMek is distributed in the hope that it will be useful,
```

**Review by rjhancock — APPROVED** [review]
