### PR TITLE
Fix: #6967 Battlemech Shields are non-functional

### LINKED ISSUE #6967: Battlemech Shields are non-functional
### Brief Description *

Since v 0.50.04 battlemech shields have stopped functioning. Setting the shields to passive or active (or even direct hits to the arm which it is installed on) does not reduce the damage of hits.

### 3. Steps to Reproduce

1. Deploy any 'mech with a shield.
2. Get shot at.

### Attach Files

I have attached a file with an atlas III with 2 shields vs an akuma. Should be easy to reproduce with it.

[Shields.sav.gz](https://github.com/user-attachments/files/20006808/Shields.sav.gz)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MegaMek Suite Version *

0.50.05

### Operating System *

Windows 11

### Java Version *

Eclipse Adoptium 17.0.15

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by psikomonkie**
Fixes #6967 

Shields should require the equipment to be operable, not inoperable

### CODE REVIEW

File: megamek/src/megamek/common/MekWithArms.java [hunk 1]
```diff
@@ -85,7 +85,7 @@ public boolean hasShield() {
             MiscType type = m.getType();
             if (((m.getLocation() == Mek.LOC_LARM) || (m.getLocation() == Mek.LOC_RARM))
                 && type.isShield()
-                && m.isInoperable()
+                && !m.isInoperable()
```
Comment (Scoppio) [inline megamek/src/megamek/common/MekWithArms.java:88]: <3
I was looking at this error and forgot to set myself as assignee, happy you found the fix quickly! 👍🏼

**Review by Scoppio — APPROVED** [review]
quick catch!

File: megamek/src/megamek/common/MekWithArms.java (hunk 1 above)
Comment (psikomonkie) [reply megamek/src/megamek/common/MekWithArms.java:88]: I was just casually looking into it; I assigned it to myself once I found the issue ;) might as well finish it at that point, right?
