### PR TITLE
fix NPE when attempting to roll initiative for player with no units

### LINKED ISSUE #2115: 0.47.7 MekHQ-MegaMek Princess halting during move, NPE
### Environment
Version: 0.47.7
MekHQ integrated MegaMek
Windows 10
Java version 1.8.0_261

### Description
Princess locked up while attempting to move (possibly related to ejected Mechwarrior in water being the active unit?). Kicked and replaced bot, immediately locked up again, at which point I started taking logs and screenshots, etc. Uncertain if previous freeze was identical, but it shows two of the same NPE in MekHQlog.txt, while megameklog.txt does not have anything immediately obvious to me. Included both anyway. 
image

Edit: after testing, issue reproduces  after save/quit/load and replacing all bots. Kicking the Lyran Commonwealth bot, skipping a single turn, then replacing the bot resolves the issue (at least temporarily), so it does seem linked to that specific unit. 

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/5031483/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/5031495/mekhqlog.txt)
[princessNPE.sav.gz](https://github.com/MegaMek/megamek/files/5031493/princessNPE.sav.gz)

Player name: Coppercoats

### PR DESCRIPTION
**Pull request by NickAragua**
This prevents an NPE when attempting to roll individual initiative for units belonging to a player that isn't in the game? I'm not really sure how it got into this state. 

Fixes #2115 , the second issue (first one was already fixed)

### CODE REVIEW

File: megamek/src/megamek/common/Player.java [hunk 1]
```diff
@@ -525,6 +525,11 @@ public int getTurnInitBonus() {
     @Override
     public int getCommandBonus() {
         int commandb = 0;
+        
+        if(game == null) {
```
Comment (Windchild292) [inline megamek/src/megamek/common/Player.java:529]:
```suggestion
        if (game == null) {
```
