### PR TITLE
Lobby/GUI work

### LINKED ISSUE #322: GM/host-specific Powers: ignore Blind Drop (and possibly Double Blind) rules
As an impartial GM, currently it is difficult to ensure a fair match between multiple players when Blind Drop rules are enacted.  As it stands right now, Blind Drop only really works when the "honor code" between players applies, but even then players make mistakes and it would be helpful if the GM/host could double check people's force loadouts.  To a lesser extent, this also applies to Double Blind rules as well, but I've been told the /seeall command resolves this.

Can I suggest a toggle option that disables Blind Drop rules for the host of the game lobby?  That way GMs can easily ascertain that everyone has their forces setup correctly without giving away valuable intel to the players.

I think this will have a large and positive impact on both exhibition and campaign missions.

### LINKED ISSUE #448: Sort Units in Lobby by Name/BV/Tonnage/etc...
http://bg.battletech.com/forums/index.php?topic=55804.msg1283982#msg1283982

Yer really killing me Smalls. You and Hammer both asked for ideas on the first page of the thread. 

Anyways, pretty self explanatory, the ability to sort units in the lobby view panel by Type/BV/Tonnage/Name.

### LINKED ISSUE #765: [0.43.2-git : Bug] Board Too Big For Preview in Lobby
When the board is too big, only part of the board will be shown in the preview. Would it be possible for click and drag?

### LINKED ISSUE #1996: RFE - Be able to change order of units in lobby/unit list
Suggestion seen on Discord ...

"is there a way to sort the unit list in the lobby?"

As I understand it, units in the lobby, and in the unit list, are sorted in order of the Unit ID, and thus in the order that they are added.

Suggestion - addition of a 'Sort Order' variable, allowing units to be re-ordered in the lobby, and thus in the unit list (and default order they are offered up for deployment and activation).

### LINKED ISSUE #2277: Add unofficial option to give every mech and vehicle a free searchlight for night missions if they don't have one already.
It would simplify night combat a little if Megamek could give searchlights to all of your units as an unofficial rule. This would simply automate the process of adding lights to all of your units through meklab when playing ATB. The construction rules say "combat vehicles and 'Mechs may have a larger mounted searchlight at no cost in weight, slots or C-Bills" so in effect all this does is give mechs and vees the searchlight quirk for free. The searchlight would be mounted in the CT or FR facing forward, which iirc only matters in checks that determine when the searchlight is destroyed by enemy fire.

### LINKED ISSUE #2306: [RFE] Option to change the font size of tooltip items such as Weapons, Heat etc.
The ability to change font sizes for entries on the tooltip would be advantageous to players with high resolution displays. Weapon entries being a key issue here. The option to change font color would also be useful to many that have a harder time reading certain colors.

### LINKED ISSUE #2322: Include warnings if weather conditions will prohibit deployment
Its possible to end up with units in the MegaMek lobby that are destroyed immediately on deployment due to weather conditions such as extreme temperatures. wind, or vacuum.  These units must be removed at deployment if this is missed in the lobby.  This can happen from missing the nuances of the large variety of weather effects, as well as units deployed from a MekHQ campaign.

Please add an indicator in the lobby to show two conditions: 
- unit cannot be deployed due to fixed or minimum variable wind speed, extreme temperature, or atmospheric pressure
- unit may be destroyed due to maximum variable wind speed

This can be another column in the unit list, such as "Weather conditions" showing OK/Warning/Prohibited.  Or a change in the tile background color, such as orange (warning) or red (prohibited).

Also include a 'nag dialog' when the Done button is pressed, if there are units are still present which can be destroyed by weather conditions.

### LINKED ISSUE #2327: 0.47.11 Further unit tooltip character problems
### Environment
0.47.11 - applies _differently_ to standalone MegaMek and MekHQ MegaMek
Windows 10
Java version 11.0.8

### Description
Despite the changes from #2292, some issues still exist with tooltip characters. In fact, some new issues have appeared. 
In the standalone MegaMek, the issue is minimal, effectively nonexistent - in the Client Settings (Advanced) window, for all Flat themes, the new armor/IS/destroyed component characters still do not display properly (as in #2240). This is not critical, because when actually in-game, these display properly (see below, using Flat Darcula theme). 

image

As a separate, mostly irrelevant issue, the weapon tooltips in the MegaMek lobby don't use the same formatting as the actual in-game tooltips currently do after #2292 (see below, and compare with above) - apparently this code is not unified, despite being activated by the same Client Setting. This applies to both the integrated and non-integrated MM, but doesn't necessarily need to be fixed. 
image

However, in the MekHQ integrated Megamek, the Theme that applies is the Theme chosen in MekHQ->File->Themes (overriding the Client Settings in the integrated MM). This seems to cause issues _if and only if_ MekHQ was _opened_ with a Flat theme loaded. If it was opened with another theme loaded, and then _switched_ to a Flat theme while still open, the issue does _not_ appear, which can give false negatives on initial testing. 

Reproduction steps:
1. Download and extract a fresh copy of MekHQ v47.11 (to ensure default settings)
2. Open the attached campaign save with MekHQ. Note that the MekHQ Theme is Metal by default. 
3. Go to the Briefing Room and Start Game on the active Stand Up (Defender) scenario. 
4. In the lobby, open View->Client Settings and activate "Show unit weapons in tooltip" and "Show mini armor visualization in tooltip". 
5. Hit "I'm Done", start the game, choose a location and Deploy your first unit. Hover over the unit to view the tooltip. Tooltip should be properly rendered (as below). 
image
6. Close out of the integrated MegaMek client (don't save the game), return to MekHQ, and change the Theme to Flat Dark (or any other Flat theme). 
7. Repeat steps 3, 5, and 6 as desired to test multiple themes. All themes should produce properly rendered tooltips.
8. _With MekHQ set to a Flat theme_ (I use Flat Darcula), close MekHQ, then reload the same campaign and repeat steps 3, 5, and 6 as desired. 
9. Note that both the Weapon and Armor tooltips now contain characters that fail to render (see below). If switched to a non-Flat theme, characters will properly render, but switching back to a Flat theme will cause them to once again fail to render. 
image

Exactly how this issue should be fixed is up to the developers. As a workaround, always switching MekHQ to Metal (or another non-Flat theme) before closing it will prevent the issue from occurring (if forgotten by accident, switching the theme and then reloading MekHQ will re-resolve the issue). The Armor/IS/Destroyed Component characters can also be changed in the Client Settings by the user, as an alternate workaround, but the characters used in the Weapon Tooltip cannot. 

### Files
Saved MekHQ campaign with a fight ready for testing purposes:
[Coppercoats.cpnx.gz](https://github.com/MegaMek/megamek/files/5355851/Coppercoats.cpnx.gz)

### LINKED ISSUE #2340: Adding searchlights to Princess units only works in Configure dialog
In 47.11, and at least as far back as 47.7, using the right-click context menu to add searchlights in the lobby doesn't work properly with Princess units (haven't checked the old TestBot).  It shows in the toggle on the Configuration dialog, but the feedback "Unit BlahBlah has been customized" doesn't appear and the unit is not equipped with a searchlight when the game starts.

To reproduce:
In the lobby, add a Princess bot.  Or start a session from MekHQ with a bot opponent.

Under Set Map, set Planetary conditions to "Full Moon Night" or darker.

Add units to the human player, and select Equipment > Add searchlight(s).  Note the feedback on unit has been customized.

Add several units to the Princess player.

Right click on all Princess units and use the same method to add searchlights.  Note the lack of feedback.

Select one individual Princess unit and bring up the Configure dialog.  Note the "Has searchlight?" toggle is checked.  Toggle this off, then back on again.  Click OK to close the dialog.  Feedback on unit has been customized is present.

Start the game.  Kick the Princess player and replace with a human.  Units that did NOT have the searchlight added through the Configure dialog do not have searchlights to turn on/off or target enemy units.
Princess add searchlight
Princess add searchlight - toggle

### LINKED ISSUE #2374: RFE - Option to disable Save Before Quit Message
Currently, MegaMek asks me if I would like to save the game before exiting, regardless of whether I am in a game, or in the lobby. I wish to be able to disable this message, either via checkbox on the message, or via Client Settings

### LINKED ISSUE #2384: RFE - Searchlights per Tech Manual (Borderline Unofficial Rule)
Night fighting is one of the biggest pains with the TableTop Rules as written. Techmanual pg 237 describes the construction rules as 

_All units except for Combat Vehicles and BattleMechs are presumed to incorporate at least 3 hand-held searchlights
as part of their design (2 Front and 1 Rear) to reflect running lights, headlamps and taillights—though some vehicles may designate these as strobes for emergency and police vehicle units or warning beacons. BattleMechs and Combat Vehicles may instead mount one mounted searchlight at the designer’s option, at no cost in weight, slots, or C-bills. Over and above these “free” lights, additional searchlights may be mounted on all units in accordance with standard core construction rules._

Given the lights are no cost I can't see a reason why every unit wouldn't have them per the above description. This would give every unit at least one, with an option to purchase more.

### LINKED ISSUE #2385: Search Light Issues
Watching Casual Jokers stream tonight they had some weirdness with search lights. I've tried to recreate the issues with

1) If you add the mech to the lobby and use the right click equipment add searchlights, they aren't added to the unit, or if they are they don't work in game. If added as a quirk they work fine.

2) If you turn on Searchlights some times you don't get the hexes illuminated on the map till you hit fire. Wouldn't it make sense to have the hexes illuminate to the target when you select it as a target. 

image

### Environment
What version of MegaMek does your issue apply to?  Megamek 47.12-SNAPSHOT from MekHQ running from Repo.
What operating system are you using?  Windows
What java version are you using?  Java 11

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/5505876/megameklog.txt)
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/5505878/autosave.sav.gz)

### LINKED ISSUE #2428: [RFE] [UI] Remember Select Unit window parameters/Change default parameters
### Environment
0.47.14
Windows 7

### Description
I would like to request that the Select Unit popup window remember the size of the window and the width of the chassis/model/weight/etc columns. 
It would also be nice if the size of unit summary and unit selection windows as part of the overall Select Unit window was remembered.

For instance, in this image I have my ideal setup. It gives me plenty of room in all columns to read what that value is, and the summary window is large enough to show off all the stats and image.
ideal window

But after selecting a unit, when going back to the Select Unit window it returns to its default settings. This cuts off information in the summary window, and the width of the chassis and model names are too small for a bunch of units.
default window

It would be best if the scaling, position, size, and column widths of the Select Unit window were remembered between uses, or at least a way to save those parameters so that they become the default.

### LINKED ISSUE #2560: Cannot select boards on servers if they are not local
### Environment
What version of MegaMek does your issue apply to?  0.47.16
What operating system are you using?  Windows, Mac, or Linux.
What java version are you using?  Java 11

### Description
Attempting to select a board on a server that isn't local:
```
21:13:34,446 ERROR [megamek.common.Board] {AWT-EventQueue-0} 
load(), line 931 : IO Error opening file to load board! java.io.FileNotFoundException: data\boards\unofficial\JimBoards\FreeWolves_League1.board (The system cannot find the path specified)

Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: board is the wrong size, expected 40x20, got 0x0
	at megamek.common.util.BoardUtilities.combine(BoardUtilities.java:85)
	at megamek.client.ui.swing.ChatLounge.previewGameBoard(ChatLounge.java:1150)
	at megamek.client.ui.swing.ChatLounge.actionPerformed(ChatLounge.java:2804)
```

### Files
image

### LINKED ISSUE #2657: RPE - Starting Heat
Is it possible to change in the Lobby the starting heat levels of Mechs for scenarios?

### PR DESCRIPTION
**Pull request by SJuliez**
OK I'm finishing this now (tentatively) to at least start the process of integrating it.

I have no clue why the Messages call in the Boardvalidator fails.

Main Changes (omitting small bug fixes in the tooltip and elsewhere):
- Unifies the tooltip in the lobby and game (while still enabling different views, e.g. the pilot info can be omitted as is done in the lobby mek table) and moves the code out of Entity; the tooltip now shows a different symbol for capital armor. I've introduced many unicode symbols, these require the Java "Dialog" logic font, I hope they work on other systems besides Win10 as well. 
- Adds a general gui scaling float value (neutral value = 1) that is accessible in the Client Settings and, unless a modal dialog is up, with Ctrl+Numpad+ and Ctrl+Numpad- . This currently scales mainly the lobby and some dialogs in the lobby that have been revamped. The scaling can be applied by calling UIUtil.adjustDialog on any dialog, but the result depends on how complicated the dialog is and its probably better to adjust manually. I've done this with the host game dialog and the result is I guess ok.
- Completely revamps the info in the lobby mektable, obviously. I've tried using colors that are desaturated in the hope this will make the colors readable for everyone. Also, the main colors come from methods that return different colors based on whether the current UI theme is light or dark.
- Allows sorting the mek table by various algorithms
- Generally shows more info directly in the table such as velocity, height, deployment, partial repairs, C3 info. I've tried to hide stuff thats unnecessary such as height in space and so on to make it all kinda useful
- The lobby now shows if a unit has a problem such as instant death upon deployment or an unconnected C3 computer; the tooltip gives details on the problem (unit cannot survive in vacuum)
- Makes the compact mode more useful; it now shows alomst the same info as the full mode.
- Revamps the popup menu; it now allows some more unit settings such as C3 configuration and most operations work on multiple units
- Adds toggles to hide unofficial and legacy game options; also adds a ToggleButton that has a checkmark or cross as the normal Java togglebuttons dont show their status really well
- Adds searchlights automatically to all units in circumstances when they're needed
- Revamps the player config and planetary settings dialog
- Revamps the player table; it now allows multi-selection and direct setting of team and deployment via popup, also shows local bots with a symbol
- Makes some dialogs rememeber their size and position such as the Unit selector and force generator
- Adds Ctrl-S quicksave and Ctrl-L quickload. I think this is only useful for development. Ctrl-L works only from the main menu I think.
- The mektable generally remembers column sizes
- removes some buttons from the main interface (such as Delete All) and adds a confirm dialog to delete and various other things that shouldnt be insta-kill
- Minefields now actually require the TacOps minefields game option to be active
- Corrects conventional fighter weight classes, use the same as ASF (50t = medium)
- Corrects legal deployment with double blind
- Obviously revamps board selection to graphical dragndrop. It can deal with server-side boards (although in this case it can't actually display the real board, just an empty placeholder) and invalid boards. 
- Instead of choosing a board at random, the surprise function will now choose a board from a list of boards that can be assigned by selecting the desired boards and dragging them to the preview.
- Board setups can now be saved. I've created some examples from the boards we have
- Adds a smaller minimap zoom that I neede for those huge maps and a better space minimap with stars...
- Adds a team overview pane. The table can be detached to a window. It shows the summarized strength of the teams and when one team is selected in the table it shows the relative values (87% of ...)
- Adds ammo to the unit tooltips
- Adds forces to MM and a force tree view to the lobby. Forces currently have no ingame effect. The game has a Forces object that controls the individual Force objects. The structure is similar to MekHQ's forces although I believe MekHQ has no owner field. Forces can be saved to MUL files and load from there correctly. However it only saves the full force every unit is in, not the forces themselves. When loading a MUL, the force structure is reconstructed from these individual force entries. Therefore, loading from a MUL will always create new forces, never integrate into existing ones. The forces from MekHQ can be transported to MM by using the String representation as Ive done in the MekHQ PR. The MekHQ PR is not required for this PR; it can be pulled later when MM actually works.
- Units in forces and subforces can be moved up and down by Ctrl-Up and Ctrol-Down; no multi-selection.
- The mek table and force table allow Ctrl-C to copy selected units (forces are ignored). It exports the unit, tonnage, pilot and a few values and pastes mostly well into Excel, although some units have secondary names that dont paste well such as "(3025)" which arrives as -3025 in Excel. Ive found no solution for this that also allows pasting into MM well. 
- Obviously, the mektable and force table also allow Ctrl-V. So it's easy to copy-paste units in MM. 
- Also, makes the keybinds overlay disappear in the map preview

Resolves #2384 
Resolves #2385 
Resolves #2340 
Resolves #2327 
Resolves #2322 
Resolves #2306 
Resolves #2277 
Resolves #2428 
Resolves #1996
Resolves #448 
Resolves #2560 
Resolves #765 
Resolves #2657 
Resolves #2374

I believe this also resolves #322. It does not enable a GM player to see all units during blind drop, but the team overview allows a cost/tonnage/BV comparison through all blind drop options.

image

### CODE REVIEW

**Comment by HammerGS** [comment]
This looks great. One first impression from the screen shot, I think the unit ID would better after the unit name.

**Comment by SJuliez** [comment]
Thanks. Note that on the left side theres a toggle button for the unit ID,  so it's easily turned off and on (took this from the CasualJoker vids) and the unit name can be very (very) long. I can try this though.

**Comment by HammerGS** [comment]
Curious would this one fit into the last of UI stuff - https://github.com/MegaMek/megamek/issues/2183

**Comment by sixlettervariables** [comment]
CI is failing because the source compatibility level is 8 and you have some >8 Java-isms.

**Comment by HammerGS** [comment]
Wanted to have a look. But looks like it has conflicts.

```
Auto-merging megamek/src/megamek/server/Server.java
Auto-merging megamek/src/megamek/common/Game.java
Auto-merging megamek/src/megamek/common/Entity.java
Auto-merging megamek/src/megamek/client/ui/swing/gameConnectionDialogs/HostDialog.java
Auto-merging megamek/src/megamek/client/ui/swing/gameConnectionDialogs/ConnectDialog.java
Auto-merging megamek/src/megamek/client/ui/swing/dialog/MegaMekUnitSelectorDialog.java
Auto-merging megamek/src/megamek/client/ui/swing/dialog/AbstractUnitSelectorDialog.java
Auto-merging megamek/src/megamek/client/ui/swing/boardview/BoardView1.java
Auto-merging megamek/src/megamek/client/ui/swing/MegaMekGUI.java
Removing megamek/src/megamek/client/ui/swing/MechGroupView.java
Auto-merging megamek/src/megamek/client/ui/swing/GUIPreferences.java
Auto-merging megamek/src/megamek/client/ui/swing/FiringDisplay.java
Auto-merging megamek/src/megamek/client/ui/swing/EquipChoicePanel.java
Auto-merging megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
Auto-merging megamek/src/megamek/client/ui/swing/ClientGUI.java
CONFLICT (modify/delete): megamek/src/megamek/client/ui/swing/ChatLounge.java deleted in 4f5175175a282f66f2e6f36300bcf038899dfd36 and modified in HEAD. Version HEAD of megamek/src/megamek/client/ui/swing/ChatLounge.java left in tree.
Auto-merging megamek/src/megamek/client/bot/princess/Princess.java
Auto-merging megamek/i18n/megamek/client/messages.properties
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by SJuliez** [comment]
Hopefully better now. Not many changes, I struggled with the mektable popup and most of the changes there are not so visible. It'll only show certain load options when a unit type is present, like fighter squadrons. Squadrons require Capital Fighters (which Im not sure is really what the rules meant to say...). Something visible is the player config dialog. To get the most out of it, activate minefields (this option now really toggles minefields in the lobby) and double blind with exlcusive deployment and open it for a bot client.

**Comment by HammerGS** [comment]
Thanks, really looking forward to see this done. More I use it the harder it is to go back to the old lobby.

**Comment by HammerGS** [comment]
Loving the improvement but think I got a bug.  Running from repo, add a unit to the lobby. Right click and select view. Nothing happens.  Log has the following error.

```
Action! javax.swing.JButton[,6,22,380x33,alignmentX=0.0,alignmentY=0.5,border=com.formdev.flatlaf.ui.FlatButtonBorder@1539f6af,flags=288,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=javax.swing.plaf.InsetsUIResource[top=2,left=14,bottom=2,right=14],paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=true,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=Add A Combat Unit...,defaultCapable=true]
Action! javax.swing.JButton[,183,5,137x29,alignmentX=0.0,alignmentY=0.5,border=com.formdev.flatlaf.ui.FlatButtonBorder@1539f6af,flags=288,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=javax.swing.plaf.InsetsUIResource[top=2,left=14,bottom=2,right=14],paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=true,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=Game Options...,defaultCapable=true]
[Fatal Error] log4j.xml:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
```

**Comment by SJuliez** [comment]
Thanks! found it ... I wanted to check if exactly one unit is selected and instead checked if zero units are selected.

**Comment by HammerGS** [comment]
Huge improvement on the planet dialog. One cool thing would be to pull the image used from MekHQ and the planet they are on if available :) 

Also showed a preview on the Casual Jokers Stream lots of kudos.

**Comment by HammerGS** [comment]
That update to the map selector is AMAZING?  Is there any way to add the name to them? Under the map maybe?

**Comment by SJuliez** [comment]
Sure, I'll take a look. The names can be awfully long though, so some of them will be cut off.

**Comment by HammerGS** [comment]
Finding something odd with the map selector. It does consistently select a map. Nothing in the log but will try and duplicate it. It's also not clear to drag and drop the map, and double click doesn't seem to do anything.

**Comment by HammerGS** [comment]
Another suggestion for the map selector. Since we have the search, could we have an "all maps" added to the map size.

**Comment by SJuliez** [comment]
> It does consistently select a map.
Im not sure what you mean, but this was not finished by any means, I just pushed it because I switched branches so any odd behaviour is possible. Next version wil be much better.
> All maps
I'll have to see how the map list behaves because the map sizes have such a huge range. Also, this will be problematic with how to handle multiple selected boards (you can drag multiple boards in my version; I'll upload it shortly, but this requires that boards are the same size. Not sure how to handle this). Maybe I can allow any board size as long as the map is 1 board.
> Merge
Yes, I'll have to do that, but Im not looking forward to it, because merging when files were moved (I moved the ChatLounge to its own package) is not nice (or I just don't know how to do that correctly which is also possible).

**Comment by HammerGS** [comment]
I haven't been able to duplicate the map issue I was having. I think the names look great and we might test need to shorten some of the map names.

I have a Lobby question for you. This weekend we had a big game 14 players, each with 2 mechs but set up on 2 teams. Could we have a way to total up the BV by team.

image

In the picture you can see the BV totals for Team 1 are split between players.  Maybe something like in red boxes have

4534 BV (Team total 14324 BV)

Also this shaping up to be an amazing improvement to the lobby.

File: megamek/src/megamek/client/Client.java [hunk 1]
```diff
@@ -1757,4 +1884,18 @@ public void setCurrentHex(IHex hex) {
     public void setCurrentHex(Coords hex) {
         currentHex = hex;
     }
+    
+    /** Returns true when the player is a bot added/controlled by this client. */
+    public boolean isLocalBot(IPlayer player) {
+        return bots.containsKey(player.getName());
+    }
+    
+    /** Returns true when the player is a bot added/controlled by this client. */
```
Comment (NickAragua) [inline megamek/src/megamek/client/Client.java:1893]: Comment doesn't match method behavior. Also, do we really want to be using exceptions as flow control?

File: megamek/src/megamek/client/ui/swing/ClientDialog.java [hunk 2]
```diff
@@ -51,6 +53,12 @@ public ClientDialog(JFrame owner, String title, boolean modal) {
         super(owner, title, modal);
         this.owner = owner;
     }
+    
+    public ClientDialog(JFrame owner, String title, boolean modal, boolean scale) {
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/ClientDialog.java:57]: Is it possible to get some explanation on why somebody would use one of these constructors over the others?

File: megamek/src/megamek/client/ui/swing/ClientGUI.java [hunk 3]
```diff
@@ -709,6 +704,9 @@ public void actionPerformed(ActionEvent event) {
             case FILE_GAME_SAVE:
                 saveGame();
                 break;
+            case FILE_GAME_QSAVE:
+                quickSaveGame();
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/ClientGUI.java:708]: Sneaky a little extra feature in there. Nice.

File: megamek/src/megamek/client/ui/swing/ClientGUI.java [hunk 4]
```diff
@@ -1006,12 +1020,6 @@ void die() {
         }
         client.die();
 
-        // TODO Is there a better solution?
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/ClientGUI.java:1009]: I guess there was a better solution. What happens now?

File: megamek/src/megamek/client/ui/swing/CommonMenuBar.java [hunk 5]
```diff
@@ -243,6 +247,16 @@ public CommonMenuBar() {
         fileGameSave.addActionListener(this);
         fileGameSave.setActionCommand(ClientGUI.FILE_GAME_SAVE);
         submenu.add(fileGameSave);
+        fileGameQSave = new JMenuItem(Messages.getString("CommonMenuBar.fileGameQuickSave")); //$NON-NLS-1$
+        fileGameQSave.addActionListener(this);
+        fileGameQSave.setActionCommand(ClientGUI.FILE_GAME_QSAVE);
+        fileGameQSave.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.CTRL_DOWN_MASK));
+        submenu.add(fileGameQSave);
+        fileGameQLoad = new JMenuItem(Messages.getString("CommonMenuBar.fileGameQuickSave")); //$NON-NLS-1$
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/CommonMenuBar.java:255]: This should probably be QuickLoad instead.

File: megamek/src/megamek/client/ui/swing/CommonMenuBar.java [hunk 6]
```diff
@@ -937,19 +964,19 @@ private synchronized void manageMenu() {
...
         }
+        
+        fileUnitsPaste.setEnabled(phase == IGame.Phase.PHASE_LOUNGE);
 
         // If we have a unit list, and if we are in the lounge,
         // then we can still perform all unit list actions.
         if (hasUnitList) {
             fileUnitsOpen.setEnabled(phase == IGame.Phase.PHASE_LOUNGE);
-            fileUnitsClear.setEnabled(phase == IGame.Phase.PHASE_LOUNGE);
           //  fileUnitsSave.setEnabled(phase == IGame.Phase.PHASE_LOUNGE);
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/CommonMenuBar.java:974]: Maybe get rid of the commented out code here and on line 980? Or address it somehow otherwise.

File: megamek/src/megamek/client/ui/swing/GameOptionsDialog.java [hunk 7]
```diff
@@ -30,24 +30,9 @@
 import java.awt.event.WindowAdapter;
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/GameOptionsDialog.java:30]: Think this one needs the megamek license header.

File: megamek/src/megamek/client/ui/swing/PlanetaryConditionsDialog.java [hunk 8]
```diff
@@ -20,544 +20,618 @@
...
+        // with snowy weather and instead relies on the temperature itself being set correctly.
+        // I believe that the rules allow a temp of e.g. -5 °C with snow (and why not?) and
+        // that the "includes the effects" statements are meant to reduce repetition. If the temp
+        // were fixed to -40 °C, the text of the rules saying "cannot be used with temp of 30 °C 
+        // or more" would be unnecessary. With the current rules handling, temp has to be set to 
+        // the necessary values. Therefore the following check for 30 °C is not needed.
+        //        if (temp >= 30 && requiresLowTemp(weather)) {
+        //            tempValid = false;
+        //            wthrValid = false;
+        //            tempTip.append("The Temperature cannot be 30 °C or more in snowy weather.<BR>");
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/PlanetaryConditionsDialog.java:367]: I'm still amused at the idea of water-based snow in 30C weather.

File: megamek/src/megamek/client/ui/swing/PlanetaryConditionsDialog.java [hunk 9]
```diff
@@ -20,544 +20,618 @@
...
-            JOptionPane
-                    .showMessageDialog(
-                            frame,
-                            Messages
-                                    .getString("PlanetaryConditionsDialog.EnterValidGravity"),
-                            Messages
-                                    .getString("PlanetaryConditionsDialog.NumberFormatError"),
-                            JOptionPane.ERROR_MESSAGE);
-            return false;
+        if ((atmo == ATMO_TRACE) && (wind == WI_LIGHT_GALE)) {
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/PlanetaryConditionsDialog.java:391]: How about vacuum and wind?

File: megamek/src/megamek/client/ui/swing/PlanetaryConditionsDialog.java [hunk 10]
```diff
@@ -20,544 +20,618 @@
...
-                                    .getString("PlanetaryConditionsDialog.VacuumWeather"),
-                            Messages
-                                    .getString("PlanetaryConditionsDialog.Incompatible"),
-                            JOptionPane.ERROR_MESSAGE);
-            return false;
+    }
+    
+    /** 
+     * Updates the enabled state of some fields based on the atmosphere setting. 
+     * Also, for some weather settings,
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/PlanetaryConditionsDialog.java:450]: Also, for some weather settings what?

File: megamek/src/megamek/client/ui/swing/RandomArmyDialog.java [hunk 11]
```diff
@@ -536,20 +537,25 @@ public RandomArmyDialog(ClientGUI cl) {
...
         
-        m_pSplit = new javax.swing.JSplitPane(javax.swing.JSplitPane.HORIZONTAL_SPLIT,m_pMain, m_pRightPane);
+        m_pSplit = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, m_pMain, m_pRightPane);
         m_pSplit.setOneTouchExpandable(false);
         m_pSplit.setResizeWeight(0.5);
 
         // construct the main dialog
         setLayout(new BorderLayout());
-        this.setPreferredSize(new Dimension(800,500));
+//        this.setPreferredSize(new Dimension(800,500));
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/RandomArmyDialog.java:546]: Why's this commented out, along with the pack() on line 550?

File: megamek/src/megamek/client/ui/swing/RandomArmyDialog.java [hunk 12]
```diff
@@ -784,34 +790,51 @@ public void actionPerformed(ActionEvent ev) {
...
-    }
-
-    public void windowDeiconified(WindowEvent arg0) {
-        //ignored
-    }
-
-    public void windowIconified(WindowEvent arg0) {
-        //ignored
-    }
+//    public void windowActivated(WindowEvent arg0) {
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/RandomArmyDialog.java:793]: If we don't need these, how about deleting them?

File: megamek/src/megamek/client/ui/swing/boardview/EntitySprite.java [hunk 13]
```diff
@@ -718,496 +688,6 @@ public Coords getPosition() {
         return entity.getPosition();
     }
     
-    private StringBuffer tooltipString;
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/boardview/EntitySprite.java:721]: Where'd all this stuff go?

File: megamek/src/megamek/client/ui/swing/dialog/AbstractUnitSelectorDialog.java [hunk 14]
```diff
@@ -187,7 +187,10 @@ private void setUserPreferences() {
         ((DefaultRowSorter<?, ?>) tableUnits.getRowSorter()).sort();
 
         tableUnits.invalidate(); // force re-layout of window
-        pack();
+//        pack();
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/dialog/AbstractUnitSelectorDialog.java:190]: Commented out pack?

**Review by NickAragua — CHANGES_REQUESTED** [review]
Got through about half the files. Didn't review the data files, since I wouldn't know what's correct and what isn't anyway. Will take a look at the rest of the files over the next few days.

File: megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java [hunk 15]
```diff
@@ -0,0 +1,1312 @@
...
+    }
+    
+    /** 
+     * Returns a likely owner client; if any of the fighter belongs to the local
+     * player, returns the local player. If not, returns a local bot if any of the
+     * fighters belongs to that; finally, returns the owner of a random one of the 
+     * fighters.
+     */
+    private IPlayer createSquadronOwner(Collection<Entity> entities) {
+        if (entities.stream().anyMatch(e -> e.getOwner().equals(localPlayer()))) {
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java:1019]: Gotta ask, is there a reason we're guessing who owns the squadron that a given entity is in? Do we allow entities from multiple players to form squadrons or something?

File: megamek/src/megamek/client/ui/swing/lobby/LobbyMekPopupActions.java [hunk 16]
```diff
@@ -0,0 +1,328 @@
...
+        String command = st.nextToken();
+        // info need not be an int; loading uses the format "##:##"
+        String info = st.nextToken();
+        // The entities list may be empty
+        Set<Entity> entities = LobbyUtility.getEntities(lobby.game(), st.nextToken());
+        
+        switch (command) {
+            
+            // Single entity commands
+        case "CONFIGURE":
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/lobby/LobbyMekPopupActions.java:47]: Well, I see where all the magic strings come from.

File: megamek/src/megamek/server/WeatherProcessor.java [hunk 17]
```diff
@@ -113,7 +113,6 @@ private void resolveWeather() {
             }
         }
         if(((conditions.getWeather() == PlanetaryConditions.WE_HEAVY_SNOW)
-                || (conditions.getWeather() == PlanetaryConditions.WE_BLIZZARD)
```
Comment (NickAragua) [inline megamek/src/megamek/server/WeatherProcessor.java:116]: Where'd blizzard go?

File: megamek/src/megamek/server/ServerHelper.java [hunk 18]
```diff
@@ -449,4 +441,510 @@ public static void checkAndApplyMagmaCrust(IHex hex, int elevation, Entity entit
             }
         }
     }
+    
+    /**
+     * Returns a list of path names of available boards of the size set in the given
+     * mapSettings. The path names are minus the '.board' extension and relative to
+     * the boards data directory.
+     */
+    static ArrayList<String> scanForBoards(MapSettings mapSettings) {
```
Comment (NickAragua) [inline megamek/src/megamek/server/ServerHelper.java:450]: In general, I'm kind of concerned that this file will become another disorganized mess like Server.java. I think it'd be better to organize the various methods into different ServerHelper classes, e.g. the board scanning/loading related methods into ServerBoardHelper, etc.

File: megamek/src/megamek/server/Server.java [hunk 19]
```diff
@@ -29964,13 +29868,38 @@ public boolean accept(Entity entity) {
...
+                            Force parent = game.getForces().getForce(realId);
+                            realId = game.getForces().addSubForce(force.getName(), parent);
+                        }
+                        forceMapping.put(force.getId(), realId);
+                    } else {
+                        realId = forceMapping.get(force.getId());
+                    }
+                    topLevel = false;
+                }
+                entity.setForceString("");
```
Comment (NickAragua) [inline megamek/src/megamek/server/Server.java:29899]: We no longer have a need for this once we load the entity's forces?

File: megamek/src/megamek/server/Server.java [hunk 20]
```diff
@@ -30435,11 +30467,29 @@ private void receiveEntityAmmoChange(Packet c, int connIndex) {
...
+            send(ServerHelper.createMultiEntityPacket(updateCandidates));
+        }
+        
+        ArrayList<Force> affectedForces = new ArrayList<>();
         for (Integer entityId : ids) {
             final Entity entity = game.getEntity(entityId);
 
-            // Only allow players to delete their *own* entities.
-            if ((entity != null) && (entity.getOwner() == getPlayer(connIndex))) {
+            // Players can delete units of their teammates
```
Comment (NickAragua) [inline megamek/src/megamek/server/Server.java:30489]: Sounds like a great prank.

File: megamek/src/megamek/common/util/CollectionUtil.java [hunk 21]
```diff
@@ -0,0 +1,52 @@
...
+        result.addAll(c2);
+        return result;
+    }
+    
+    /** 
+     * Returns a random element of the collection or the element if it has only one.
+     * Throws a NoSuchElement exception if it is empty.
+     */
+    public static final <T> T randomElement(Collection<T> collection) {
+        return collection.stream().findFirst().get();
```
Comment (NickAragua) [inline megamek/src/megamek/common/util/CollectionUtil.java:38]: Is this really random?

File: megamek/src/megamek/common/Terrains.java [hunk 22]
```diff
@@ -211,38 +211,16 @@ public static String getEditorTooltip(int type) {
...
         switch (type) {
-        case (BUILDING):
-            if (level == 1) {
-                return "Light building";
-            } else if (level == 2) {
-                return "Medium building";
-            } else if (level == 3) {
-                return "Heavy building";
-            } else if (level == 4) {
-                return "Hardened Building";
```
Comment (NickAragua) [inline megamek/src/megamek/common/Terrains.java:228]: I assume that this descriptive building text is contained somewhere else?

File: megamek/src/megamek/common/PlanetaryConditions.java [hunk 23]
```diff
@@ -48,13 +48,14 @@
...
     public static final int WE_SLEET            = 10;
-    public static final int WE_BLIZZARD         = 11;
-    public static final int WE_ICE_STORM        = 12;
-    public static final int WE_LIGHT_HAIL       = 13;
-    public static final int WE_HEAVY_HAIL       = 14;
+    public static final int WE_ICE_STORM        = 11;
+    public static final int WE_LIGHT_HAIL       = 12;// NYI
+    public static final int WE_HEAVY_HAIL       = 13;// NYI
+    public static final int WE_LIGHTNING_STORM  = 14;// NYI
+    //  public static final int WE_BLIZZARD         = 11; does not exist anymore
```
Comment (NickAragua) [inline megamek/src/megamek/common/PlanetaryConditions.java:55]: Guess I know what happened to blizzard

File: megamek/src/megamek/common/OffBoardDirection.java [hunk 24]
```diff
@@ -78,4 +78,30 @@ public static OffBoardDirection getOpposite(OffBoardDirection value) {
             return NONE;
         }
     }
+    
+    /** 
+     * Returns the OffBoardDirection associated with given the on-board deployment
+     * position as defined in IStartingPositions.
+     */
+    public static OffBoardDirection translateStartPosition(int startPos) {
+        if (startPos > 10) {
```
Comment (NickAragua) [inline megamek/src/megamek/common/OffBoardDirection.java:87]: I'm having a little trouble understanding the logic in this method.

File: megamek/src/megamek/common/EntityWeightClass.java [hunk 25]
```diff
@@ -252,8 +250,6 @@ public static int getWeightClass(double tonnage, Entity en) {
                     break;
                 }
             }
-        } else if (en instanceof ConvFighter) {
```
Comment (NickAragua) [inline megamek/src/megamek/common/EntityWeightClass.java:255]: In the other method, you added conventional fighters to the aero else if, here, they're just removed?

**Review by NickAragua — CHANGES_REQUESTED** [review]
Round 2. 98/132 files reviewed.

File: megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java [hunk 26]
```diff
@@ -0,0 +1,870 @@
...
+                result.append(" [" + carried.getId() + "]");
+            }
+
+        }
+        result.append("</FONT>");
+        return result;
+    }
+    
+    /** Returns a list of units loaded onto this unit. */
+    private static StringBuilder forceEntry(Entity entity, IPlayer localPlayer) {
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java:780]: Comment doesn't match method name or behavior.

File: megamek/src/megamek/client/ui/swing/util/UIUtil.java [hunk 27]
```diff
@@ -0,0 +1,735 @@
...
+    public static String scaleStringForGUI(String str) {
+        return "<HTML>" + UIUtil.guiScaledFontHTML() + str + "</FONT></HTML>";
+    }
+    
+    /** Returns the given String str enclosed in HTML tags and with a font tag according to the guiScale. */ 
+    public static String scaleMessageForGUI(String str) {
+        return "<HTML>" + UIUtil.guiScaledFontHTML() + Messages.getString(str) + "</FONT></HTML>";
+    }
+    
+    public static void adjustDialog(Container contentPane) {
```
Comment (NickAragua) [inline megamek/src/megamek/client/ui/swing/util/UIUtil.java:369]: What's this do?

**Review by NickAragua — CHANGES_REQUESTED** [review]
All right, finished. Some questions and relatively minor change requests.

File: megamek/src/megamek/client/Client.java (hunk 1 above)
Comment (SJuliez) [reply megamek/src/megamek/client/Client.java:1893]: I'll change it to simply return null when the given player isn't actually a bot. Saves space. I don't mind but for the sake of clarity: When a method can't return a value that is correct, then why not use an exception? It just means it'll fail clearly when the caller doesn't do the appropriate checks before. In the same case, returning null will likely lead to an NPE, just at another place. I wouldn't know what else to return.

Comment (NickAragua) [reply megamek/src/megamek/client/Client.java:1893]: Looking at it again, in this particular case, I don't think I have a problem with the exception, just the mismatched comment. Maybe include an update to the comment that indicates this throws an exception.

File: megamek/src/megamek/client/ui/swing/ClientGUI.java (hunk 4 above)
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/ClientGUI.java:1009]: From the former comment:
// This is required because the ChatLounge adds the listener to the
// MechSummaryCache that must be removed explicitly.
I think the call to `((Distractable) component).removeAllListeners();` a few lines above already removes that listener.

File: megamek/src/megamek/client/ui/swing/CommonMenuBar.java (hunk 5 above)
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/CommonMenuBar.java:255]: Yes.

File: megamek/src/megamek/client/ui/swing/CommonMenuBar.java (hunk 6 above)
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/CommonMenuBar.java:974]: I think I'll remove these menu items. They are for the lobby only anyway and saving unit lists depends on blind drop options which the menu bar doesnt adress and loading units lists depends on the selected player which the menu bar also doesnt adress. There's big buttons for loading/saving.

File: megamek/src/megamek/client/ui/swing/PlanetaryConditionsDialog.java (hunk 9 above)
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/PlanetaryConditionsDialog.java:391]: Vacuum disables all weather settings, so it doesnt need to be checked there. But it was not actually resetting the weather. Will be corrected.

File: megamek/src/megamek/client/ui/swing/RandomArmyDialog.java (hunk 11 above)
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/RandomArmyDialog.java:546]: The whole dialog now remembers its position and size, therefore the setpreferredsize and pack are unnecessary. I'll remove the lines.

File: megamek/src/megamek/client/ui/swing/boardview/EntitySprite.java (hunk 13 above)
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/boardview/EntitySprite.java:721]: To UnitTooltip

File: megamek/src/megamek/client/ui/swing/RandomArmyDialog.java (hunk 12 above)
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/RandomArmyDialog.java:793]: done.

File: megamek/src/megamek/client/ui/swing/dialog/AbstractUnitSelectorDialog.java (hunk 14 above)
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/dialog/AbstractUnitSelectorDialog.java:190]: Same as the RandomArmyDialog, this dialog now remembers size&position and the pack had to go to make it work.

File: megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java [hunk 28]
```diff
@@ -0,0 +1,3628 @@
...
+        panMapType.setAlignmentX(JPanel.CENTER_ALIGNMENT);
+        panMapType.add(butGroundMap);
+        panMapType.add(butLowAtmoMap);
+//        panMapType.add(butHighAtmoMap);
+        panMapType.add(butSpaceMap);
+        grpMap.add(butGroundMap);
+        grpMap.add(butLowAtmoMap);
+        grpMap.add(butHighAtmoMap);
+        grpMap.add(butSpaceMap);
+//        panMap.add(panMapType);
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java:585]: Its added a few lines below. Just leftovers from moving stuff around. Will delete those lines.

File: megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java [hunk 29]
```diff
@@ -0,0 +1,3628 @@
...
+        
+        // Planetary Conditions and Random Map Settings buttons
+        FixedYPanel panSettings = new FixedYPanel();
+        panSettings.setAlignmentX(JPanel.CENTER_ALIGNMENT);
+        panSettings.add(butConditions);
+        panSettings.add(butRandomMap);
+//        panMap.add(panSettings);
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java:592]: As above.

File: megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java [hunk 30]
```diff
@@ -0,0 +1,3628 @@
...
+            JOptionPane.showMessageDialog(clientgui.frame, 
+                    "There was a problem while loading the map setup!", "Error", JOptionPane.ERROR_MESSAGE);
+            MegaMek.getLogger().error(ex);
+        }
+    }
+    
+    private void removeBot() {
+        Client c = getSelectedClient();
+        if (!client().bots.containsValue(c)) {
+//        if ((c == null) || c.equals(clientgui.getClient())) {
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java:1997]: Leftovers. Will remove.

File: megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java [hunk 31]
```diff
@@ -0,0 +1,3628 @@
...
+    
+    private void setManualMapWidth() {
+        try {
+            int newMapWidth = Integer.parseInt(fldMapWidth.getText());
+            if (newMapWidth >= 1 && newMapWidth <= 20) {
+                mapSettings.setMapSize(newMapWidth, mapSettings.getMapHeight());
+                clientgui.getClient().sendMapDimensions(mapSettings);
+            }
+        } catch (NumberFormatException e) {
+            // no number, no new map width
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java:2051]: you mean like `boolean tryParse(String source, Object resultValue) {}`? It would help if Java could handle return tupels. (Or anything else C# added in the last few years :-) )

File: megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java [hunk 32]
```diff
@@ -0,0 +1,3628 @@
...
+            
+            if (code == KeyEvent.VK_SPACE) {
+                e.consume();
+                mechReadoutAction(selEntities);
+                
+            } else if (code == KeyEvent.VK_ENTER && onlyOneEntity) {
+                e.consume();
+                lobbyActions.customizeMech(selEntities.get(0));
+                
+            } else if (code == KeyEvent.VK_UP && e.getModifiersEx() == InputEvent.CTRL_DOWN_MASK) {
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java:2666]: No. I could add this to the popup with the key shortcut so people will see it.

File: megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java [hunk 33]
```diff
@@ -0,0 +1,3628 @@
...
+                    }
+                    icon = new ImageIcon(image);
+                    
+                    mapIcons.put(board, icon);
+                    setIcon(icon);
+                }
+            }
+            
+            // Found or created an icon; finish the panel
+            setText("");
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java:3464]: When an icon isn't there, the super renderer result is returned a few lines above. This will set the text, so it has to be reset when an icon is found and used (otherwise, the text of a first list entry will stay present for all subsequently rendered list entries, sorry if that overexplains).

File: megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java [hunk 34]
```diff
@@ -0,0 +1,3628 @@
...
+    /** Returns true when the compact view is active. */ 
+    public boolean isCompact() {
+        return butCompact.isSelected();
+    }
+    
+    /** 
+     * Returns a list of the selected entities in the Mek table. 
+     * The list may be empty but not null. 
+     */
+    private ArrayList<Entity> getSelectedEntities() {
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java:3289]: OK done, though I wonder at this practice (I also found it at some Java Practices website). Why stop at List? If I change the method to actually use a Set (which I've done multiple times while doing the lobby stuff) I still have to change the return value and possibly the callers. Isnt it the fault of the caller to not use a Collection whenever possible? If they do, I can return an ArrayList or a HashSet, no problem. Shouldnt the actual practice be to always receive a Collection?

File: megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java [hunk 35]
```diff
@@ -0,0 +1,1312 @@
...
+    /** Shows the dialog which allows adding pre-existing damage to units. */
+    void configureDamage(Collection<Entity> entities) {
+        if (entities.size() != 1) {
+            LobbyErrors.showSingleUnit(frame(), "assign damage");
+            return;
+        }
+        if (!validateUpdate(entities)) {
+            return;
+        }
+        Entity entity = CollectionUtil.randomElement(entities);
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java:185]: Here and at other places, I wanted to receive Collections instead of lists (as discussed above), especially as the order of the selected entities shouldnt play any role. When the collection has only 1 element its still bothersome to get that element, therefore I used that method. Sometimes I used it with multiple entities to find some, e.g. to find one owner. I think I'll rename it to anyOneElement or something like that as it really has nothing to do with random.

File: megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java [hunk 36]
```diff
@@ -0,0 +1,1312 @@
...
+                    m.setMode("");
+                }
+                updateCandidates.add(entity);
+            };
+        }
+        sendUpdates(updateCandidates);
+    }
+    
+    public void load(Collection<Entity> selEntities, String info) {
+        StringTokenizer stLoad = new StringTokenizer(info, ":");
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java:567]: Yup, will remove from ChatLounge

File: megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java (hunk 15 above)
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java:1019]: Yes, loading/squadron/C3/forces are allowed within teams. I didn't want to add an owner dropdown or something for a fighter squadron. Most of the time there'll only be one owner anyway.

File: megamek/src/megamek/server/WeatherProcessor.java (hunk 17 above)
Comment (SJuliez) [reply megamek/src/megamek/server/WeatherProcessor.java:116]: Global Warming? I just couldn't find it in the rules anymore.

File: megamek/data/images/temp/The images in this directory can be safely deleted between games.txt [hunk 37]
```diff
@@ -0,0 +1 @@
+The images in this directory ar temporary images used for the pilot tooltips. They can be safely deleted while not in a MegaMek game.
```
Comment (Windchild292) [inline megamek/data/images/temp/The images in this directory can be safely deleted between games.txt:1]:
```suggestion
The images in this directory are temporary images used for the pilot tooltips. They can be safely deleted while not in a MegaMek game.
```

File: megamek/src/megamek/common/OffBoardDirection.java (hunk 24 above)
Comment (Windchild292) [reply megamek/src/megamek/common/OffBoardDirection.java:87]: I think it might mean modulo ten?

File: megamek/src/megamek/client/ui/swing/ReportDisplay.java [hunk 38]
```diff
@@ -223,10 +228,11 @@ public void setReportTab(int round, String roundText, String phaseText) {
     public static void setupStylesheet(JTextPane pane) {
         pane.setContentType("text/html");
         Font font = UIManager.getFont("Label.font");
+        int size = UIUtil.scaleForGUI(UIUtil.FONT_SCALE1);
         ((HTMLEditorKit) pane.getEditorKit()).getStyleSheet().addRule(
-               "pre { font-family: " + font.getFamily() + "; font-size: 12pt; font-style:normal;}");
+                "pre { font-family: " + font.getFamily() + "; font-size: "+size+"pt; font-style:normal;}");
```
Comment (Windchild292) [inline megamek/src/megamek/client/ui/swing/ReportDisplay.java:233]:
```suggestion
                "pre { font-family: " + font.getFamily() + "; font-size: " + size + "pt; font-style:normal;}");
```

File: megamek/src/megamek/client/ui/swing/MovementDisplay.java [hunk 39]
```diff
@@ -2116,12 +2116,12 @@ private void updateRACButton() {
 
     private void updateSearchlightButton() {
         final Entity ce = ce();
-        if (null == ce) {
-            return;
-        }
+        if (ce != null) {
+        boolean isNight = clientgui.getClient().getGame().getPlanetaryConditions().isSearchlightEffective();
         setSearchlightEnabled(
```
Comment (Windchild292) [inline megamek/src/megamek/client/ui/swing/MovementDisplay.java:2121]: Indent

File: megamek/i18n/megamek/client/messages.properties [hunk 40]
```diff
@@ -206,8 +214,8 @@ BoardSelectionDialog.UpdateMapSize.message=Please hit the Update Map Size button
 BoardSelectionDialog.UpdateMapSize.title=Please Update Map Size
 BoardSelectionDialog.UpdateSize=Update Size
 BoardSelectionDialog.Updating=Updating...
-BoardSelectionDialog.ViewGameBoard=View Game Board*
-BoardSelectionDialog.ViewGameBoardTooltip=<html>Shows a preview of the selected map.<br>  *Note: for generated maps the preview is only a sample<br> and will not be the same as the actual map used.</html>
+BoardSelectionDialog.ViewGameBoard=Preview Game Map... *
+BoardSelectionDialog.ViewGameBoardTooltip=Shows a preview of the game's map.<br>  * Note: For generated maps and surprise maps the preview is only a sample<br> and will not be the same as the actual map used.
```
Comment (Windchild292) [inline megamek/i18n/megamek/client/messages.properties:218]: Recommendation: Swap the side where the BR is, to avoid having 
```
Hello
 World
```

File: megamek/i18n/megamek/client/messages.properties [hunk 41]
```diff
@@ -344,58 +352,49 @@ BoardView1.ROLLED=ROLLED
...
-BoardView1.Tooltip.PilotEnd=</TD></TR></TBODY></TABLE>
-BoardView1.Tooltip.PilotStatus=<FONT COLOR=#FF0000> ({0})</FONT>
-BoardView1.Tooltip.Advs=<BR><FONT SIZE=-2 COLOR=#555555>&nbsp;&nbsp;{0} Advs.;</FONT>
-BoardView1.Tooltip.Adv1=<BR><FONT SIZE=-2 COLOR=#555555>&nbsp;&nbsp;1 Adv.;</FONT>
-BoardView1.Tooltip.PilotPortraitW=</TR><TR><TD VALIGN=\"top\"><IMG WIDTH=60 HEIGHT={1} SRC=\"file:{0}\"></TD>
-BoardView1.Tooltip.PilotPortraitH=</TR><TR><TD VALIGN=\"top\"><IMG WIDTH={1} HEIGHT=60 SRC=\"file:{0}\"></TD>
+BoardView1.Tooltip.AeroVelAlt=<I>Velocity: {0}, Altitude: {1}</I>
+BoardView1.Tooltip.AeroStartingVelAlt=<I>Starting Velocity: {0}, Altitude: {1}</I>
 BoardView1.Tooltip.ArmorInternals=Armor {0}; Internal {1}
+BoardView1.Tooltip.ArmorCapital=<I>Capital Armor</I>
```
Comment (Windchild292) [inline megamek/i18n/megamek/client/messages.properties:358]: Italics are terrible for accessibility, and should **never** be used. Use em or b instead.

Comment (Windchild292) [reply megamek/i18n/megamek/client/messages.properties:358]: This holds for the whole file, as I see a number of other cases where this occurs.

File: megamek/i18n/megamek/client/messages.properties [hunk 42]
```diff
@@ -550,22 +567,55 @@ ChatLounge.PartialRepairs=Partial Repairs
...
+ChatLounge.teamOverview.COLCOST=Cost
+ChatLounge.teamOverview.COLBV=BV
+ChatLounge.teamOverview.COLMEMBERS=Team Members
+ChatLounge.teamOverview.COLUNITS=Unit Summary
+ChatLounge.teamOverview.COLHIDDEN=Hidden
+ChatLounge.teamOverview.unitSum0=Meks:
+ChatLounge.teamOverview.unitSum1=Vehicles:
+ChatLounge.teamOverview.unitSum2=Aero:
+ChatLounge.teamOverview.unitSum3=Infantry:
+ChatLounge.teamOverview.unitSum4=Protomeks:
```
Comment (Windchild292) [inline megamek/i18n/megamek/client/messages.properties:616]:
```suggestion
ChatLounge.teamOverview.unitSum4=ProtoMeks:
```

File: megamek/i18n/megamek/client/messages.properties [hunk 43]
```diff
@@ -1266,6 +1325,7 @@ GameOptionsDialog.Save=Save
 GameOptionsDialog.Search=Search
 GameOptionsDialog.SearchToolTip=Search for options that contain the entered text
 GameOptionsDialog.Load=Load
+GameOptionsDialog.HideWarning=Warning: All hidden options will also be turned off. If you reenable these options, you will have to reenable any of the affected options manually. Are you sure?
```
Comment (Windchild292) [inline megamek/i18n/megamek/client/messages.properties:1328]:
```suggestion
GameOptionsDialog.HideWarning=Warning: All hidden options will also be turned off. If you re-enable these options, you will have to re-enable any of the affected options manually. Are you sure?
```

File: megamek/i18n/megamek/client/messages.properties [hunk 44]
```diff
@@ -2090,23 +2150,37 @@ PlanetaryConditionsDialog.labAtmosphere=Atmospheric Pressure
 PlanetaryConditionsDialog.BlowingSands=Blowing Sand
 PlanetaryConditionsDialog.EMI=EMI
 PlanetaryConditionsDialog.labFog=Fog
-PlanetaryConditionsDialog.labGrav=Gravity
+PlanetaryConditionsDialog.labGrav=Gravity (g)
 PlanetaryConditionsDialog.labLight=Light
-PlanetaryConditionsDialog.labTemp=Temperature
+PlanetaryConditionsDialog.labTemp=Temperature (deg C)
```
Comment (Windchild292) [inline megamek/i18n/megamek/client/messages.properties:2155]:
```suggestion
PlanetaryConditionsDialog.labTemp=Temperature (\u00B0C)
```

Comment (Windchild292) [reply megamek/i18n/megamek/client/messages.properties:2155]: Unicode symbol, which fixes a number of possible issues (had a MekHQ bug that using the icon instead of the unicode led to display issues.

File: megamek/i18n/megamek/client/messages.properties [hunk 45]
```diff
@@ -2090,23 +2150,37 @@ PlanetaryConditionsDialog.labAtmosphere=Atmospheric Pressure
...
-PlanetaryConditionsDialog.labMaxWind=Maximum Wind
+PlanetaryConditionsDialog.labMinWind=between
+PlanetaryConditionsDialog.labMaxWind=and
 PlanetaryConditionsDialog.NumberFormatError=Number Format Error
 PlanetaryConditionsDialog.title=Planetary Conditions
-PlanetaryConditionsDialog.EnterValidTemperature=Temperature must be between -200 and 200 degrees Celsius.
+
+PlanetaryConditionsDialog.invalid.integer=Enter an integer number.<BR>
+PlanetaryConditionsDialog.invalid.number=Enter a number.<BR>
+PlanetaryConditionsDialog.invalid.tempRange=The Temperature must be between -200 and 200 �C.<BR>
```
Comment (Windchild292) [inline megamek/i18n/megamek/client/messages.properties:2165]:
```suggestion
PlanetaryConditionsDialog.invalid.tempRange=The Temperature must be between -200 and 200 \u00B0C.<BR>
```

File: megamek/i18n/megamek/client/messages.properties [hunk 46]
```diff
@@ -2090,23 +2150,37 @@ PlanetaryConditionsDialog.labAtmosphere=Atmospheric Pressure
...
+PlanetaryConditionsDialog.invalid.gravRange=Gravity must be between 0.1 g and 10 g.<BR>
+PlanetaryConditionsDialog.invalid.sandsLost=The effects of Blowing Sands are lost when the wind is below Moderate Gale strength.<BR>
+PlanetaryConditionsDialog.invalid.traceLightGale=In Trace Atmosphere, Light Gale is not allowed.<BR>
+PlanetaryConditionsDialog.invalid.lightSnowTemp=This weather includes the effects of a temperature of -40 �C and any higher temperature setting is invalid.<BR>
+PlanetaryConditionsDialog.invalid.modSnowTemp=This weather includes the effects of a temperature of -50 �C and any higher temperature setting is invalid.<BR>
+PlanetaryConditionsDialog.invalid.iceStormTemp=Ice Storm includes the effects of a temperature of -60 �C and any higher temperature setting is invalid.<BR>
```
Comment (Windchild292) [inline megamek/i18n/megamek/client/messages.properties:2171]:
```suggestion
PlanetaryConditionsDialog.invalid.lightSnowTemp=This weather includes the effects of a temperature of -40 \u00B0C and any higher temperature setting is invalid.<BR>
PlanetaryConditionsDialog.invalid.modSnowTemp=This weather includes the effects of a temperature of -50 \u00B0C and any higher temperature setting is invalid.<BR>
PlanetaryConditionsDialog.invalid.iceStormTemp=Ice Storm includes the effects of a temperature of -60 \u00B0C and any higher temperature setting is invalid.<BR>
```

File: megamek/i18n/megamek/client/messages.properties [hunk 47]
```diff
@@ -2090,23 +2150,37 @@ PlanetaryConditionsDialog.labAtmosphere=Atmospheric Pressure
...
+PlanetaryConditionsDialog.invalid.windRange=The current wind strength is outside the range of shifting wind strengths.<BR>
+
+PlanetaryConditionsDialog.EnterValidTemperature=The Temperature must be between -200 and 200 �C.<BR>
```
Comment (Windchild292) [inline megamek/i18n/megamek/client/messages.properties:2174]:
```suggestion
PlanetaryConditionsDialog.EnterValidTemperature=The Temperature must be between -200 and 200 \u00B0C.<BR>
```

File: megamek/i18n/megamek/client/messages.properties [hunk 48]
```diff
@@ -3539,7 +3620,7 @@ HeatEffects.tsm.mt.49=-7 MP; +7 BTH
 HeatEffects.tsm.mt.50=Automatic shutdown
 
 #Loading Units into Bays
-LoadingBay.baytoomany=Too many units selected.\nThe selected bay has a remaining capacity of 
+LoadingBay.baytoomany=Too many units selected.\nThe selected bay has a remaining capacity of {0}{1}.
```
Comment (Windchild292) [inline megamek/i18n/megamek/client/messages.properties:3623]: Just checking that this wasn't supposed to have a space?

File: megamek/src/megamek/client/ratgenerator/ForceDescriptor.java [hunk 49]
```diff
@@ -843,6 +845,29 @@ public void loadEntities(Ruleset.ProgressListener l, double progress) {
             l.updateProgress(progress, "Loading entities");
         }
     }
+    
+    /** Generates a force string for exporting these units to MUL / adding to the game. */
+    private String getForceString() {
+        ArrayList<ForceDescriptor> ancestors = new ArrayList<>();
```
Comment (Windchild292) [inline megamek/src/megamek/client/ratgenerator/ForceDescriptor.java:851]:
```suggestion
        List<ForceDescriptor> ancestors = new ArrayList<>();
```

File: megamek/src/megamek/client/Client.java [hunk 50]
```diff
@@ -852,6 +865,50 @@ public void sendDeploymentUnload(Entity loader, Entity loaded) {
...
+     * The server will handle this; the client does not have to implement the change.
+     */
+    public void sendAssignForceFull(Collection<Force> forceList, int newOwnerId) {
+        send(new Packet(Packet.COMMAND_FORCE_ASSIGN_FULL, new Object[] { forceList, newOwnerId }));
+    }
+        
+    /** Sends a packet to the Server requesting to delete the given forces. */
+    public void sendDeleteForces(List<Force> toDelete) {
+        List<Integer> forceIds = new ArrayList<>();
+        toDelete.stream().mapToInt(f -> f.getId()).forEach(forceIds::add);
```
Comment (Windchild292) [inline megamek/src/megamek/client/Client.java:902]:
```suggestion
        List<Integer> forceIds = toDelete.stream().mapToInt(Force::getId).boxed().collect(Collectors.toList());
```

File: megamek/src/megamek/client/Client.java [hunk 51]
```diff
@@ -953,7 +1015,41 @@ protected void receiveEntities(Packet c) {
...
-
+    
+    /**
+     * Receives a force-related update containing affected forces and affected entities
+     */
+    @SuppressWarnings("unchecked")
+    protected void receiveForceUpdate(Packet c) {
+        Collection<Force> forces = (Collection<Force>) c.getObject(0);
+        Collection<Entity> entities = (Collection<Entity>) c.getObject(1);
+        for (Force force: forces) {
```
Comment (Windchild292) [inline megamek/src/megamek/client/Client.java:1026]:
```suggestion
        for (Force force : forces) {
```

File: megamek/src/megamek/client/Client.java [hunk 52]
```diff
@@ -953,7 +1015,41 @@ protected void receiveEntities(Packet c) {
...
+            game.getForces().replace(force.getId(), force);
+        }
+        for (Entity entity: entities) {
```
Comment (Windchild292) [inline megamek/src/megamek/client/Client.java:1029]:
```suggestion
        for (Entity entity : entities) {
```

File: megamek/src/megamek/client/Client.java [hunk 53]
```diff
@@ -965,28 +1061,50 @@ protected void receiveEntityUpdate(Packet c) {
...
         game.setEntity(eindex, entity, movePath);
     }
+    
+    /**
+     * Update multiple entities from the server. Used only in the lobby phase. 
+     */
+    @SuppressWarnings("unchecked")
+    protected void receiveEntitiesUpdate(Packet c) {
+        Collection<Entity> entities = (Collection<Entity>) c.getObject(0);
+        for (Entity entity: entities) {
```
Comment (Windchild292) [inline megamek/src/megamek/client/Client.java:1071]:
```suggestion
        Collection<Entity> entities = (Collection<Entity>) c.getObject(0);
        for (Entity entity : entities) {
```

Comment (Windchild292) [reply megamek/src/megamek/client/Client.java:1071]: Could also probably just have the cast in the for loop call

File: megamek/src/megamek/client/Client.java [hunk 54]
```diff
@@ -965,28 +1061,50 @@ protected void receiveEntityUpdate(Packet c) {
...
 
     protected void receiveEntityAdd(Packet packet) {
         @SuppressWarnings("unchecked")
         List<Integer> entityIds = (List<Integer>) packet.getObject(0);
         @SuppressWarnings("unchecked")
         List<Entity> entities = (List<Entity>) packet.getObject(1);
+        @SuppressWarnings("unchecked")
+        List<Force> forces = (List<Force>) packet.getObject(2);
 
+        for (Force force: forces) {
```
Comment (Windchild292) [inline megamek/src/megamek/client/Client.java:1084]:
```suggestion
        for (Force force : forces) {
```

File: megamek/src/megamek/client/Client.java [hunk 55]
```diff
@@ -965,28 +1061,50 @@ protected void receiveEntityUpdate(Packet c) {
...
         @SuppressWarnings("unchecked")
         List<Integer> entityIds = (List<Integer>) packet.getObject(0);
         int condition = packet.getIntValue(1);
+        @SuppressWarnings("unchecked")
+        List<Force> forces = (List<Force>) packet.getObject(2);
         //create a final image for the entity
         for(int id: entityIds) {
             cacheImgTag(game.getEntity(id));
         }
+        for (Force force: forces) {
```
Comment (Windchild292) [inline megamek/src/megamek/client/Client.java:1105]:
```suggestion
        for (Force force : forces) {
```

File: megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java (hunk 34 above)
[the remark this answers is not in the document]
Comment (Windchild292) [reply megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java:3289]: The reason I code using List/Set instead of Collection is that both give you more information and functionality while still being generic.

If you see a set, you know the values within are unique and that contains is a fast method to use.
If you see a list, you know the values within are ordered, sortable, accessible and insertable by index, and searchable by element.

The individual implementations within those two are less important, and can thus be genericized out, but just having a collection (especially with list) removes a huge amount of functionality and information for the programmer.

So... I'd use collection only if you don't and cannot think of a future reason why to use any list-based functionality and don't care about the duplication state (which... would just be easier to use and return List still to future proof it).

**Review by Windchild292 — CHANGES_REQUESTED** [review]
Went through about 2/3 of this PR (including all of the data), and made comments on it.

File: megamek/src/megamek/server/ServerHelper.java (hunk 18 above)
Comment (SJuliez) [reply megamek/src/megamek/server/ServerHelper.java:450]: Yes I hijacked this as my Eclipse continually goes on 10s hibernations when I edit anything in Server. I'll see if I can divide some things out.

File: megamek/src/megamek/common/util/CollectionUtil.java (hunk 21 above)
Comment (SJuliez) [reply megamek/src/megamek/common/util/CollectionUtil.java:38]: Renamed.

File: megamek/src/megamek/common/Terrains.java (hunk 22 above)
Comment (SJuliez) [reply megamek/src/megamek/common/Terrains.java:228]: No, this was not a good change. I'll revert it.

File: megamek/src/megamek/common/OffBoardDirection.java (hunk 24 above)
Comment (SJuliez) [reply megamek/src/megamek/common/OffBoardDirection.java:87]: The deep deployment zones use the numbers of the normal deployment zones +10

File: megamek/src/megamek/common/EntityWeightClass.java (hunk 25 above)
Comment (SJuliez) [reply megamek/src/megamek/common/EntityWeightClass.java:255]: ConvFighter is instanceof Aero so the Aero part works for ConvFighters in the second method.

File: megamek/src/megamek/client/ui/swing/lobby/LobbyMekPopup.java [hunk 56]
```diff
@@ -0,0 +1,688 @@
...
+            }
+            menu.add(ScalingPopup.spacer());
+
+            // Heat
+            JMenu heatMenu = new JMenu("Heat at start");
+            heatMenu.add(menuItem("No heat", "HEAT|0" + eIds, enabled, listener));
+            for (int i = 1; i < 11; i++) {
+                heatMenu.add(menuItem("Heat " + i, "HEAT|" + i + eIds, enabled, listener));
+            }
+            JMenu subHeatMenu = new JMenu("More heat");
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/LobbyMekPopup.java:344]: I didnt think so. Assigning heat should be rare. assigning 7 heat is just a menu entry. And if you really need to assign 22 heat you can do that in that last submenu. Its sure blocky but gets it done. I have to add that personally I dislike any UI item that forces me to click a tiny arrow which is why I avoid Spinners.

image

File: megamek/src/megamek/client/ui/swing/lobby/LobbyUtility.java [hunk 57]
```diff
@@ -0,0 +1,465 @@
...
+    /** Returns true if any of the given entities are embarked (transported by something). */ 
+    static boolean containsTransportedUnit(Collection<Entity> entities) {
+        return entities.stream().anyMatch(e -> e.getTransportId() != Entity.NONE);
+    }
+    
+    /** 
+     * Returns true when the given board name does not start with one of the control strings
+     * of MapSettings signalling a random, generated or surprise board. 
+     */ 
+    @SuppressWarnings("deprecation")
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/LobbyUtility.java:134]: The RANDOM entry. I replaced it with surprise.

File: megamek/src/megamek/client/ui/swing/lobby/LobbyUtility.java [hunk 58]
```diff
@@ -0,0 +1,465 @@
...
+    public static boolean sameNhC3System(Entity a, Entity b) {
+        return (a.hasC3i() && b.hasC3i()) 
+                || (a.hasNavalC3() && b.hasNavalC3()) 
+                || (a.hasNovaCEWS() && b.hasNovaCEWS());
+    }
+    
+    /** Returns the string with some content shortened like Battle Armor -> BA */
+    static String abbreviateUnitName(String unitName) {
+        return unitName
+                .replace("(Standard)", "").replace("Battle Armor", "BA")
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/LobbyUtility.java:269]: Yes. This only abbreviates the unit names for compact display. Doesnt need to be successful.

File: megamek/src/megamek/client/ui/swing/lobby/MekForceTreeCellFormatter.java [hunk 59]
```diff
@@ -0,0 +1,794 @@
...
+        // Owner
+        if (game.getForces().getOwnerId(force) != client.getLocalPlayerNumber()) {
+            result.append(DOT_SPACER);
+            formatSpan(result, owner.getColour().getColour());
+            result.append("\u2691 ");
+            result.append(owner.getName()).append("</SPAN>");
+        }
+        
+        // BV
+        // This takes a crazy amount of time when regiments are in the game
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/MekForceTreeCellFormatter.java:156]: I think it won't help much. "Crazy" overstates it. I just found it crazy considering what little info-gathering this code does. With 50+ units in the game, the updates start getting noticeable. With 500 units we're speaking of around a second for an update, but changing something may trigger several updates depending on #players and other things. So things get slow. There's no single thing to change to make it faster, unfortunately. Updating stuff for each player, the icons, the text formatting, the info gathering all works together. Turning this force fluff info off won't change anything for most games and for the few ones with really many units it won't make it super fast.

File: megamek/src/megamek/client/ui/swing/util/UIUtil.java (hunk 27 above)
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/util/UIUtil.java:369]: This applies the current gui scale to a dialog by setting fonts and adjusting EmptyBorders. This works kinda well with simple dialogs (the host game dialog, for example).

File: megamek/src/megamek/common/Player.java [hunk 60]
```diff
@@ -417,6 +418,7 @@ public int getBV() {
      */
     @Override
     public int getFledBV() {
+        //TODO: I'm not sure how squadrons are treated here - see getBV()
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/common/Player.java:436]: Note that I changed the getBV() function you updated to a stream() a few days ago because it counted Squadrons twice. With the FledBV I just wanted to note that the same problem applied here maybe but Im not about to figure that out now.

File: megamek/src/megamek/client/ui/swing/lobby/sorters/PlayerBVSorter.java [hunk 61]
```diff
@@ -0,0 +1,67 @@
+package megamek.client.ui.swing.lobby.sorters;
+
+import megamek.client.ui.swing.ClientGUI;
+import megamek.client.ui.swing.lobby.MekTableModel;
+import megamek.common.Entity;
+import megamek.common.IPlayer;
+
+/** A Lobby Mek Table sorter that sorts for 1) Player 2) BV. */
+public class PlayerBVSorter implements MekTableSorter {
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/sorters/PlayerBVSorter.java:27]: Another time...

File: megamek/src/megamek/client/ui/swing/lobby/sorters/C3IDSorter.java [hunk 62]
```diff
@@ -0,0 +1,99 @@
...
+    
+    @Override
+    public String getDisplayName() {
+        return "C3 Network";
+    }
+    
+    @Override
+    public int getColumnIndex() {
+        return MekTableModel.COL_UNIT;
+    }
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/sorters/C3IDSorter.java:43]: Lets not overdo it.

File: megamek/src/megamek/client/ui/swing/lobby/sorters/ForceSorter.java [hunk 63]
```diff
@@ -0,0 +1,123 @@
...
+
+import java.util.ArrayList;
+
+import megamek.client.ui.swing.ClientGUI;
+import megamek.client.ui.swing.lobby.MekTableModel;
+import megamek.common.Entity;
+import megamek.common.IPlayer;
+import megamek.common.force.Force;
+
+public class ForceSorter implements MekTableSorter {
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/sorters/ForceSorter.java]: No longer used, deleted.

File: megamek/src/megamek/client/ui/swing/lobby/sorters/MekTableSorter.java [hunk 64]
```diff
@@ -0,0 +1,55 @@
...
+    String getDisplayName();
+    
+    /** 
+     * Returns the column index of the Mek Table that this sorter is to be used with. 
+     */
+    int getColumnIndex();
+    
+    /**
+     * Returns true if this Sorter is currently allowed. Sorters might not be allowed e.g.
+     * when they would give away info in blind drops.
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/lobby/sorters/MekTableSorter.java:44]: You do take things seriously, do you :)

File: megamek/src/megamek/common/Entity.java [hunk 65]
```diff
@@ -1482,7 +1497,21 @@ public int getBodyLocation() {
...
+        // object is not usually replaced. I expect entity.game to be up to date much more than owner.
+        // Unfortunately, entities freshly created may not have the game set. Therefore, fall
+        // back to the old version when game == null
+        if (game != null) {
+            return game.getPlayer(ownerId);
+        } else {
+            return owner;
+        }
+        // FORMERLY:
+        // return owner;
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/common/Entity.java:1514]: Id like this to remain non-ternary. This is kinda important, not something to collapse to a line.

File: megamek/src/megamek/client/ui/swing/RandomMapPanelAdvanced.java [hunk 66]
```diff
@@ -332,18 +332,23 @@ private void initGUI() {
...
         JScrollPane naturalFeaturesPanel = setupNaturalFeaturesPanel();
+        naturalFeaturesPanel.getVerticalScrollBar().setUnitIncrement(16);
         tabbedPane.addTab(Messages.getString("RandomMapDialog.tabNatural"), naturalFeaturesPanel);
 
         JScrollPane effectsPanel = setupEffectsPanel();
+        effectsPanel.getVerticalScrollBar().setUnitIncrement(16);
         tabbedPane.addTab(Messages.getString("RandomMapDialog.tabEffects"), effectsPanel);
 
         JScrollPane waterPanel = setupWaterPanel();
+        waterPanel.getVerticalScrollBar().setUnitIncrement(16);
```
[the remark this answers is not in the document]
Comment (SJuliez) [reply megamek/src/megamek/client/ui/swing/RandomMapPanelAdvanced.java:351]: Um, what kinda of bug? Why, where. It is used in MM widely and I see no bugs. In any case, please give me a better solution.

File: megamek/i18n/megamek/client/messages.properties (hunk 40 above)
Comment (SJuliez) [reply megamek/i18n/megamek/client/messages.properties:231]: The "* Note" is supposed to be indented.

File: megamek/i18n/megamek/client/messages.properties (hunk 41 above)
Comment (SJuliez) [reply megamek/i18n/megamek/client/messages.properties:371]: This has been like that before, lets maybe discuss outside. Easily changed.

File: megamek/i18n/megamek/client/messages.properties (hunk 44 above)
Comment (SJuliez) [reply megamek/i18n/megamek/client/messages.properties:2168]: Doesnt work on Win10 without setting the font of the label to "Dialog" (which is precisely why I hadnt used it)

File: megamek/i18n/megamek/client/messages.properties (hunk 45 above)
Comment (SJuliez) [reply megamek/i18n/megamek/client/messages.properties:2178]: As above

Comment (SJuliez) [reply megamek/i18n/megamek/client/messages.properties:2178]: And yes the character Ive used here doesnt work either :)

File: megamek/i18n/megamek/client/messages.properties (hunk 48 above)
Comment (SJuliez) [reply megamek/i18n/megamek/client/messages.properties:3636]: Probably...

File: megamek/src/megamek/client/Client.java (hunk 52 above)
Comment (SJuliez) [reply megamek/src/megamek/client/Client.java:1029]: Not my style.

File: megamek/src/megamek/client/ratgenerator/ForceDescriptor.java (hunk 49 above)
Comment (SJuliez) [reply megamek/src/megamek/client/ratgenerator/ForceDescriptor.java:851]: I'll use var instead

File: megamek/src/megamek/client/Client.java (hunk 51 above)
Comment (SJuliez) [reply megamek/src/megamek/client/Client.java:1026]: See below.

**Comment by SJuliez** [comment]
@NickAragua and @Windchild292 Went through the reviews. What I didnt comment I put in the code as suggested by the review. Nick's review changes are in two commits, Review Changes pt.1 and Nickaragua review changes; Windchild's review changes are in the latest commit.

File: megamek/src/megamek/client/ui/swing/lobby/LobbyMekPopup.java (hunk 56 above)
[the remark this answers is not in the document]
Comment (NickAragua) [reply megamek/src/megamek/client/ui/swing/lobby/LobbyMekPopup.java:411]: Fair enough.

**Review by NickAragua — APPROVED** [review]
Looks good from my end.

File: megamek/data/images/temp/The images in this directory can be safely deleted between games.txt (hunk 37 above)
Comment (Windchild292) [reply megamek/data/images/temp/The images in this directory can be safely deleted between games.txt]: Still holds true

File: megamek/src/megamek/client/Client.java (hunk 52 above)
Comment (Windchild292) [reply megamek/src/megamek/client/Client.java:1029]: This isn't a style bit, but code accessibility. You separate out the ":" to ensure that the symbol isn't read as part of the word and then ignored, as it makes it into a separate word.

**Comment by SJuliez** [comment]
@Windchild292 Putting this here so we don't have to search for comments. 
Accessibility means what? Someone using a screen reader to program stuff? I really don't know. If yes, has there ever been someone? Even if the : gets swallowed why would that be a problem?

And you commented on this again:
The images in this directory are temporary images used for the pilot tooltips. They can be safely deleted while not in a MegaMek game.
But this is changed in your commit. I don't see what's missing.

Any other new comments?

**Comment by Windchild292** [comment]
Interesting... the file did not update on my end, so ignore that comment. As for the other bit, I'll explain in a PM.

**Review by Windchild292 — APPROVED** [review]
